var htmlConfig = {
    "bookConfig": "v010001103852Ibn3OWt4Fft8HTl1JRjxMdj0NUvyDalyGctwHTm9DaguLYi6IQsvAVtvOeixERk3KXg1JXuzGVp9LQq4JWouPYp3ORhuHQu7Den0CfsvARnuEcvyGetvIbk1EckyGTu2Jah3EepyGfk6CeovGdp8KUrwFcj2DcjzMRnzLZp5OTg2DVt2MTg6Nfr4Ocp5CQpzLdh8BQgwFUh1GWi9FUp6NYv2GaizAbqvIUlvBVg7CfoyKWm1Abj3IXuuIXguKfh7OUl3Lcn7Pfm2DXi9Mbi9CTn9Lbm6AVv6HYp3BWr3DRhuFXq3Lal4Ndo0EZg8Mcv7EVt6Edi9JZr7ISt3Per4IVk9GahzKZs8Aci5HcrwBYkyLZj5Bet2Hbn3Ben7PVqyKbuxDSh6HXmzNbrzAUk4FUu6FRkyETm7PTmzOUr3PeiuISowDet1GdluLYl5Eeh7KXp9Abl8MTm5Mep6Ael3GZp9Lem4CXr5AQnzFRj2HZkyLTn7MXguBTv8Cfh4JVn5FYq5EUp7Cep2FYo7Dfv3BRu8OYnxIQsyBVm4Nal9NfuxAcuvIei5Lfr8BUj8Gdu9DZk7KXu3Mfs2PZt1Aek1AVi9Pei4OaovPRk6Dbu5Idv2Nbg5Lco3PSt3KetvHdjyPUs1Nbr6EfowFWp3Cer2EXg0BcmzNRj7JRj3FSm8Odt5ETjyJag8PbryMQg0LQi1GQouETu7ETr2EUp1IcsuCZt0Adu2GXnuBbg7DZv1Edt4FUj8Jer8KRm3JXl3Nfs8OWj9Hch0MZt5NTtxDclwFQu8IZhuHfu6Jcu9OSh7Afk7HUtxEWuzISt4HZl1NfpxLSizGaj1HSv6PdsxEVh9ETv3NQm6EQp0GQp6JSi7Adj4DZh1Gai4FUpxFct0PUsyMar3Dfk2NVk4BdvyCRnwMVquMSrzKfowATqzBUmwNZl4Idq2CZtxJbo4IWh3MQo6CTj3BYuuMSj1PYmzPVvwCWq6Cdp3EUvyLdl1Eek5FZjvOSqxIfp3JStvOQrwNVl3KQv1OegvAWj4PWmzKQm8CXk6GQu1OVm3BVq0AbovPTvwIRt9BUq1AZh1Kau5LdkvBUj8BYl9MSj7Lbo9Aal5HTs5ATu1Ndg2Lbj8BeuzEeg0DclyEYnzJcm4JYq1ATk1KUj5IblyKUqxDSi5PUp7BZh5Obq2LVs4OYg0Ebs6IVuuBfj8LVn6BRj5Dcs6CdqyMUguLevvIfv0BVu5EToxCRkwPWs3CSn8DQk8DbrzJZs5OVj8Cel8Kbh1LUq9LUi0Dfr0Hev4NYs4LRgxKQkuJTrwDei7Nck3NYv1Ddu9EdpyPai6ObkvBYh1HboxAeq9Jfv6EZqxGdhwLbhvCfj6Adk9MZuxEan6BVi7JRm9GXmvBRguJenuFel1Kbv1Icj7BWgxLfh6PZg1DSq1IUs6GZm6JXuwBRn0BWu6MUt7JYk8Mci0BanvJem2Fal2MVh1Dco8CUu4NRjuCVp9Edm4JZq3EZg9LVm9KfvwLdvuKbs5MRnwCbl8OTh5Cch0AcnwGdm3PUnxPdk9BRp7Efo3Mau5ORmzBev2Han5ESuuCSj8Ofm1KYi9DQtuOXp2MXp6Gbp8IdowJRuuPSkyERr2ETg3MeowKTizJRlvLTr7DXiuPZr4GTuyDcq1JQrwHYr4MWp1NQo7Nem4PUr3Meq9CWgwJUpuNVv5MTqzLRm9JWr9NesuFWj5OSs4BRr2Nfn0BahvPcsuIbhyKWu5FVvuDagxBRoxMckuGTi5IVq5ETlzHbh9ITvyATl1PYluMTg1HdixIasyOZi6OTlwEQm7ITtzPQn3CYi9BRr3CYn6ARn7NTl5NSv2KdmuDbqxIUkwLdswNbpzHcp4DXquCdm8Kco0Hdq4GSh2Bar7MToxKSi9MSr2CYhyNWkzNVk4HSr5PUrvIZl7IbruCUh4Kau2EWr9FVn2Gco0Lfs4Par9HTivJSi2BQo0KSk8GYn6Hfn0KRk4NXrwDUr0IQv6AQsxIQg5ETiwAbiyFYq1GfguLfhzKRl5FTu4IVi5HTqvLRmuPYhuDRn9EXryJbn2OYv8KavxMSpzJUp8NQm0BTpuJcp2KTnvGSt8FcgwKanwDem7OQtuKZp7LXm5GXnuLai1GRk2ASguKVsuNcp0Ndl3LTm6JQuvNUu9ESt4OSi4KUv2NWmuOWszKfo9Cbs8GagyDbo9Cdk9JbszCei8FdjxNQr0OfmzDTn3GfvwOWouOdp4PXl7KYpuNer3CSq7PUkxNat8CZs0NSr1BXk0NSp6FYn1Peu9CVv1PSs7LUlwJZg7AUnxEfp8ASk4AUu4Eal7Jfv2JSpwNZl7MRu5CXj3OZmyMfi7LVm2Bch9DZrxKekvKci2OUj7FUp9Bcn4PSjyAUr9CXsvNYk5LRi4CRjzIXj6Ebn1Lbj2Ees1JfrvMbgxHcu4BXnvLYpuLVrvKRjvKWu7Fbt4DZswHQk3HWm7ETk7GTsuPbpxHRi1CXn3Ccj4NXr8LWtwCdr1NZhwJRvwLQg6MQhvIdvvPei1KXg5NSh6HQqzOen8Afl7JYl8Gdm2Naj3Kfr4Acr6IZk9Afi1Jdq1Jcg0JdrvOegxBStzMbn6GXizBYv5PUm9Mbl3PemwBTkwMWr0JYizMdg3Gdv2Cam4HSp7BSt2Iem7Hds9MYmuJXvuGfsxHek2PVqwFTl0JSv7FUo0MZq7AVt5ITtxFVk4ISqvLep5PZq6JfovGYl7BYu5JQtzPekyOYj0BXo1DQn0MTr1Leo5KVj7HSnxDZp0AfqyPbn3JXhvOXu0NapuGer6BemxMRv9GTt4Heu0FSm6ATm6BfivPSn6AZi3IeszLdtzAUo6ORvxLRgxAfi8Hfh7LVk2KYm6FTk6BTn9CXn5BUluFQi4Ebh9MevwOXowHdvxEdmvCaryHat7GUt0Ieo6JetuGau0Mdm5DQs9Jdk7KaivOUi7LXt8Oeq8FWixJSi0KUk2KWo2Kfj5Heq0HXj3NVuuHfh1Ocg9KWk7MVsuLbp3Pao6Ecm1Pdh9IZp6Pfr0JZu7LenyJZp9FQnxKdgyHeg3Mdt4DRg1BXq5BWozLWk5OWhvEbn5MetzKSsxORouPat4Lao0Hbo6Kfm4DXt6JSt5CUlzBUr0JTg7JXmvAWs5OQi8Jfr7FfjyAdt6EVv2LchyPQo1JdowFUv0Cfm8Beu7CUtuNTh3Jfk3OYv4MSq6Neh9MRnyFYr8NQtuIcq3DRh5JYh2Afg3NTj4DVgvAZizIXr1Ddv8FXrxFfi9Ncj2OWs1EbmyDbs9BVv7EaguGVl0OYpyPWv3KVm6Peh8DYl6CdrxKWp3EdtwFQm6Cfv6FQs9Can7OQh0EeqyGVi2IYo0Per5PSrvEbjzIVp2NdmuDRg2Acg3JcnwGQvxKQsuMSrxHdl8OZg0HSnwDVjvKSl4BTmyJSq4GfuzDWp5NWpuBbh9Abj4AWo3Iej1Cfj8Bbg8HVluBRtxMbu7LUn5Jfh4HZswAYuxDaryJRh0Kau1HSv9Oep9MfrzMei8Lbo0Adr2Oam3IXj6BVj8Fcu3JWm2IUmuFesvCRr8Ecr9PSl7JWn2BfpuLes5Cdu7JXq3GUq8PfjuOTgzDdj0Kdt8AesuGVp7Fao0PSi3IRszGXmwGYp2ETl6DTuwOQk8ITiyFfqxCYt7Lej3FRkyMep5Ieh7DRvvKZj6BZo7Nbl7ORlxMWhxIWjwLWswCXtuKej9PSk6PZj6OdqzGfn8LZmvNUlwGXr9KZn0FZp1PXh0Mcu3ERu7NbhvFbjxASv1KUlxEXk4JUmxDZrxCer2KWvzNco0Cbt2MWq0CSr3BVo6BWswBcj2ASg7Man0GWi2Cfs4DVg4DYj4CYgzOQu8BSi6ATqwGbnyNQgyKai3IejuJZkzEQm6Ldj8Lfo4Fcu4IRuxGUu8EWmzFbu4FVoyPVlzDbr4Iam8MRk7JTsyIXpvNTn4EelvGTgwLUn9Cbq2KQuvAcv9ERqzJSovOel1Der7CetwMTi5EWpuNWhzPVk7CbqvLZryPUquFcq9MfkuHds8BVk1Bah0CZn9LQhuCeg4PZovLcr9EThxEZvwNXt6NfsxPaj2DSrwGei2LZrwKUszPSiwKbg5Kag1FblxGWk2BZo6FWmzGVlxFUtxHQl6ITmvMYk3FenvBQivFTl9KTqyKTgxBVo8NRm4BQvuNbi7HaqvEdmvAcvyFTrwEbhxDTp6MToyCdiyJSuzEemwGXnyEdluKUmxCRp5LRj0OQjzEenwOdozFep2DSq5Jbu9NZm5Ndn1JVm8OWv6LXlwEXi1JbvuDWn4OZovBauwJSizDVgyFbg4IXt5OSv2CVp4KfowFSsuFepwEUu9Jcp6OUlzAUm4JXh8NZk0JVl7Dav4KRs7GQh2CYl0JRr6CQq7Ceg4CYt7LTs6DWh9Nbh9KRnuPal5HTjyKerxFZkwDRsuLXn4PVg1DSuxIRvuJTiwPUp0BTvzJWn6Kbj1Bdu8Pav2LTh1KSs4Pdt4GWt2LTt5Icq2HQgvAVkvDYo9LRh8LZl3IRp5KVn9OTn9Cbt6FcmvHdu1Hdi0DXkzCdsvMapyOTi6Dcq7FSn3Aau2ATs8FSqwETt6MbnwAfq1OUv8Ffl2HavuIfqxEbmxCSk1BRtuDbi9IWhxFUh1ETnwLer4BYg8Hdo2Pbg6HcguLSs4Bfq3Pes6Kcm6MavvEXq5CSuyKetuHbgxPcs1Ocv5Gcn8ObluAXouGUivDeouDXhuGRg4AehvAYpyPQr8Ddv5CQg8KRs2BVnzLZo7GXs1Gag0Pev5HXk8AVnuKbj1Neh8Hdl7HUq7EakwBdj2ObrwHdk6OZl2FRpzKRjxHXlxGRjxMerxIel9EUk2FQnyISpzGcvwEbkzObtwIar4EWi1NRn3Nai0MbsyKfi8EWi9BanxJet9AQi7DSvvJTkuGbsyAUvuJbqzBau9FQo5AVi7HXsyHXi0BVl7IegvDfsuPahyPQmvGXkzDVquDSgzPbryPfh5Nau2HYpuHUj6Aan6NVizDTi7Mdn6KYo8BbtuDbj7AWixGaqxMVh4KSg8CegwPUgzKZsyDaj6HRuxBWh5ARt6LUl1PZs8EYp1Hel2Ifk0Bcn7PcmyHVp9LYnyJal9EepzIZr4OQv6DXq2AQsuAUh9NXq9KYl9Efk7JfuzJTuuAVgwIam4DUh4MTvxIQmzFeiwOUpzMbqyOXozOXh7PVpwCbh2PUqzFfi4DVr9ITovHas7IQj1PSt8BZqvEfg4MUvxLXs3AZn1Oek0IWp9DZjzAen6OQsvLUvxDSi2OdrvMYowEYhvCQn3DUjxBfiyMWuvLTm7GZq4Gej8Eev6OQpvAehvPUp4Ibl6AZnxEVs1Bfg8HdpvBSsxMYs9FXn2BQj0IQo1JVn5ASkxBQl2Bem5LdizFbg4Jbr5Maj9CZs4Kfp2Ebk5Ier2ORu3AWiyNRsxLZt8JUlxFWi6JYkvPWpvNfn4Hcj0DSuxKctzFXg8MSg1Cev4CRgyIblyOdm5OTjyEZn0DQk4HUrxJWm9IZtzPau0BdhvDUsuBSg5Nau2IQs6AbkvObs6DXn5DcquGcn1Cfp6OQlzIcn1ETsuMUv1CfpzEbt5Jcn7Feh3KVi4CYg1IThwPco7KTm0FUvuIYtxPak2NdrzFapwKRvuBRn4JZo3NUowKRgwLSi1NYlxMXg0KSt5Cer9Ifi3MXp1Hft1AYj7BZs9KbsuAal3CZsxBVoyDeh3JWtvKVs9NRsuGTpuNfl6OTjuHal1HXq6Nfo1Pap5JTg1BVn8Dci9CUtvPfm5IfqyBdnzERlzPVv7MWj4LXhuFYl0OWm5EWlyEcv3JXhvCZi7NUvzGel1MQhzJYnxEUn8KfnzBWu3Ldr6Nch1IZv4KTiyGZv0Bdo2PXv2MUqwPdvxNdp1ESr3LQl9KUu4LRkwDanyBXi4Cek5Cag0BZg4HUl0Lft0OTuvEdnxAWm6HZtvBTk7Gan9PTtuKSv1OSq9Idu3JYs1Ddk7CXr8HTs8AXjxPWkyGag9DbjxAQsyIUu5LXh4HXr8Aeo8HWuxGWm7MXv4DbuyATpyHerxHSlxJVk9NdhzGXryNXh6LYvvBes3BVjuLUv3NdlxLYk2CVn5DYr7OXv5IcvyGXg8IfiwJer5NWkxLSp0GRi0NZrvEZm9JSjwOeq8NYv2GSvxCRsxDbm1Afm6McqyNWhvBdu5JUg3FUozKThwGbp2NcrxNap7KYp2LVtwJajzESs1NdvvHUlzDbr2PVn5DRi1EbixEWtyNWm6PVt2McqwBRl4Oak6Edh0MUi9Bbl2Cfu7FfvyDTs4PSnuFXt9GXuzAYp9CWi7IYq6NTq2Iev6Nct5Gaq8Obv6EVj9MYiwDap1PUhvMdj4Cfu4CUq8Dak9PZj8MfmuAYs5MWguCRq5MWh7Mfl8HYi3Kdq6NSp9Kav1KbgxIWu4ORvwJTuvJdt5HQn5Fbi9NQj0BZk2FSlyHRm1GSq1FUl2FWm8KVs0JQs3CYk1FTm3BSk2JctxASi8Ncv5GZhxGfu1FYs7MQizBXj4OXgzFTgyAep4MVu4DehxCYuwLep8AViwAfl3FRh6Jfv2NQl1PTvxOSr0Cdn9ETn5MQh6HVj7LRj1PejuLZr4Fck5AekyMei3ESg6CTl3EVg3EQs0FasxBal8NQm8MYj7CRo1Gfs5LZv2Kfs4EQk2AVg9AUn7Oem4FZgwJfm6Oco1DZs5DZt7JWg1Mco4Mbr8HeqvNTqwGRs0Ceg8ATi7NZv3IZuvIcp8NVt6Nfg3PWl6GWu0Ddv9Obv1HXvvGVoxBXh6AUh1Maq9LZg0Lfi6NbuwGdsvAbi4Lam1FUt8IQjyOchxKbv4Dcg6CVq9NSu9FdhvBflzPaiuOYryDVj8Aer9Fet9GbiyLZpyLXm6EQn7CSr7McovNTv4OcnxIas9PTn2BYhzGUo0KWu9Jci5GRm4PUt1HXt1Pat3OSh4Gbl5JXr7DWt9Aeo7Cft8Neh6Odn7GXm9NVj0JVrzMfsxMRhxNTuyPXg4Bbh2Cat0Gft7Kav1Ccm0ActuPcuuOUqxPSh7FTo3GYgxFTl5KZnwGTi1Pch5IZr0EbhwPWv9Gen3LVixNXhvMUt5OTp8Ffv6LQj2FRg5KUguKel3Baq1MXu2LXjuLei0FVj1LSg2GVhyPVtvNRlvHUovOXo5MWtyMQg4ARi2FXtzAZo3Dfl5BUj1CYg4Gck6Feh3EQs2HQn7Pfk8MSvwDbjuBdo9GbhvIWv6IYhzHRp8Kbn6AVv2IblzGZrwISu5GYm9LSh7ISu1LQowBQkuBbvyDZv4Ldl8OUh0JWo6BZj5IVq6HQiyCUl0HTm2IVguMSoxFWn8Mfv0GRq1MVl5PTv1BZsvJYlzBfjuFZj2BZiyDel9DZouIZl4IdpwMSm9FRjuHaq0Ncp7MTuuDek6GWn3PXlzIXgwHWl3MXh2CSvyFTs8IXhwIWq6ObivCQsyEbv4AXlvOYkzEVsyFUk6NZsyFcr6OWr7Kbr8CRr9IWo9Lbt3LXlwARo7Meu1MXi1Mcg7JRr2FXjuHak7Ffh5MXqyDXp0Gdv9EanzEch5CQk8AcjvOQguMTuyKXt6Jat5OZg0MfjzAcr5FRo4MXg9MVk1GakvCav1Ffv0LcnvFemuMeo4NZv6MZlzObh0LakwKUn3CTv1LUkwAQt6MbhxMUqvCZuuGfsuPTozEbn3Hai4CfqwFSv2Hbi6DXlwCYhwIRi0FVtvIXm7JVi7JZn5ITn5DdqxJRlwCehxLUh4MYs5Gfo3PZm0OSp8Bdn4EVv7LQs7ITo8DWoxIRt9Nao4DRm7ETiwGbl1FYsyEdq9Gbo1PTquEar5Eds9EdqwJbvwPUrvIZuzKViuLZv3Nbs3OYnzPeluCRjzMYu4Icq3OXi3JZg8LaruBdn5ITg0PRsuCRo0FYp8LYl8GYpzGXl0Hcp6Ofn9LZt9JSj8GYmyOaivETo7JZivJbi5PQs1Nbm6GVl7Cfk3EQm9NfnzLUg7BWl7PWlvFYrvNWh3Nbi8PYtxDUr7LTgxIem6IckzGfqvATg2MRr3KXkxNahuMVh9EYn8DXh3FVqzDepwAfp3Iei0IRquIbmwOVh0KdgvMWvvJdiyJQuyKTpzAYm5Leh7Oat4OVt5LWjuCejuHan7DeqvMWg7BWt9AYl4CQhvIQi7PRsuPRruHSq4Oeg1EVsxHfm8PRt6Fdl5CWsyJRt3PfsyMXh1FSh1MQh3MTp2Cct2GUk4OSqwOYjvHfv2JYl2PXu2Kat8CSt5EWs2Efl6FTt1MTi4KTo7HZt5IdnwKbnwIWg6EUgvORh0DTu0Ffi4LQn0FTg7LfrxKYovBTryMStuBVsvEeluEQg8FUoyKTtyKUk9JepzBUtwKZjxJch5NYhxHUuvEUl3PZqxEdsvDXo9GYrvIdr5HSj7HaqxOUs8FUtxCao8Mam1FSg5Fer3NdozFavxEdm1Peu4KYjzFaouLVkzOUk2FYrwKcm4BQn0Nan8Pcn9Ocj1MUg4PclxOagyEcj5Kel7KYkwLaq2IXtuOYkuCZi2GcnzFVtxDYi6JbtvAVm9CcnzNXqxOcm5Baq4IZh7MSp2NTnuBWkwCQizNXs7JcvzNWpvAfi7BXv9ObnzCam4MaiwKVk6ORnvBbq1Pbi0OSlyIdi4MUlwIRjzCZk0NZvwJfovOSt4KfqzEes2Adu7Pdh1CVh3Kfj7CfpzOXvvKamzDfuuBQn7JWr7Fdp0KajxIam8EYq4GfvzMaq7EequDSq4HSmyIev9LTs4CQnuCcsvMch9FTkwPYn3AWpyJdu1DYg6MYq5Cao6Acn5Pds9FTnxKcr0GQs7PZl7MVqwOelyMYp0MZsvLcu3Fdn7NVpvKUp4KXv7LQg7HUm9Pem3DQj0Dfu5NXq1AVszIUk8IXg3CYvwOcs6PQsvPYt2GXr6Hes5EQt4EUv1Adp8OapxFXlwCWn1HTmuEXs7Der0IUo2Hcu4KZp7JVn8EaswDcrzKVo1Lcm3Eep7Obh8Ibn5Ffj4MQq6FWvxESuuGUh4JYrvCRv4Beg0NTnuAUs0Hcg2IWnuLQpvLUvxFShvKQowAVp6KfpuNbu5OTlxEdgyISnvMaj0EVv7GXj2NajyDbm8Hag9EbsuNdowMctvCRh1GUlvPRo3IalyPek4Cdp3FTkxJbv7Jfv6Bev9JWmwFYg7BaiuDYh6Lfq9OWg6AVj5Pao7PQr7DfmvLVm7JQs5EUi7BWiyGZl4Abk0DQl4NSn9Eek9NWv4AQj2PToyFXi5Acv9CRr9Oeo7BUgzNYvvNSruARqyKSi2PWh5FfqwEXlyHWp9PTrwHZtxMWl4Hft2MVj1Mcs7HcowEfryOQr8DToxKVsyFZn4IVuzJSswBan9Kch5HSkzIVo4Kao4OTp9EcpzKfm5DUk7Jdo6IRo8LbsyHdv2BcsuAZo3Aem2EWm2ETl2IQj5PQp1PbhyCSn3ISmwCXpvIUvvFUiyESs2ETv2MXo9LTn3BbvvNciwLUp0AZl9JRk6NdgzESt5FZu8Dch8BcqvDep0Ifh9Adl9OVv8Jcs9HSs3Eev2Bbu2OXq5FSn0JWgzARq8Ceq0MYn7IYixORm6GSj5BYs0BYp2NUi8OamuIUk6OUj4HUj9IUp3BUjvHaiuIdk2KcgwHdmwATv6HSt3AYu1NTh6Ies3DYgzFcmyNTrwGYi4Gdm1PZi9AdrxBUk4HTg3HUp8LSi1ESpzFdozNeh7BYl8JSquARg6GZi7Bfu3FWq9JSr2Jds3CWnyHSp3DZj6Gal7PRk9PfozKet2GZi9LTiuMRizBZhuMbt7NSjyLVs0NUs4Jcg2EfnuGTm7GZiyFTkyEep4OevyFervPUu6PVm6ESr6KWu6OXkvLVt5Bdh8ITv9HSk8Pdo1FSuyDVl0LSu1EVszFfj8LYg3PchzIfmwPUn7Ifq7NSkyCZv2EQnyIdruKYu9IRp2AakuFbo8ORn5EagxETj7CZp7BXr1CYrzCauvEeu9FZg2Mfu8AegxNam9Hdi0HTi8AVg7GTivHbg6IZlxGapvPbu8EWt4Pbg3Pbi3FZqwFRl7Bbt1Ebh6DVr9PbsvBar8Fbs6HbiyMWrvJSn3Ocp2Cbj8Nas4EcvuNbtwPRg8OTr4MWq4MZhvOSlvHZp4JahzNQt4Mdg8Idm8Icn0IcgwMSmyPes4BTpwNYm5JWr2JfluLTpxATu7ORh8Neo5OetvCSi3MTn2Efo7Gas4FYo5BTgyDbm7IQg6OYi7IUozEVt5FRt8GctzHTtxMQn6MXlyHQuuJdsuDah0BTm6Lcm7Oah2PRg4Oet8HSs0Obt2DVqyFfl4DUv6MWsvARkuMas9AUk0BXhzDdv5FegyBfk8OYouNYm2EStwLckvAbq6NTr2CRsyDdt0LVjzJUv4FWt7CbtyETg5FTh4HTq1BYjzHRrwEWg1Leo4IZj4NdmwIbuyHVswGRn0CQg3GbrxHftuDThvKRoyATqvMXh1Ibs7KYi7Fes1KTj5PclzHRh7GUo4EdnuKevyLXu7FVhwDVvxAdg1Gbr7JTm7AajuBRp2DQv1GWivAQl8BXt8BUuuMUi7Iaq2Nar5PSj0MZs5CVowJcj8HdkyNVmyKVh4FWo1JRoyMcr6PYtuAYqzMalzNUsxMVv2LXg3NVluIbh2DTo1GWi4PcqvKTt1Nah1ITk7Abm1Kdt2NbvzHWn7ITpyEbp8MWt8CagvHXq8DXo4Ceo0Fft7Hft4GVsuFTk5KYvwCag2IZk5FZq9KSm5Eah8NSp3KVm8BUj6PSk0AXk4JapyGYlwMaj1KQg4Aam9Bci8OfkwHanxKemvMVs8EQl6EXtvEVm7Ndv5BfnzOTuzIeqvNYu1DYt6EWrwFbg6PUt9CWi7IajvNRj2LQruPXt0KfruOXp1ASuyAVu9KYqwAen2KRi4MShzIYt6NYn0IanzJek5PVk7EXkwBfk0MevzMfp1KegvIWm3HamxPbpxMVq2CfnyJZp7CbruDZgvFYrvCSlzAcl0PVm5Ick9Lbs8DRq8IVlxGVi1IeovJWhzGYuvFdvxBSi4HQkwHcvyFYi2FatyNfkuJWtuDcgwPbn5Jej5BQuzGThzIStuCYlwKdj6BTrvHSt3HUqvBfk0ESguHav9GVm9CYh7BcrzKZhwBWjzHfn8DSu2Jcr4MTv2KRq3PWv7Ebo9Pcm8FRk0MSn6HVnuIUm3HStyKZivHanuMdg0DRpwGTj1DZhwIVo7Ddo4Hdm3ORm3OahuGXi2Ebi4Kfi8Jdp8JemvHQsxAVh6HQrwLarvHZh8Pcm4FbozJRs5CXvyHUluCeg7LQg8FUr1DQm6CRgzKQk5PXlvCdrzDfh7Mbo6JSt7MSs4JQg6FYi9Fcg9EVquOQq4PbkuNcu5KYv9CYi0CZlyIWnuJfj5PXi1JTg9AWr5Dar3KVs7FZkxMVt6Lfo5JTkvJdq1DVnuBSn8NXhuAduwMZp9CUj7Acg2JSq6JfmvPXjuCbl7DanuIbn8BYhyCVl4ISlwCRj6EauzMTv4BXozOQu0Jer0FQvwDYj1KYvvHYg5ORs1ASn0MSuwFWg5PRvyOYgvMdr6IZo2NbixLak4Gdk9CRh2KXnyIYuwOarvESo3PRhyNWquHfquMeiyKQrvHdmyJRl1OWm4DcmuKSn7JelyEXpvDRj5JflyIRpwCVp7CXjvEQjzAbn2Kaq7Aat7LXjvBSgvIRuuASg3Hfg3NWlzLQlvCTp8AXm5CQt2MSg1AUlvJTk2DQj9DXl9DRm1Hev9Fdo4BTr6AatxAeu8MZkuCRtyDVm2AYt0Gfo6DVn8MWu3JSq1HYhzDZs5KdgzOWg3LUlwEQtwNalyOft8DUj6PZp8KTn8FVs7MQk7Nbq4PZnzPYjwGYk3HVjyAasyIQv5LQg5KbpxIbg9Fdt1PbqzIUu4JRn3ObvuPdozIdu2AVo9Ebq2IRlwNdpwLZv6KTh5OYl4PZu3Fch0NcowNWg5FZowGYo9CRmyAauvBet8KZqxCep6CXv0KQivHcvxBUo5MVp9PZt6Dak4KTm6Cft0CQhyOQm0ATmzPXhuFcn5FTq2OUl4AYl0MRh2Pdt1ARg5HWi3PUs1PYo6KWs0NZp7HYv3BftyEYi3CUmvIalwGWq3Kci4AdsyITgwPUo6Gdq2FXp2AQm7GSu6DcoxEcrvISm7GUszFYq5OZuxEfhvFSnwFcm0FeoyMSv1MZt3DSk7PTr1CbtyKTr8KekvOcv0OZp1BXt1Jcl2EZuuHVh4MRn5GUl2IXg8HYv1BXnvLcq2CZg1BVg2KVmvFck5AUqwNcjwHdi0KZv3MQt7OVl0CfowLfuvHZr0IcrvNZs5MUq2ERvzIen7Aag6FYo8KWt1Lfq6Dcu0Adt5DenxBaj6PZs0GWr1NQo6KVj9GQm9Lah8JVk8JRg3Cfv9Obo5Hdo1MRl0JfhuPWm6KTg3HVj8MRj8ISm2BYl9BeryGQjzDco0KRu8CVu9EYv7Cci1CbkxDUs9PSgxJVo9ASh8Bct9LYh6ESn9EbivFej3NSp9Lav9NZq5FYk9MVu9PVp3DWm7BSv4KUmvObq4PSg0DcvwNep0BbgxDYq2MRqvLWjuDVu0OZv1CbjwGZowMcmyNTs8ITk8Kbr0KelxCapvPRtvBQhzIZjuKctzFQq5BTs4Gao7PUm7Mdq1CXuuIdtwKQnwHar6JctwGbi0Ceu5CfmxMWjzNetwHSp9Mcj7GUvvGai1LVl4OdgzEbsuJShxFVo7Gct4HWrwIdtzDQswNemxKSgwFWpxOVkvFeg4BYk8KUi5Gbt3PWv8OapvOTh3CXuuLRh0IenyLbszKXswPQmvDZlxESqyPbq7GQh2NSu3KTq6PWi7EetxLYlxATl3BWr9BStxFVlzHSl9Dcu7Mbp3Ldu0FWp5Gbo8NfrvCVh2NWjzLbh1OYr6GdqzNao9DVtxKQu4Mcs7AUt0KSqwNfjvCfmxPerwOSrzNYmzLVtzLbuwHfg0HZpxGWv7IbvxJekxDXuwAejxOVu5CXkxKZt7Gal6MTu5Hbn7Pbp1HdmuDSqvPci4Pcm9PXg7JZq4Fdl9NWs8IZo9Lbs6Dfg5ESuzEdn4DZq5BUhwHdk4Ddi0FervDTmuObh7NfgvBcl6Hdj1MevwMcl2Fdr9LVq7CUg0KXswBTq7ETrwAfl6BYmvOel0Fdg2KVl2AUu7BYr9DemuHXu4DXoyKbjyHUt7DVkzDXm0BZg0DcmvJRh9NXq3LWp6CSp8NUo1DQi3Lcu0HZn4Par3JStyHQq8Per2KSi3GTq9GQp8Cdi0KQn9Jan1PYn2FVqvBXi1Lek9BQr0Cev3CVh1FcmyHdhxPeowNbu2Oak8Cfu1OWo7HSr0AYn3FZn3OduwIZh5MSm2OZk9IUgyFSs8BUr8KUrvIbmyETl0IRm7MUg8PZj7DYuxGWmwEXnzHUmxJfoxIRsuPasvAci1MSlzJWp1NWkvOem1HRjzFZuuEYk1KXg3FchxKdt9BRo1DUv6IWn4Ebp6NXq5ESkuEWryOaouJcqvGbovCVl8Kcv0Pfq4Jcg1MSv7DYu0BRnzAboxJcovJRu9BUm8MeuzLYoyDYuxHbk8CRi4ETh1HVv6JUs1LYh4MUuzFSo0OUl0ISjxITgvKcluOTs5BXjvBTlyJei2BarwBRq3EUt2AVkuLdr7Jcn4HVn5Nds2OZkzDemxNXl4PRn7Ibg7JXk4HfuzNUt5NcuuEWi7IQp0Eeo7DZluKQr8GQpvOVl3IUouOeqwAehuLWt5AYt0MYvzPcu7CRl3LZlwOUpyGUmuKfmyBVo0BXq0DZuwBZo8OXk0AfuvEWnwHUu9Eel8BZmvGRk9NXp6DRnvKQp9CYkxHSi0DRvzGfk9Ddr2JUvxPWuzNRpuNQrzGVs1KXg4ERj4BZi4Pfm5PXu4IQpwMWt1CWv2EUr1AcrzOWhzOQpyNao7KQhyMRo5FftwOej2Iep2KXjyNUt8FXnyBTo5McnuBWgyCWuwLZg2Bbo1JZi1Lcp8MTvyLeu7PRi1Nev9IXpxFTm5KTp2HZh9FSu2EQjuATr4Jdv0Gbp2Kar8Kah7BYsxCSvxLSruCYi3EdjuJcn3BSp8KVuxDVvvFXn6Caq9NYqzBWtvNdlzDTsyHRm3Bdo3LWrzIXh6MZv5PSh7GQk0FdiwPQt2LRh4Lcq4Nak3HagyKRr3JSm6KVt1PWuzAWn1PSt5Kdv4Deq2MYl0Ocr8BXqvDfo6LQuzGau3BbjuOaq2JXp9EenuAQlwEYmvAbnwHZk2DZl8MUhuMSl5CRm6Ndm1Ieq9GRu5OUlxOYj5DVhvEXlvIWnzAen1HWr2IaqzLTt6Mej2JdpzDcovPSuuDWn1Ncr9Kbv0GXg1BTuvDXk7MYi9ASvzERv9KdryNZt2Gft1IYhxPXEekxGVjxHVlyDVk4DWgZa3aba025d4630c8c468325055dbc59fe20",
    "aliasConfig": {
        "appName": ["", "", ""],
        "totalPageCount": [],
        "largePageWidth": [],
        "largePageHeight": [],
        "normalPath": [],
        "largePath": [],
        "thumbPath": [],
        "ToolBarsSettings": [],
        "TitleBar": [],
        "appLogoIcon": ["appLogoIcon"],
        "appLogoLinkURL": ["appLogoLinkURL"],
        "bookTitle": [],
        "bookDescription": [],
        "ButtonsBar": [],
        "ShareButton": [],
        "ShareButtonVisible": ["socialShareButtonVisible"],
        "ThumbnailsButton": [],
        "ThumbnailsButtonVisible": ["enableThumbnail"],
        "ZoomButton": [],
        "ZoomButtonVisible": ["enableZoomIn"],
        "FlashDisplaySettings": [],
        "MainBgConfig": [],
        "bgBeginColor": ["bgBeginColor"],
        "bgEndColor": ["bgEndColor"],
        "bgMRotation": ["bgMRotation"],
        "backGroundImgURL": ["mainbgImgUrl", "innerMainbgImgUrl"],
        "pageBackgroundColor": ["pageBackgroundColor"],
        "flipshortcutbutton": [],
        "BookMargins": [],
        "topMargin": [],
        "bottomMargin": [],
        "leftMargin": [],
        "rightMargin": [],
        "HTMLControlSettings": [],
        "linkconfig": [],
        "LinkDownColor": ["linkOverColor"],
        "LinkAlpha": ["linkOverColorAlpha"],
        "OpenWindow": ["linkOpenedWindow"],
        "searchColor": [],
        "searchAlpha": [],
        "SearchButtonVisible": ["searchButtonVisible"],
        "productName": [],
        "homePage": [],
        "enableAutoPlay": ["autoPlayAutoStart"],
        "autoPlayDuration": ["autoPlayDuration"],
        "autoPlayLoopCount": ["autoPlayLoopCount"],
        "BookMarkButtonVisible": [],
        "googleAnalyticsID": ["googleAnalyticsID"],
        "OriginPageIndex": [],
        "HardPageEnable": ["isHardCover"],
        "UIBaseURL": [],
        "RightToLeft": ["isRightToLeft"],
        "LeftShadowWidth": ["leftPageShadowWidth"],
        "LeftShadowAlpha": ["pageShadowAlpha"],
        "RightShadowWidth": ["rightPageShadowWidth"],
        "RightShadowAlpha": ["pageShadowAlpha"],
        "ShortcutButtonHeight": [],
        "ShortcutButtonWidth": [],
        "AutoPlayButtonVisible": ["enableAutoPlay"],
        "DownloadButtonVisible": ["enableDownload"],
        "DownloadURL": ["downloadURL"],
        "HomeButtonVisible": ["homeButtonVisible"],
        "HomeURL": ["btnHomeURL"],
        "BackgroundSoundURL": ["bacgroundSoundURL"],
        "PrintButtonVisible": ["enablePrint"],
        "toolbarColor": ["mainColor", "barColor"],
        "loadingBackground": ["mainColor", "barColor"],
        "BackgroundSoundButtonVisible": ["enableFlipSound"],
        "FlipSound": ["enableFlipSound"],
        "MiniStyle": ["userSmallMode"],
        "retainBookCenter": ["moveFlipBookToCenter"],
        "totalPagesCaption": ["totalPageNumberCaptionStr"],
        "pageNumberCaption": ["pageIndexCaptionStrs"]
    },
    "aliasLanguage": {
        "frmPrintbtn": ["frmPrintCaption"],
        "frmPrintall": ["frmPrintPrintAll"],
        "frmPrintcurrent": ["frmPrintPrintCurrentPage"],
        "frmPrintRange": ["frmPrintPrintRange"],
        "frmPrintexample": ["frmPrintExampleCaption"],
        "btnLanguage": ["btnSwicthLanguage"],
        "btnTableOfContent": ["btnBookMark"],
        "btnExitFullscreen": ["btnDisableFullScreen"],
        "btnFullscreen": ["btnFullScreen"],
        "btnHome": ["homebtnHelp"],
        "btnMore": ["btnMoreOptionsLeft"],
        "frmToc": ["btnBookMark"],
        "frmSearch": ["btnSearch"],
        "frmLinkLabel": ["lblLink"]
    },
    "meta": {
        "htmlTemplate": "Popular",
        "theme": "Default",
        "title": "Menu Brothers",
        "description": "",
        "url": "https:\/\/online.fliphtml5.com\/hbozp\/onfk\/index.html",
        "pageCount": 24,
        "pageWidth": 612,
        "pageHeight": 792,
        "template": "Popular"
    },
    "project-config": [],
    "bmtConfig": {
        "tabs": [],
        "onSideEdge": false,
        "hasTexture": false
    },
    "videoList": [],
    "staticAd": {
        "haveAd": false,
        "bgColor": "#000",
        "bgOpacity": 1,
        "interval": 0,
        "adPosition": 0,
        "data": []
    },
    "language": [{
        "language": "English",
        "btnFirstPage": "First",
        "btnNextPage": "Next Page",
        "btnLastPage": "Last",
        "btnPrePage": "Previous Page",
        "btnDownload": "Download",
        "btnPrint": "Print",
        "btnSearch": "Search",
        "btnClearSearch": "Clear",
        "frmSearchPrompt": "Enter key to search.",
        "btnBookMark": "Table of content",
        "btnHelp": "Help",
        "btnHome": "Home",
        "btnFullscreen": "Fullscreen",
        "btnSoundOn": "Sound On",
        "btnSoundOff": "Sound Off",
        "btnShareEmail": "Email",
        "btnSocialShare": "Social Share",
        "btnZoomIn": "Zoom In",
        "btnZoomOut": "Zoom Out",
        "btnDragToMove": "Move by mouse drag",
        "btnAutoFlip": "Auto Flip",
        "btnStopAutoFlip": "Stop Auto Flip",
        "btnGoToHome": "Return Home",
        "frmHelpCaption": "Help",
        "frmHelpTip1": "Double click to zoom in or out",
        "frmHelpTip2": "Drag the page corner to view",
        "frmPrintCaption": "Print",
        "frmPrintBtnCaption": "Print",
        "frmPrintPreparePage": "Preparing Page:",
        "frmPrintPrintFailed": "Print Failed:",
        "pnlSearchInputInvalid": "The search text is too short.",
        "loginCaption": "Login",
        "loginInvalidPassword": "Not a valid password!",
        "loginPasswordLabel": "Password:",
        "loginBtnLogin": "Login",
        "loginBtnCancel": "Cancel",
        "btnThumb": "Thumbnails",
        "lblPages": "Pages:",
        "lblPagesFound": "Pages:",
        "lblPageIndex": "Page",
        "btnAbout": "About",
        "frnAboutCaption": "About & Contact",
        "btnSinglePage": "Single Page",
        "btnDoublePage": "Double Page",
        "tipChangeLanguage": "Please select a language below...",
        "btnMoreOptionsRight": "More Options",
        "btnFit": "Fit Window",
        "smallModeCaption": "Click to view in fullscreen",
        "btnAddAnnotation": "Add Annotations",
        "btnAnnotation": "Annotations",
        "FlipPageEditor_SaveAndExit": "Save and Exit",
        "FlipPageEditor_Exit": "Exit",
        "DrawToolWindow_Redo": "Redo",
        "DrawToolWindow_Undo": "Undo",
        "DrawToolWindow_Clear": "Clear",
        "DrawToolWindow_Brush": "Brush",
        "DrawToolWindow_Width": "Width",
        "DrawToolWindow_Alpha": "Alpha",
        "DrawToolWindow_Color": "Color",
        "DrawToolWindow_Eraser": "Eraser",
        "DrawToolWindow_Rectangular": "Rectangular",
        "DrawToolWindow_Ellipse": "Ellipse",
        "TStuff_BorderWidth": "Border Width",
        "TStuff_BorderAlph": "Border Alpha",
        "TStuff_BorderColor": "Border Color",
        "DrawToolWindow_TextNote": "Text Note",
        "AnnotMark": "Bookmarks",
        "lastpagebtnHelp": "Last page",
        "firstpagebtnHelp": "First page",
        "aboubtnHelp": "About",
        "screenbtnHelp": "Open this application in full-screen mode",
        "helpbtnHelp": "Show help",
        "searchbtnHelp": "Search from pages",
        "pagesbtnHelp": "Take a look at the thumbnail of this brochure",
        "bookmarkbtnHelp": "Open Bookmarks",
        "AnnotmarkbtnHelp": "Open Table of content",
        "printbtnHelp": "Print the brochure",
        "soundbtnHelp": "Turn on or off the sound",
        "sharebtnHelp": "Send Email to",
        "socialSharebtnHelp": "Social Share",
        "zoominbtnHelp": "Zoom in",
        "downloadbtnHelp": "Downdlaod this brochure",
        "pagemodlebtnHelp": "Switch Single and double page mode",
        "languagebtnHelp": "Switch Lauguage",
        "annotationbtnHelp": "Add Annotation",
        "addbookmarkbtnHelp": "Add Bookmark",
        "removebookmarkbtnHelp": "Remove Bookmark",
        "updatebookmarkbtnHelp": "Update Bookmark",
        "btnShoppingCart": "Shopping Cart",
        "Help_ShoppingCartbtn": "Shopping Cart",
        "Help_btnNextPage": "Next page",
        "Help_btnPrePage": "Previous page",
        "Help_btnAutoFlip": "Auto filp",
        "Help_StopAutoFlip": "Stop atuo filp",
        "btnaddbookmark": "Add",
        "btndeletebookmark": "Delete",
        "btnupdatebookmark": "Update",
        "frmyourbookmarks": "Your bookmarks",
        "frmitems": "items",
        "DownloadFullPublication": "Full Publication",
        "DownloadCurrentPage": "Current Page",
        "DownloadAttachedFiles": "Attached Files",
        "btnCopy": "Copy Button",
        "infCopyToClipboard": "Your browser does not support clipboard.",
        "restorePage": "Would you like to restore your previous session?",
        "tmpl_Backgoundsoundon": "Background Sound On",
        "tmpl_Backgoundsoundoff": "Background Sound Off",
        "tmpl_Flipsoundon": "Flip Sound On",
        "tmpl_Flipsoundoff": "Flip Sound Off",
        "Help_PageIndex": "The current page number",
        "tmpl_PrintPageRanges": "PAGE RANGES",
        "tmpl_PrintPreview": "PREVIEW",
        "btnSelection": "Select Text",
        "loginNameLabel": "Name:",
        "btnGotoPage": "Go",
        "btnSettings": "Setting",
        "soundSettingTitle": "Sound Setting",
        "closeFlipSound": "Page-flipping Sound",
        "closeBackgroundSound": "Background Sound",
        "frmShareCaption": "Share",
        "frmShareLinkLabel": "Link:",
        "frmShareBtnCopy": "Copy",
        "frmShareItemsGroupCaption": "Social Share",
        "frmPanelTitle": "Share it",
        "frmShareQRcode": "QRCode",
        "TAnnoActionPropertyStuff_GotoPage": "Go to page",
        "btnPageBack": "Backward",
        "btnPageForward": "Forward",
        "SelectTextCopy": "Copy Selected Text",
        "selectCopyButton": "Copy",
        "TStuffCart_TypeCart": "Shopping Cart",
        "TStuffCart_DetailedQuantity": "Quantity",
        "TStuffCart_DetailedPrice": "Price",
        "ShappingCart_Close": "Close",
        "ShappingCart_CheckOut": "Checkout",
        "ShappingCart_Item": "Item",
        "ShappingCart_Total": "Total",
        "ShappingCart_AddCart": "Add to cart",
        "ShappingCart_InStock": "In Stock",
        "TStuffCart_DetailedCost": "Shipping cost",
        "TStuffCart_DetailedTime": "Delivery time",
        "TStuffCart_DetailedDay": "day(s)",
        "ShappingCart_NotStock": "Not enough in stock",
        "btnCrop": "Crop",
        "btnDragButton": "Drag",
        "btnFlipBook": "Flip Book",
        "btnSlideMode": "Slide Mode",
        "btnSinglePageMode": "Single Page Mode",
        "btnVertical": "Vertical Mode",
        "btnHotizontal": "Horizontal Mode",
        "btnClose": "Close",
        "btnBookStatus": "Book View",
        "checkBoxInsert": "Insert Current Page",
        "lblLast": "This is the last page.",
        "lblFirst": "This is the first page.",
        "lblFullscreen": "Click to view in fullscreen",
        "lblName": "Name",
        "lblPassword": "Password",
        "lblLogin": "Login",
        "lblCancel": "Cancel",
        "lblNoName": "User name can not be empty.",
        "lblNoPassword": "Password can not be empty.",
        "lblNoCorrectLogin": "Please enter the correct user name and password.",
        "btnVideo": "VideoGallery",
        "btnSlideShow": "SlideShow",
        "btnPositionToMove": "Move by mouse position",
        "lblHelp1": "Drag the page corner to view",
        "lblHelp2": "Double click to zoom in, out",
        "lblCopy": "Copy",
        "lblAddToPage": "add to page",
        "lblPage": "Page",
        "lblDescription": "Title",
        "lblEdit": "Edit",
        "lblDelete": "Delete",
        "lblRemoveAll": "RemoveAll",
        "tltCursor": "cursor",
        "tltAddHighlight": "add highlight",
        "tltAddTexts": "add texts",
        "tltAddShapes": "add shapes",
        "tltAddNotes": "add notes",
        "tltAddImageFile": "add image file",
        "tltAddSignature": "add signature",
        "tltAddLine": "add line",
        "tltAddArrow": "add arrow",
        "tltAddRect": "add rect",
        "tltAddEllipse": "add ellipse",
        "lblDoubleClickToZoomIn": "Double click to zoom in.",
        "frmShareLabel": "Share",
        "frmShareInfo": "You can easily share this publication to social networks.Just cilck the appropriatebutton below.",
        "frminsertLabel": "Insert to Site",
        "frminsertInfo": "Use the code below to embed this publication to your website.",
        "btnQRCode": "Click to scan QR code",
        "btnRotateLeft": "Rotate Left",
        "btnRotateRight": "Rotate Right",
        "lblSelectMode": "Select view mode please.",
        "frmDownloadPreview": "Preview",
        "frmDownload": "Download",
        "frmHowToUse": "How To Use",
        "lblHelpPage1": "Move your finger to flip the book page.",
        "lblHelpPage2": "Zoom in by using gesture or double click on the page.",
        "lblHelpPage3": "Click on the logo to reach the official website of the company.",
        "lblHelpPage4": "Add bookmarks, use search function and auto flip the book.",
        "lblHelpPage5": "Switch horizontal and vertical view on mobile devices.",
        "TTActionQuiz_PlayAgain": "Do you wanna play it again",
        "TTActionQuiz_Ration": "Your ratio is",
        "frmTelephone": "Telephone list",
        "btnDialing": "Dialing",
        "lblSelectMessage": "Please copy the the text content in the text box",
        "btnSelectText": "Select Text",
        "btnNote": "Annotation",
        "btnPhoneNumber": "Telephone",
        "btnWeCharShare": "WeChat Share",
        "btnMagnifierIn": "Magnifying Glass",
        "btnMagnifierOut": "Magnifier Reduction",
        "frmShareSmallProgram": "smallProgram",
        "btnMagnifier": "Magnifier",
        "frmPrintPrintLimitFailed": "Sorry, you can't print the pages.",
        "infNotSupportHtml5": "HTML5 is not supported by your current web browser, please read the book with latestverson web browser. Here we recommend you to read it with Chrome.",
        "btnReport": "Report",
        "btnDoubleSinglePage": "Page switch",
        "btnDownloadPosterPrompt": "Click to download the poster",
        "infLongPressToSavePoster": "Press and hold the mobile terminal to save the poster",
        "infLongPressToIndentify": "Long press to identify QR code",
        "infScanCodeToView": "Scan code to read",
        "frmaboutcaption": "Contact",
        "frmaboutDESCRIPTION": "Description",
        "frmaboutAUTHOR": "Author",
        "frmaboutADDRESS": "Address",
        "frmaboutEMAIL": "Email",
        "frmaboutWEBSITE": "Website",
        "frmaboutMOBILE": "Mobile",
        "infDeleteNote": "Do you want to delete the note?",
        "proFullScreenWarn": "Current browser does not support full-screen,Please use Chrome for best results",
        "btnBack": "Backs",
        "frmVideoListTitle": "Video list",
        "frmVideoTitle": "Video",
        "lblConfirm": "Confirm",
        "frmBookMark": "Book Mark",
        "btnExitFullscreen": "Exit fullscreen",
        "btnMore": "More",
        "frmPrintall": "Print All Pages",
        "frmPrintcurrent": "Print Current Page",
        "frmPrintRange": "Print Range",
        "frmPrintexample": "Example: 2,3,5-10",
        "frmPrintbtn": "Print",
        "frmaboutcontactinformation": "Contact Information",
        "frmSearch": "Search",
        "frmToc": "Table of Contents",
        "btnTableOfContent": "Show Table of Contents",
        "frmLinkLabel": "Link",
        "frmQrcodeCaption": "Scan the bottom two-dimensional code to view with mobile phone.",
        "btnLanguage": "Change Language",
        "msgConfigMissing": "Configuration file is missing, unable to open the book.",
        "lblSave": "Save",
        "accessRestrictedTitle": "Access Restricted",
        "enterYourName": "Enter your name",
        "enterVisitCode": "Please enter your password",
        "enterReadingCode": "enter your reading code",
        "enterTheReason": "Enter your reason for application",
        "enterPhoneNumber": "Enter your email address",
        "enterVerificationCode": "Enter your verification code",
        "getVerificationCode": "Send",
        "sendValidCodeSuccess": "Verification code sent",
        "getVerificationCodePrompt": "Get a verification code sent to your email",
        "enterPasswordPrompt": "Password required to proceed reading",
        "leaveMsgSimilarBooks": "Explore More Books",
        "leaveMsgToAuthor": "Contact Author",
        "leaveMsgName": "Your Name",
        "leaveMsgContact": "Your Contact Information (visible only to the author)",
        "leaveMsgEnter": "Please Enter the Message",
        "leaveMsgCancel": "Cancel",
        "leaveMsgCommitTitle": "Submit",
        "leaveMsgPrompt": "We will forward your message to the book uploader.",
        "leaveMsgErrorPrompt": "Exception occurred. Please try again later",
        "readingCodeErrorPrompt": "Invalid reading code. Please try again",
        "passwordErrorPrompt": "Invalid password. Please try again",
        "invalidPhoneNumber": "Invalid number. Please try again",
        "invalidEmail": "Invalid Email. Please try again",
        "verificationCodeErrorPrompt": "Invalid verification code. Please try again",
        "codeSendingFrequent": "Frequent operation, please try again later",
        "commiteTitle": "Verify",
        "shamStopTitle": "The author's account privileges have resulted in book access suspension.",
        "shamStopSubTitle": "Contact <a target='_blank' href='{%host}\/homepage\/{%uLink}\/' style='text-decoration: underline' >the author<\/a> for further information.",
        "shamStopLeavePrompt": "Please complete the question.",
        "shamStopLeaveMsgSuccessPrompt": "Send successfully",
        "codeSending": "Sending",
        "viewFullScreen": "Fullscreen",
        "cardsSign": "click to view card",
        "frmaboutViews": "Views",
        "btnMessage": "Message",
        "btnInstructions": "instructions",
        "btnArticlePages": "Pages",
        "btnArticleList": "Articles",
        "btnCalendar": "Calendar",
        "btnBook": "Book",
        "btnEnlarge": "Enlarge",
        "btnReduce": "Reduce",
        "btnPrevArticle": "Prev Article",
        "btnNextArticle": "Next Article",
        "copySuccessfully": "Copy Successfully",
        "cardsWechat": "Wechat",
        "cardsTelephone": "phone",
        "close": "close",
        "jumpPageByEnterNumber": "Enter the page number to jump quickly to the specified page",
        "jump": "Jump",
        "relatedContent": "related information",
        "brandTitleUndefined": "No brand name is set yet",
        "more": "More",
        "fold": "Put away",
        "otherWorks": "other works",
        "flipSound": "page turning sound",
        "backgroundSound": "Background music",
        "report": "report",
        "copySuccessTip": "copy successfully",
        "saveSuccessTip": "Saved successfully",
        "scanCodeAddMy": "After saving, WeChat scan the code and add my friend",
        "saveImg": "save Picture",
        "searchTheBook": "Search this book content",
        "historicalRecord": "history record",
        "searchResultCount": "A total of {%count} results",
        "noRelevantResults": "No relevant results",
        "changeTheKeyWords": "Try another keyword ~",
        "leastWordsTip": "Please enter at least 2 words",
        "jumpPageInputTip": "Enter the page number to jump quickly to the specified page",
        "jumpto": "Jump to",
        "foldThumbnailTip": "Click here to put away the thumbnail ~",
        "btnLoadingText": "In loading, it's fine soon",
        "btnTitleText": "Read now",
        "relatedInfoText": "Related Information",
        "brandContactFrTitle": "Contact the author",
        "shareFromPage": "Share starting from page N",
        "TStuffShowInformatin_Width": "Background width",
        "TStuffShowInformatin_Height": "Background height",
        "TPageList_BlankPage": "Blank page",
        "morePanelBookLink": "Link",
        "morePanelPoster": "Poster",
        "morePanelOtherShare": "Other",
        "doublePageTitle": "Enable Landscape Mode to Read in Two-page View",
        "doublePageAndroidTitle": "Enable Landscape Mode to Read in Two-page View?",
        "doublePageDescription": "How to set landscape ?",
        "doublePageGotIt": "Got it",
        "doublePageAndroidSettingStep1": "1.Allow auto-rotation in phone settings",
        "doublePageAndroidSettingStep2": "2.Allow landscape in browser settings",
        "doublePageAndroidSettingStep3": "3.Turn your phone sideways to read",
        "doublePageIPhoneSettingStep1": "1.Disable portrait orientation lock",
        "doublePageIPhoneSettingStep2": "2.Rotate your phone",
        "noFilesAvailablePrompt": "No Files Available!",
        "reportBtn": "Report",
        "reportConfirm": "Submit",
        "reportCancel": "Cancel",
        "reportAlertBoxCloseBtn": "Close",
        "reportTitle": "Please select the reason for reporting",
        "reportSuccessPrompt": "Report successful",
        "reportError": "Report failed",
        "reportNetworkError": "Report failed, request link error",
        "reportDescErrorPrompt": "Detailed description cannot be empty or contain only whitespace characters",
        "reportContactErrorPrompt": "Contact information cannot be empty or contain only whitespace characters",
        "reportTextareaPlaceholder": "Please provide detailed reasons for reporting (required)",
        "reportNumberPlaceholder": "Please provide a valid phone number for better understanding of the situation;otherwise, it will not be processed",
        "reportReasonSource": "Please select the reason for reporting; Piracy Copyright Infringement; Medical HealthPlastic Surgery False Advertising; Cult Violation of National Policies; Pornography GamblingDrugs Pyramid Scheme; Other reasons",
        "businessNone": "None",
        "lblSimulatePageFlip": "Simulate page-flipping on a computer",
        "lblSimulatePageSlide": "Tailor to the sliding habits on a tablet",
        "suspendedForExpiredMembership": "Due to the expiration of the account member service, the access to the book has been suspended by the system",
        "suspendedForMaxReadLimit": "Due to the account reading times being exhausted, the book has been suspended by the system",
        "suspendedForReadLimit": "Due to the limit on the number of readings, the access to the book has been suspended by the system",
        "suspendedForContact": "To resume it, you can contact the author directly.",
        "expiredRedirectButton": "Explore More Books",
        "btnPhoneticReading": "Listen",
        "btnPhoneticTips": "You can listen to and read this book at the same time.",
        "articleSummary": "Article Summary",
        "articleFirst": "This is the first article.",
        "articleLast": "This is the last article.",
        "articleBack": "Back",
        "multimediaSoundOn": "Music on",
        "multimediaSoundOff": "Music off",
        "downloadRestrictionTips": "Download access for this book is restricted by the publisher.",
        "encrpytionSearchTips": "The book has restricted access.<br\/>Please obtain permission before searching.",
        "chatbotBtnTips": "Hi~ Ask me about the book here!",
        "searchMatchType": "Split term search",
        "settingMultimediaSoundTitle": "Music",
        "settingMultimediaSoundPlayTips": "There are pages without music currently. Once music is enabled, it will only play on pages with music.",
        "settingMultimediaSoundPauseTips": "After music is disabled, pages with music will no longer play.",
        "downloadingTips": "Downloading...",
        "downloadSuccessfully": "Download successful!",
        "comment_title": "Reader Message",
        "comment_userNameTip": "Name",
        "comment_numTip": "Contact Number (visible to author only)",
        "comment_leaveMess": "Please enter your message",
        "comment_submitText": "Submit",
        "comment_emptyPrompt": "Be the first to post a message!",
        "comment_closeLeaveMessage1": "Sorry!",
        "comment_closeLeaveMessage2": "The author has disabled the display of messages",
        "comment_closeLeaveMessage3": "You cannot view other readers' messages",
        "comment_successMess": "Message submitted successfully",
        "comment_successShowText": "Your message will be displayed after admin approval",
        "comment_successHideText": "The admin will receive your message",
        "comment_successGotIt": "Got it",
        "comment_loadingText": "Loading, please wait...",
        "comment_noMoreText": "No more messages...",
        "comment_emptyErrorMsg": "Message content cannot be empty",
        "comment_specialErrorMsg": "Message content cannot contain special characters",
        "comment_frequentlyErrorMsg": "Sorry, you're posting too frequently. Please wait a moment before submitting again.",
        "comment_errorMsg": "Sorry, due to system busy, submission failed. Please try again later.",
        "comment_username": "Anonymous",
        "comment_authorName": "Author",
        "comment_replyMsg": "Reply",
        "accessLimitedText": "The book is protected. Please purchase it, or verify password \/ your email to continue reading.",
        "printRestrictionTips": "*Print access for this book is restricted by the publisher.",
        "lblVerifyPwdBtn": "Verify"
    }],
    "ols": [],
    "slideshow": [],
    "pageEditor": [],
    "flipByAudio": null,
    "downloadconfig": {
        "pdf": null,
        "isDownloadProject": false,
        "isDownloadAttach": false,
        "attachments": [],
        "hideDownloadSinglePage": false
    },
    "assistantConfig": null,
    "phoneNumber": [],
    "bookPlugin": null,
    "slider": [],
    "downloadConfig": null,
    "fliphtml5_pages": [{
        "n": ["2011faf824218be23dc2f0afa6632b9b.webp"],
        "t": ".\/files\/thumb\/4e00158834fbff911266d4ca987be308.webp"
    }, {
        "n": ["89086524f866500038fbf0600017a3f9.webp"],
        "t": ".\/files\/thumb\/2d6f43c49368b53a946e6f9064ffe862.webp"
    }, {
        "n": ["204db78f4603a07d054489ac31c978a5.webp"],
        "t": ".\/files\/thumb\/f9da14890c78c9dba0118e4ca169abd0.webp"
    }, {
        "n": ["750984fe9ab473142ec02bd88ab0beeb.webp"],
        "t": ".\/files\/thumb\/927ed27db167247414075e711aa116c2.webp"
    }, {
        "n": ["1945afd1f69f31e69dd0b32bb52ef2c2.webp"],
        "t": ".\/files\/thumb\/a31564e4290fca6dbdce144d0832f9d6.webp"
    }, {
        "n": ["23def87e597c94669184cc7d38f008aa.webp"],
        "t": ".\/files\/thumb\/321d5ded69893dd6ccdc7a59cee56661.webp"
    }, {
        "n": ["25940555114dc0e5265625aec3f42f15.webp"],
        "t": ".\/files\/thumb\/84729d6d8c2b310f769a614ff7640a50.webp"
    }, {
        "n": ["0f96c55c7678c989108b694ea5796913.webp"],
        "t": ".\/files\/thumb\/c4621003e2e8ea11f68b65638c059ac1.webp"
    }, {
        "n": ["4292bfe25d82d9f4f32593cdeecab407.webp"],
        "t": ".\/files\/thumb\/a84b3fb7d65843e5134b0853da9701e8.webp"
    }, {
        "n": ["4097cec47d66db5cc09409ba2a26d163.webp"],
        "t": ".\/files\/thumb\/50074c10a740ffc6ec03e3c8cf15d3d6.webp"
    }, {
        "n": ["25fdfac395f110f2932618f0326a9911.webp"],
        "t": ".\/files\/thumb\/9b6c9074fa23419ae6aa4fb10329e881.webp"
    }, {
        "n": ["670d6b0865561f0ca3dc9951cf243a97.webp"],
        "t": ".\/files\/thumb\/07aecbaedd0d1a697673d46ad0efd705.webp"
    }, {
        "n": ["5bf2012760d0956e03e9e9bdc67240d4.webp"],
        "t": ".\/files\/thumb\/41ec0bef7cfc12c5c4a8e3f5417c7077.webp"
    }, {
        "n": ["5e3fc83c2622c53475f334ef2650f1e6.webp"],
        "t": ".\/files\/thumb\/db496dc1fff1a177597e37ca18d3ee4c.webp"
    }, {
        "n": ["2646f6c34c2c91603d1fa3514d5bfd9a.webp"],
        "t": ".\/files\/thumb\/a04100acf7590d3f6c0d9334cca546a0.webp"
    }, {
        "n": ["66c3bc143c4d84a58d019d986c0cea75.webp"],
        "t": ".\/files\/thumb\/246d710d8dcbbdbd4c1f4ac74f5186e0.webp"
    }, {
        "n": ["43fd7b5d576585c56a83bf06c2adb9e0.webp"],
        "t": ".\/files\/thumb\/4acd09bd910ad41ad0f0d94f43c0fb03.webp"
    }, {
        "n": ["04b3e4f06bcec283aec5a8bf5d81378a.webp"],
        "t": ".\/files\/thumb\/e0d6d8f3b47109af9a7595d000f23e17.webp"
    }, {
        "n": ["5e4ceb276fda23c436bdc4a4a942aaaa.webp"],
        "t": ".\/files\/thumb\/b8b256beeda21fbb68bc450cafd5fc58.webp"
    }, {
        "n": ["d518e3ee4816ee1325b5ecdef90e2913.webp"],
        "t": ".\/files\/thumb\/07f68da15b2016d472dbdc026e88c04d.webp"
    }, {
        "n": ["39a497634b5551cfa9b04c5c511867f7.webp"],
        "t": ".\/files\/thumb\/969b981ae5858e03a3d01132279efda4.webp"
    }, {
        "n": ["0d00772b79e3bf2f2921154b0495e94f.webp"],
        "t": ".\/files\/thumb\/68bda6fb9deac2991566868a5369f0f9.webp"
    }, {
        "n": ["5f2b3e66e92cb9e6e587e410b957863b.webp"],
        "t": ".\/files\/thumb\/4640b80fef4186322ba05b90a5f8234b.webp"
    }, {
        "n": ["339f4992e70c5fe1711730fcacec260a.webp"],
        "t": ".\/files\/thumb\/ab747055c6463934710786e86dc6debe.webp"
    }],
    "fileExist": {
        "pageEditor": 0,
        "updateEditorTime": 1754331054,
        "plugin": 0
    },
    "loadingConfig": {
        "loadingBackground": "#323232",
        "loadingCaptionColor": "#DDDDDD",
        "loadingCaption": "",
        "loadingCaptionFontSize": "20",
        "loadingPicture": "",
        "loadingPictureHeight": "150",
        "showLoadingGif": "Yes",
        "loadingVideo": "",
        "loadingDisplayTime": "0",
        "isEncryptionBook": false,
        "isFakeStopBook": 0
    }
};
