var htmlConfig = {
    "bookConfig": "v01000110403cLRl2Nek4AUvwGSsyEWl4NWnuNUh4Ico6GWs0EUjuKXo2Fcs3BXr1HYp0HUg6LQh2Ebo9HfkwCSl9LXlzMcg2KTo4HfkyPUgvNdr6LXi4Cdl4Oao4GWr9CYt6MXs6PWv6JSvvBQixLVr6KauuKbk7JQh3LSi8LSh6Lft0NWkyBelzAYj9Gfq2PWg5ERi8KWn4IQk4OUv0Cfp9PRn4JXh0JdkyISqvBcs3Fch4BemxETp5AftxGVt1LTtxHUkzAWgvAQi0MXnxPaj8BUl8KUl9PSmxGar6PalwIYg4PTv5DRl1LQjyOTruKct8LRh7Obp8ISp0HQr3FZlzARg8IQo5MaqwHbr9EZhyPaouEWozHem6Nap1DTi5OXv3DYm3BcjyPUq9EbhzOfjuAYhvKZu3KXsxDQtuDbg8HdhyLRj6PVpyFcp7PVtzFXgwAcg4KRtwFatuEfnwPdm5BTi6LRp3AVm6GRmzMbk0BRhwBRi7CXmwPYh1Obo6OQs1JYquLdnvPWszHVpxNYo6PXq6ERkyKQn6EXh1IRh3AVvuDYnwOYnzMWhwGSuwFeuxDSv7Feh5AQp1GQnwIUnwLUn3Aeh5PZsuCdl2Pfp0Beq4ITo8BTg1Pbu4PUlyCVgxLat6AQi5EXrwHWkuFVh4NSh8AXnvNTn2AQrwDZsyEcu7NQj1LXr7GThxIRvvBfuvKfuzNQs1PcmxCZuwLWu2OdpuBdu6Pep1GSg8HWsxOZsxEeruPdp6Ebg6OYo3Beq0FVqxOYixLSj9HciuBSj5JRi7CStvBYn3IbiwPZuuMRv5JUi7FSixHahwNbgxFdt5GUiyNao7OZvvPbnuDTg5IcozCUv1Ffs1HUkvDdk8Pev5JYjuLUuuHei5Efu9FXhzEUowMaq2IVl4NfgyNbo9LZm2OYjwLdq2IXnxEVovAZrzCfp5ITl9AWpvLflvHehuKRnzNdp3GYv1DUl8NelyDdg3IXk4OWk8PSt3NcmuCfn9Lcv7JTrzObv6BYq8PbhxBcm6GWswBZrwHWq5MTj9DSgwFcqzOSk1ARt7JUo2PXpzCdv9KbhwOTpvPauwEbt3PcvuIXp6KRh6Efm2Eel2MQlvOUq2LWp6BfhvDav9Pet1Mch7OaguHVn1Pck9Hft3KVv1AQh7FdhuNfq1GYguBTp8EXk8IVs9Abq6Beu2Edr8Mai0BZnwIXr8Nds4GWr0LRl4ATp8Cdg8IXg4EYg4LVsyIYu8CUt5Mbn1ISr1NdivBYgyAZh2FcizHas7AVh8AauxCejuBet2GYr0Ddt0GTj2LXp1MQt7CSqvJdgyPYk5Ofn6AalwLbk2EXpyLWl7FfnwNeswGUs6CUg8AQpwGYswJTh4FZt0CVk7JTg3AboxMfoxCVt7Jdl0LSj2KbjyEfp9DZj9Ccm6DbpvNas1AUqvPak1DUr5NcovIVp1MRrwCXq4EVjwKfm7ESo0Ieh3MWu3Jeu7FTi2FZhxNQj3LYq2PVv2LZnvHXq9GelzGTh8EdlvGeoxFVm1AbowGfhwEct6AXkvNUh9Jcr3Jdj3Meo9NXlxIWr0MWs3EbgyLerxKXl1IUmwKUp1PWk7IXquNcmvCcp7FUj7PTv2BRg2Mfq4OQn0NfvzJWhyHan8NUvzHRu4AdpxMagwPVh5AUu2EeuuHQu7AYpxFbt9CSv4OTi5GRjuAci9LQowLWj6GUs7FVnyHdh4GTnxEdryLVpxDRl3Mcr9BXm6Lbk7DchyFbh6ObkuLdr0Baq7IfkvDXl5LQovBRm4PXt1GYu8CbkwAclxIbvwOQuuFas3BRmvJUl3Hav7DTn0IbkyHWnvHfpyIbizMXs7CXo3HfrzEQm9BYuuIduyOSl3Ocv7BUj2Lfv0Gag0Nar5IfqxBaluFRs6JVk1NcgvMft2NUl3CRt9Ccs9PagvFcuwPRuwJZp4JcrvOdt9Gas4GSuzCSpuKcv1BVg1AQu4PZmyHVh3IVq1BXu7Dbi4NVkyJSm4GXgzOQjuCfvwPag2BXs8Ofq6Gbv5AYj6EVo9Mdh7GZv9PZr2GTo6HZsvNUj0LTm9JWrvGbszKbo9MXk3MarxJbjuPXn9Pfk5CZp1CSj8AesvEfl5MVuxOYhzPeuvHUu1JXu8NXt9KZt7CQu0GVizNWs7NWvyGZo2Jal2NYm1CctxJWgwITr5Hct0LRozNam6BWovARi0EXp2DUh9MVt2Dbn5EUo8GRqzNXl0BfpxPRr4Fdv8Iau6GZuzNfl7CZp8Afo8MUsuBQt9Aej1EZtyCUj8AXq1Ncj2AYo7BQm9IWk0HXi4Ffm6GQm9MTq8MYouJWu8EYp6DboyFehuAaswNXu0MRn7AcsvIQt2Efq1Ibu7HYl3KZgwLbv2Oaq0Hcm7CTt8NWo7KbvuGWqxFVh3MQk9NSm2JZp3Pbo6EQryIVvzLSrzPTv7MVjyLbg7Nah7MXg8OQn7Abq0DXh9JWs9MQuwERg0KRj1JXl2BZq8NSvuNbovBei9AQm7CZpxMYq6ISjxHfu1Fdl3CYi8Mdl0IXh5NUq2MSq2HWq1KRhzIaszHZhyHdk1DTk2KZjzGat5AWr1PQh6DTnuFSt1OflyMRiyEYj1LWi7ITmuBZr7OaluBZj7Fcp3PZs8IVswGQv1GTp7Lbp0MZj8Nfl9Dct5EarvOWg9LckwORl1FVm7NdsvIXn8Hcv1DYv2BTn3KTgyPSv8GakwMWvwGYk9MfrvFfmvKbr0JRi1LQsxGTo9LVmzHTo2ITgyDZhxPbovJVh5Kfp6ISr7MavwIVj8BTs5FSh3Nak3JXl5NUq0Gel1BVizJUr2Odj8FSo5IRh3IWm4Oeo5CXgzGdn2ETq7JUu1Ddh8ITu0CQvyEdp1HVj1EXr8IZr4CQsvDdixEfu4LfqvDSqzJYi2GWvzHZmyBTjyPRkyLXs5AYovFdqzOSlyESj8CfgvIchwFQvuNSt5Lcm7DdmvIXg9Obk2NQj0Bdo5DXruBem5HVt8Obl6EWt2BWt1GYs9HSquBaquBcj4Bdh1BYhvNchwDap7FWpvMcv1MUhyDcqxLcn9KWo7EUo0Lcr2PTnzBZuwIeo7Kbr7OYtwJak4Cal2CTu5AWn5OUg6BagzMYh4KUqxOZr1CTq3NTj2CZpwOctyFWt0Cfl8EZk6Mel3Ncn9MdruLTg0Par6FYu0LYgvAQj2KXnzFTtwCYk3ARjvIVm2DTqzEWsuIcqwBTr5LepxBSjyMTm6Kah0OVr9Pbr7MYluBTk9EaruJSn6NRhvLWm3NRj5PTtyDfq9Obq1Bap4BXuyFak3IWm3FeuzISm2GWo0EUuwISvzOVr4MVkuAdhyBSuuHVgvBTmvFTs4NVv8Icj5PUo6FQnzJQo5JZp6Cfm8JVp4Bau2Iap1Bap4Cci7Fam8Iao2LRn4Aej8KUq3JXgyCcrzNYp0KVlzNdr0OZr7PRpvCbjvCRl8LdryKSszLSiuPUrzLRt7LUhxKap1DfmxGYsuCcozBWp5OQnzJWq6LfpyCVnxEWv1DZg3MYn0Lfn1AWk1Gcs3BZswAQqwITl7IfjxKejwLbt9EYtwIUuvMUu2Hdj4LdgxNSqzEbo2OWr0EflyNVi1EVp5Ebl3GRu5Edp4FWl6HamwOTlzKUs8HSv3EWjxLet1LUr2Gcv7Fan5BRkwNai6HSo4KaqyCUu0Nfs9FSv0AZr3PUp3FSuuHVo7NUo8PdqyFYrzEUr4FZt9KZj8ISmxARkvCYjvOcnwKWg0Eci9Der2OfszCeuzGdrxPUi9FXpuEUjyKXs9PXqvPYg9AYivGZs2MUi6GelwKfv4PUgyFal7Get3OVt8AfpwOVg5JXr6FWi7Abl4BXl2Meg6PeqvEXpwJXn9HVo3BRtwBZu1GXh4Obv5KUr6KRu7KalyHWpwNQo2Dbg9Hdj4NYnwAUq4GVv9Lfs8PQk7Fev6OTp1EXh0LVv5BZj8JRnzJar4GfvxAUkxEQu0Hct5JcvwEal3JTswFUt2LWt0PTl7LSt4LZjyETl5FSrxGTuzFYs6NVs5OYgwNbtyMag9Edv1BbgzMetuDej0GTg3GTt9OemyNXn0OWi1EQuxOZn6Aem0AXryBQu8HbjyGeh8MSkuBQvxEZm4Del2ASjuLSnvFbh8LdouHZs7Dfi5OTj6LTqwHSp7HVv0ASk9OQn7Dbi0Mbi8HVhvEcn9Bbs3DRi8Edv5ARt7HevwLRluJTv1AQk1FRpwOXv2PQpwDco2BaouCag6CUl6GUnxCRuxFYhwBUoyBXp2Bci3EQt7JZu5JRpwOXq9Cas9ITsxJXiuIZu3Aep4Ddr4Hfp7MVmwKcqxMbv7FSr2DRswMcn6DXo4LTv2Bfl2Dbm8DQs6Keh4FeiyCQgxIYkyGSj4MXg3FarxIalzHRg1Dfj0NQozJfs1JQuxJWpyLWp7DXl6DWg0GSg6HWp4Ifi4NYpxKdqxGUn6AWlxKUo1EYsxKbl6BUjwPRt0JRszJfv4OchyFUg7Efp3OauvFZj9DYkzHcg8FQh7FagxPbk3OVlzCav3BUkxKWjxJaq2Cdn2NWk0Ecj9FXkzCbpzIVs4Dev5PRuzDQn7JTn2CVn4NTs3Kei3GanvOXj9Keu9IUhwGbh8NQv4FXtxMRmyPStxHWhwJQiwHZp1MblwCbu6PQm1BXj0LRq1CfovMTv0LTgyFStvPUm6Jdk0JdhwNcq0DSi6Idn4Gaj8CTv0JVlxDSq0LSt1Kds9PYl2FYv3DTiuLRv4EYh8FZuuEVvzAbovIbkuBQo1GXmzPQmuEVo1Net3DVi1JclxLSl8LYs0JRkwMbs6NahyMQnwBRt8MYlvEes7BUp2Odk6CYtyNYryFak1BTgwHRp1GSt2CVh8CRk4EWvzEehwBeqvIbu0HTj9IUvvAaq0IQm6JUkyMdmwHWo9LZpyCWmwCRh7Ifg7IYh5OYoxGTmuLem9LWlxDSvzBZkvMUi1HQq2LXiyLWmzGYiuMTo3OQk9Kfn1Ndu0FXsvHQs9EakzFeu6Dcn4Dch2Ian4Gcl8KTrwDXrwCQq8LQoyAZowLQm8Jal9Ocl0Jei4ISiwBUp7IZj9Lag4DSjyNRk6LeqxAWn2Mdn7Iav7Oer6HYl0AWu9KRovEWpzLSpzJWk5OVo4KSk9DYn4Ddn8HWjyGer7NTn2LduzJQvvIRv0CTq0JUm3JSi0GVhyHXl8Icn5CdjvHUo3JYi9NTgxOdr3OerzCanzNQp5FasxPQv9IQm4NUj8NWs9ETl3OZp3HRq2JZm1Jbt3CYo7Kci5MauzAakuEfv2Ieu8HWk3Cet2GXgwMTlwHTh0Ldu7Dem4Jbv8KZr7HXr9FYuvJUizIbr5Heo6Acq6LVpuHev9OTi9FRu9IWlwKZm5KfkxAdo3FbpwDYqwGQl8PTv2DQq4KeqxDeh3AZj9LRo2JehwNYq3GTp2Iak9KQg2Ffi7GVrzKYl0CSl4Dfl8MUizLaqxAUv8Adq1HTi9IYq3Kfg2GQt0CVv5MQluMdk7Gbt8EVo9Hdm9LYq0CTm2PTj9ETivLcp4MaovEWj1Fdg8Cbq3LUkvMUh0EanxAUr5GQi6OSj0Hbg2GTl0IYj5LXi9Aes8NbmxMau8Nak2FZjvLSq9LYs6PUi5MUnyCVj1HanyMVnvPRiuISs2KenxMcuuFZjvLSp3Gbl6MYovARj5EZk8JVs1DYs2LciyMbqxASn3ISp4KZj5MXl5ASt3CSnyAesxHZmxDfrxKVjvFbmuPdn8EeuuLev2DWtyGcg7Bei0EdivDSp6Jbq3LYvuNZq5LRpwMUs8IUmwJTnwKTnxFYm2PWi4PXs7Jeh0Jdg3Eaq0HQn5CXs1GbvwEYhxNfu6CQs8AUr6KXkyIaguNTv3OVi8FRixHbgwHZm6BYo5Ocs2Ldl6NWj2IZnuISi5Kfp5PUm3GRg3ESk4CTjyEat4EYq8EeuvDcvuJUn7EZs9PRpzIdhvCYl2DUgxPbiyDWg5IUovAXj2ETk4PZm2IVp4IdrxIdo1Ian7CWtyIbn2CTu3MWquIQgwBVp3Nct2Pcq3IbpxLRo3NVv5IXuuJXlzCRk1Oag1Fej7Lbn1LepvITiyIdm6LWrxEVp6Cfi4AUuyNet1HfpxPch2Keh7OTqzDWlvGYvwNcp8McpxCdm0GSj7OUn6DSlxIRn6Pej7LYt9Pfl1Afj6KXl5HXj0AYj0NeqzHbkvLdl0DalxDcq4HRh8Dfh7LRguFQs6Ldp0Afh5Bcu4KWkzNUtwJYq5FRryObqvEanvIetwARs8AetuDWlvHSh4Fbl4FSv1OWkxMRj8ARl3JSo3AXozMcg2Eah4LYo3IcmuPUj2Ofh9AVsuPZh2KTs0GSt5Jcm5HQquHQh2Bfo5KfqyDfouPXvyGQiyAfl5Edq8Oep8MUs4CSh1Pcu3LSl4NTh2CZp6Leu7Idl0PSl3Jcu8EXn8PSu5ERi9PQpvPYjuESmzDRn2MYjyNQh6DWl2PXk6BYj2Bch8Ces4ORv2DZs0MYmuJUl8Nal2Ndg1Pej0MRg8OUj9FfuvDRm1JWvxFTh6PUr7HdnzOdv6CTl1DZnuMfq5Ees9GYi2BQn8GSkwLdr3ATgzDSp7OXo7MVn8LQmyOboyGct3NSouAdqxOXk4AVg5DWn8PVv2Lbm7Aco0HXu5IfkuBUq6LWh3FYpzAdkuHep3Hfg9OfrvARp4CYt3Fag1NYr4LTl4GSg4Heo5KWr5DXv0MXr6HbmvCVpxBUkvIWn7NYqxEYm6GYmuHVt4BUm1Geu5ObnwFXvwLTtzOdpwCbn6Ffs9Pcn1MQsyCSk5EQk2Gdq7BVvuOeg6CbtuDWo9IZqwKZt9HcgxOfu5OTq7IfrxCcsuKbv5KQjxAVg0BXk6CTjyHYlyOci6FavyIRixCel1Pcm2JYn3Hci2BbjvIfuxOWi6DXtyCZpxNZsyCYh9MRo2BSo7CRh8BXu3AXvuGZjvKch6OYpwHWq9HasyJSruPet3IbszMfrxIcu9EciuKeuwIYhvGbg2Cel4MSj3Adt9Icq6Nei6FYryFYtwBeixGYk0GVo8KVv9BSsxNSoyDTj1CQh2GRl1DTh7PWiyDfpuJVq0Mei2OYh3DWh7Mcu4DZowAbg3Jck9LQq1Dcv7IZjyIUs2Pft0ORtyAQkvBRszPdq0GSl7Peu6AXk0EZr0IQlxJWl9Fck8IWk6Nav1IXj5CapzEamyHXt2JQhwATr5DfvzLej5MRkwOdj8BdizMevzOZg2Eck4Ndg6Efs7ESq6GfnyDZl8PWh4Hel7GaoyGah8CRg7AUkuEcm9OSruPYhvHXouDZs1IWlyMWtyBRj2IXrxCRs4DUtzGQruFfj2CXp0FVj4EbryIWt0MfpuGUhvFSoxKej5IZj1JThuBdp8FTi1Deh0Lcn3AQn8HXh4NVo4EVozCQn7JXqxJUp7HYm2Dbr5DYq5Mft5GVq8Kar9BYixHZsyIZi9IQp1BXh8FTj9FVr6AdpvKbpxIXg5Mes6LUhwNfh3FWlxPbt9Oft9Bdk6Let8Afg0CUgzHZk7HWuwIWrxCVm1BWi0PajyJervDTv1PYq0PanyJThuGSn5Dcg8HTo4LYk5EWqyDZu2CRp1BXp1KSv1Obt2Fcn7EeuzHeqwGSl6FTk7GQvvFes8FchuITo8Kbp9NVvxPVt8Pfh2CRh5GVu0Kfm7EQjzHTmyOSgxHVn7ERpwPdh2CVl1IVi4Kap3IXn3Efu4GYp9KQv1ISv7Neo4JUt6Bat4JYv6KRn1HaiyDWs7LTr9Gai2GcqxBZo8OYj2Afp3JckxEcmzFShxJVrvPbqxLcryBfr3BUu6Kfr7FUp4HYt8NdiwCdq7PXqvDak5KUrxHWqvBbl3OSj2PSlyOTgyMdj7FQp0AdlvFVj3Nfo8JUsxCfsvDat1LfqwCQqyKWkxDTkzIbu1FRivMZi1BRhyBVi4Hak1LSnwNVu4HQu0Efk5BXixOVr9ETr5LUh5NUr0BUq9IVp1Ado5Aer4Iag9GWg4Fbn8JZg4MTq6FbmvLQqxDWkzAdqxIahuASs2EdquBVhwDSluCdg1NVm4IdoyMUlzBUnuPUr0PUj9ASjxESsvHbv1IVo5Hbs8Bfl4IflwHduwKar9BRt9NSo4CSj5Gbo9Ndi6KYi7BZuwKap8ORu5BZi5KasxNWg0OYv0CeuzFZg8LXr2AZl7KahxBcu6ETl7ERi6KUkwPfo1DYq4Dar3AcqyOauwLQu0FUj6BcjuIZl3Cdg4MWjwJWu1FcrwGZg8Kam8AXsvEXuzDXvyHdr7JWhyAbv7CTi6GegyLSgvEZmzMcpvOQpxDbozOYp7FUr5JQl7BZixHQm6GYuyHRuwAam8JQh9NTr9DQj1IRj8Bci2GTkwHfn6Lam2DSk9GbuzHdnuIbi9HSg6Dfk9FVo0Ndv5CRs0LcgyCep6CdluGXu4LQvuGRm7OUluEXg4Dav0NZp1JXswCbk3PTgwBaoyJYkuOar4FUj8HepuLbuxGeo8JTqwFUj5Oek8MUg7EWlwKcsyIZhzLbm2JSquAcswHdq4MThyKTtxGds6CVmzAcowHYhwDZv2NSq6Lfl2KSq6CZovOZv1LXsyMXg7KcuxAbrvDdhxAXl3LUj7MQn5GSuuFco8Odu1Nav0Jer9Eel8Cfm0Hbr4Par7Ebu2HZq3DVi3MVswLbnyDcj6JVj9GWhxNSmvDTj0Ler4HQm1KXi0AYk1IZs3ISjzNYivFZn2LTr7GYh4EbpzFTuvPWm8CXu1Kft0JRk9PQuvEes5PThzDRu7LVu9HRg2EWsuCWo7GTj7FZsvESr4Dcm2ASm7PXqzGXvwOVq8JTi4GZr1IZq5GdgwGTruLTm0ARg0BVs5Ibq4BVk1LSg8LZs3Dbh0JXk8Oao0Pch7EXrvMZrwOQpvCcn4FTr1Feg2MRl7MVjwLVpyAYm3PQouDdt7JarvAfl5ASt5DYt9Gcn1HQrwPVmuJci9CdnxKSiyBVoxKQowHVnzBejzEQj2DTl1Cbq7GRq7FYn8LUs4MRj5NbtvAenwBaj7CQsuLZmyBQmyDXkuCej5MRuvFShvDdpxLUl3Aeo2OZl5GZsvHYg5ATv6Nah0LTlyOcvzHen9FStxFXhyDcr1OdqxLTn3AUq6BcuzLasxPTmxDcu4OXq8Dbl8Dei4MWo5BQoxAQq0HTr9Jes3Oeu5Pcp5DZqvLeq7Ffm0CblyKbv4DXq3LdjyJbg4IUj7DVgwDerzBdr6BXr8HagzKXhvJYt4NWqzITtyLfj5PQsyPVj3JajvOQu6Nct7BaovEUg7PRn1GStzFYp5HVh7AWhuNSnxJUs2CVk6NYu2Hbg3Ifg9JTi8GfmuDflzHXg7PXm0JVl4IXqwEck7Cbl4BZowKVovHSt7OVj1IRq1OZr3Ddm1MSuxNbtxHRrzGcv9MWi2PWr6JYhvAfu8IUtzGbo2OYsuGUr3GZmyLQt1AXk7KcqxIan8DQk3JZo7HYv4IQnvOUlxEakyHUk4AQk0AUn6DblvHQpvCan1PfkzOdt5OarvHYi5IYp9HRq6FRk4KTv3NSozMRqzLcj5OQn7MUj1Ifi6ARs3DUq9HasuIbq4OUr2BSq3Jbo7CQr7CUp7Nbt5GRqvMRh5EcowGSp6Ean6OagzFan6LTuyPan0CUiwEUk0ETpwMcuvPSgxLbl9NUjuJRhxFbv6AVu2CYvxLcr6McqwJYquEQjwBWs6ISl9EfrxPSo9Mfh1MSp3IcuyLfu5BdkyMegyCervOVl5BdovMZi3PVj9BWh9MYjxLVi9CRk8ARm3BQtzCVk8FZguAck6CYmzOXhxHVpyCVs8Meg9KRuzNRlwKSi5EctyMUo7EWh8CXv6AfiyMfn6Hbv1PSpuJfo2LZj3CfuzGTk0Jdi5Dbo0AZn2GRlvLWq6Mdi3Gfu8OYoyMTg9FcnxARlvLfq7Gan9DXsxETs6BflwMRi1LQtvIXl8IWg2CVu6Lci7Lfp1KfjwHSi9McjvIUk2Pes7CQq5PZiuFRp2KXp9CWl6AWn7LXruJXlwLfl0DTuvDUlzOWg2KVlzBWpwDaowBQv4PdmxERp8KTh2AWr1Oag5Ndu8Jbi7PSi5EanvOet0Gdj6IVt0Caj2AbguIfuwJQg0EQk3Kds7FYg8Ldq5FQj0NTjzPdp9CTr5HamuHdt2Kbl3OaouDfq6FclwGVs7OUgzMZr3DUuuISu3KVpvMZq1BTl9Adp8Gdo1Lfh3DZo3HWr1FYn2ATi0Mck8AQq8AehvCWv7MTr4IZh6Dfn1OSi3DcqwOYq6Laj8Mem7JVj9ISguAck1Lfv5GRq4MZlvMaj1AVv2GVtzGfv0LZn7CXnvAcqvMcjxIRiuKaiwOclvJWj2Dcv3Jat0OYl2DRl3DbvuPakxBfs4Lao6Gai1Mdl3HSryOcu9LVv0FTpxMUuxLbj0JRp6Cai0NVpzIci5Hcs9IeizPRgwBcnvLfsuPck5OUg0CSn5GTv6Efr1Ldn2LSn7JWg1Afk2HQvwHQt2BdnuPeoxLck9HSn4Fdl9Nfn3IehuJUq3NWl3MYg0Aal3LVp7CbgzAbn2BZg1AZv5Hdo5Oen2BQqxMduzHQnwPZm1OQtvEdg8KfhxLcr5PUs1KTm9DWhwHYo2CVv6HSovKfrxKdv1Ibt1GZh2Bfg1CUh5Jdv0NZh0CQrxBUg8EXv3IQs7GUqwPdpxEVl9AUu4Kfg4NWo3KQnzMTr6IahyBVizIQsxOdlzEdswBcq1BVk9DVsvDdt0Kep8JauvKWm5LXj3CWnxOZl9Ebg0HUk9Lcp9NSnuHZqyKQhuHQr1Abh8ASnuHZquDZlwDepzNYouMSvyHYh4AVm4LRvuAZo7MblyOTvxCXm4ESruKct7EYmwBZq3NWj4NfivPXtwCUg2IYt8Ldh9GUp3Cas8Kbr6Fco4Dfi7Las1Nev7NYq6HWi0OXi9LXl7BVozORl0Afq2Lel6Bck2BXvyKbk2ITmxOUrzBbmyBeiuHav2Nao9EVlxEWh1Hbk3AbiuEXt5GQh8GXm3HfqyFboxGTm4JVi0EVk9OYu9BUivLeuuNXoxKXkyGeo8KVv7Dej0Kcu2Bem9CQqvIVsuJRh9DZi1CQu4LZqyOXg4DdlvIQs4DVlyMdgwEXs2HQh4Eaq1JRmwIcq7BQu8MdqvDVuuKXo7NQn1NVpwKfqxOWr6HSh2Mav5ObvwIWi4JciuLfv8MTq9FVo2Dbs9OYv0AXnzPcjuFcs6MVk5LXn7LUguNbt6Hct1GUt7Dfv6EUg6GVg7EeoxKbr0GXvuIcp2HUp3EVu1HVk3NTu4NSp1IRnwORh5PSmvIbs9Dfr1PRjxCYvwNQv9KUl6Ids7Acg1LRk2KVo2CXm6KXn5CZuxHVm1Jfk8BQguDdvwDSu3NRm6Pak0KXp1IUg8BVryFSgvHfjvARivEVs7MXg2JVs9GTnuGYg5OUu4ETh3KejyKZm2DdjzATrzBUi3BVn7BejwNVj0NWh6EWm6MQlyGVl5EbhzCRs6CQovDTo2CUp9HRrwCeu9KbvuFQr3JSg4Gfi4ObruOdp4BRsvIRu9GWlyFUv1HZt6Cfk6AUu8OTpwNQn5CavyOZs5MYsuAXl0FVm3FQl3Ibn6OYruNWh6PamxGRryAVu4ASq6Icu4NfuwIXh1LVm1ASu6FTszAVp5GdluBck0Pfm3NYruFQt9MdhvDUk6AVmwIcnwAWrxCZuxGTnzHfl3JSh1Pdo2JfmvPRhwHRg5AauwCfu4IQv6NUu6NavvBWjxMWi8HWoyPZu2Dci3GTv2Lak3LfqwOVjwIdmxIep2Odk5FSu3AYryAbt3GSk8NdkuAbgwNWqyIeu8GRuwOai4MVp1BTp4MQkyIequNeg7DbhwFas2ARo5IRh3HRn7Dbr8NQtzBRpxNVp5MRk1BRjwEUpwPSu9MWgyLZhzGYp1JTj0IfrzNbpuGQl0Eer4Pft4NYi0Kcs5Ncs0HakvGavyBVp3MXk9Ibi9EQq7GTpyLSpuOeq0FTmyHam5JehzCaozPXlxFRh2AdtyDZq3Mbt9Kcu8LesuDfhzHet0Mdi4MekwLTr1FRr1CdruHei2Gbr3DYr5EXhvKWu1DUv1BXuuEQgyCYv8HQr8Aag2Ffn0GYl1Hcl8OWg7EQm1HYs6MRkzLSuvOdu4GTtvLXj7PQkwITlyPfuzKXmxFct3KYn6PUj7Cbn0FSn7GUkvHbu3HXmwARg5HZgxCQjzIRv6HRpxAUt8Bcl3MbvxHfs9GSq0NVnyHcovHaj2JTpvDQsyFft4MSj5MVq9Dcg3JRgwDRv1Eci7Gbo8Ocg0Dfr5KZq4Kbs5EZjvAZhvHYt3ITo9IXovHYm5AYg0HYu9NRi2Lek8GTn0AbkxDQswMXj6OXvvBRl0GUnuITr5MYl0MVv8Nbi4JQpwBdo7KYoyIWtwAQtvNVk7Adj4PRg5Bbv2HYnuDWjzNfp4IXpzMQryJfnyPcnyCVovOft3FUt1HZn2FcoxFVkwBQoyKUuxEXowIWhvCeg6DYv1IZmzCds7BemzDekuGSlwOQnzJZquDWs1Eck3PZh8JZg6CRqyCYj2IVhyHXpuHej7ISu6GXszDfm3GUv3FQt7AQn6IZr7HRj8Mdu9IRu7MUpwPag4Hdo8ITm0CesyEfkwGSm2IWvwFer3Bbj1NQu1DWk3LVl6Ieo8Ecq8HQtyEUo9Ebr3LUkwJckzLat7OQs0CWu6CapyGarzFVp3MUv1OQovFRkwIZp7BbpzFdguNek1ERp9MVm9GUj8NSt6Obs7GQrxORp3HUr4KVn2Beq8Ack1Oak9Mfu7Lag5Bdl6Ceh2Fej8HUp0LQs0JQo7FeqyHUv6OdowGanzJfu5GRo3Acs9Aeu3EVu1JcrzIds7DaouBZuzNVhwAWo6CYi6NdgwHTluEfsuJXq1Pdg6Fdn0Mcp3LcrwGekvNXl2ARhzDStvBSu9NUj6ORl6LQr6Ibm6EZt8KSuxHal2MRq2BXk4AclzAak5EYs3DUh8AflyIfs8KagvEUm8Dch3Adn1PfuvNag3GfjzKcvvGctzDbh6Jaq3Ldn3FSk7KVixLavxPVnyPTtyPah5MYhvNblzHak2Ifg7JWg2HdnzGcq2CSg3KalxGUozNZn8HfsvGSr7JTm6Dci2PZjyOYk3IRlyMShuBUv2HWvvIUqxEZp8EekwBXg1GZovFdv1JWlwPRg6NVozBet0JSguIZtvIRuvIbkyBXvuAQryLYh1GUlyDTt1Ofp9MamxKWmvCVtxDQtuMZg0HQl0OUv3FXq6KYsxIbvvHTk9PSr7EZjxCTt2KWpzHbk1HdixOdtxNXj6JRjvHctvKWozCdn8Kbq1IWn1BXi6PRvzFUn5CbuuCStvBQp9DWj0BcpvPVv4LcozPTo0BfovEYs7CfuuGar3AQgzGeozKYt4FTr8OdsuLeruKUl5Abl3DVr8NXi7MapuNXmxITs3HZizDSh8BVpzFbsuKRr3KZq0KXj9PVr3Nfp9Mes7Lar1Jdp2GWn8PSg1FYpzCYvuNQoxIekzFQh1IboxDVv4BWtuHao9GbjyIVsvIdvxLUh2Gei9KaqvCfjuNQh8HQi3EQp4ASh2EXlyNTk6GYt2KRn0KRv3CQixAfhxBYuxJZg5LQhxHdnvFYh6DSr1Acg9IVmxKXjzKeq6PVo3Lcj8GTl2GZu6FfpuHWv0Bdk9KSq2MXp7BXmzJch5OelvMStzPYr2FXswMcsuGWo3PXhyAfk6FUruKao1PSi3HRkuDahwBZlvHWk9BVtyFXp9DTpuIXv1IbhxIet6CSp1Bct8BWr1CTn6IUn9NUm1GaivEfv3BcozIbq2PavvOdg3HTm9CZt9NYixPTjvFer1BVnvNQnvHWl9MZj2PatyKWt9PSl4GdgyNVvuJYsvIYq2HRsuCRn3OSkuHdv3PQl1FSs0NfqvJQj6Bci1OUqyATp2GeuvJSs9ESlzIYt6Abq7BeryCai0Fds4Meh1AemvOQnzEdmwCTn0AYmzKWh0Abo6ETv4ERoyOaj8Bao1IetvOVg4Pbv9CWr8PUg3MRg2PXvuFZiwJUm0IXj9ARrxMWq5LSquJWsvDVluDYs8Jdt5Mer8MRiyDWozLbuvMSk1BZv5ITs5CQhyNTt4Ael6Pev8PYl7JTkvPWmyPdmyGRm2KYs6KUk5AYj0FRv5Bfu2Keg4Acn5Pcp1MesuEcoxJakxFfi9IXj0PYu3LVs0IdrvAYv1EboxAXkwASj6ETgxCQv7NRpuGUh0MVh2JRrxITr6Gfr3LXmzEYsvIej7KVryIRqwIbv5DXr1Cfl0KZm5Nep6FXs8JWt3BTn7GahwCah9MTivJRo9CSr3JfrzIfsvOXn5Hbm7CSm3BQr9BQoyHVuwOervPZv5FVt1GQjyAau1PSrxLbn8Kdh7MUo0JVnvLVkuFWlzNUkyPUhxCfo8KRt6CbjzHWt7OVtuFWs2Kdu2MQn1PbgwDdnuJUg4Fak9PYtyHbj7JXhyCWguETnwKdiyMcm4Lfq5PQk7Eci7PWt0Kav0PUtxCVs5KRqxEck0NVhyGWj0IQnvCYn2EYswNakvPahvKXiuDYgyKUt3LVuxEesyHUp3EaqwCTh9Ici8EYouMamxLfoxBVv7AavyGdr2Odj0Fbq6MRq0Edh8PQrvMap4Fei7LVvwCeu6HYkvMWh2IXv0CbtvKUh8Oci0KSrvGRv4Fdu6IXl1McjxHbn4Gav2EQj8Mbu6LVq6EVrvBXq2NViyAbp2LQg1KcqyCYs0MQo3EZmuEct3MdjzMdo7EWtvGUs9NaoxJVlxBdl0IUlvMYu1NWjwJfuuJUt9FVgyNTkyDdg0ERi8DXq5Ffo6LXrvBco5ASkvAfr9EZnyMah5Pfi8FRtyGVhvEXk5KanuGcr5Ldk6JWh8PYj5Mdo9Mfn3Kfm0Mej7MSv1OUn1OagwNTn6HZnyFZswHer7HUo3Nah4ASk7Leu9Gbk2AZl5PZl3DUgyBfg3CUsyDep4FXu5DVgyMTq7Fal1MVv8KaruOdi1Oag0MbvuHfo2OVizIWg0Afq9PXp6LZpuEZj0JTm6JQtzLeivMflvISi2KZl5Dcv7FSvxFaq9EVmwKVruNZl8LblvBUouKShuLXsyAVt8EWrwIcuwEaoyLXquFelwCfl3ORsvLckyLRs0Hcr1NXkyIfvvLai6KYk9NTvxCdk1MUlvJbhxNSnzMciyJVivDRi8ISlyBRhvFdu3FUi8CchyLQh8NSr6PWm8FTj1DRivHZt5MRk1BclzJduuAXn6FRh7HQgzATv6HUjuBdu1Aeu5Obr0Gdi7Bbh8Cfq7HSi2NTl4JRjuOQs2BZk4Gck9Dem5Ids7JSv2LVn7Mck8Mbp6Oag7Ndm2JftyKbn3KehzCQj8MTi7BfrwHbt4EXlzETg5IZs7PSn5ESmuMaq7Jan2ETiuKds6Car9Kfl0DVp5Lfk9AeguKRpvJeo7HalzGVn3PUp5Pbp9BRs8Hek6Bdq0MahvMam5Iar2OYkwBevxFZgxERmuHem5JRsyIZs7Gcp0CZh1BRs1Cbg9NYgwNQp6LWj0NToxKcozGZv9DWr4LVq8PQn8MThvGej6DVjwHRj6CUsvHTgxOVo0CQp7Jcj1DXg0HUn0DRh4HUsyFUp3Nbo5JXt6NZtvNfjvEdv9KdluJfl5LXi4EbowPWr1MYi1NYm7MUmxOYjxAar4JXryMfh6LQr7MfjyAXm0KYk1Pdh4GQizPfgyKWsyJXi7KWuzBWu2EQuwIRvwFQm5JZr7PZt6JZjxKWgvObhuGZj9OSj8DbuwLUhyJTn3Gbm9KXp0GZsxJWh5ORj9KWg0CZpwFQn0PTmxDaj2GXiyGZj4BRk9MVgyLXszAep8OZl2BSs6DZv6GetzCTt1OamuKdquLRk9AZgyNYu5HUu1NSo6HVs6DWu5FYo3NZgyBai5Aav8Bbl3AYg1GUjwBXivDXl4IdgvKUpzFUn9KXq7Fcp6Obr8BapyGTj2Kfg0HSl8JWs2EcquEZp1Pct9NeovCeovOWkwCct6PTmuCcmvPSh2NVgxKcn0EQr1Neu3CegvBaj8EYr0FUk1Iei3KdlwPeu1HYm6JXu5PSg5DUo1KWgyBau0Ebg7IZk9GSr8AZmyPShxIZm4OYp7HXtyPTuzEeluGUswNQh8JTk6PQq3OUr8Ddu2OSi1JfqvKam0FfjyKXr3Hco3Dap0FVqwPUjzIdk3HQi8Abo5EStyJToyJerwNel5NTo7AUi5Bfp8Jcp3Lem1Ddv9EWi4IQpyBUv9EZpyPfq2ATv6Mcg3Dfp1Pdu4NVsyMcn3PYm8Gei1ETi8LQs3KbvuOei8CQlzFRv6JWv0LTl9Ler9ETh9Bfm2PfnyKemxJWn0CRrwFakzCenvMVo9Hbm9OevxKfg6ERq3AXr5IdvzMfo6IYnyDRkzMai6MSs3Keh0OXp5HRn3CXn6AZlvEZquOco7JcDSj3FZmxGfjwDRk9Hal2GTm6gscfdd0046322b5dce4edcc0f3a70b8b0820",
    "aliasConfig": {
        "appName": ["", "", ""],
        "totalPageCount": [],
        "largePageWidth": [],
        "largePageHeight": [],
        "normalPath": [],
        "largePath": [],
        "thumbPath": [],
        "ToolBarsSettings": [],
        "TitleBar": [],
        "appLogoIcon": ["appLogoIcon"],
        "appLogoLinkURL": ["appLogoLinkURL"],
        "bookTitle": [],
        "bookDescription": [],
        "ButtonsBar": [],
        "ShareButton": [],
        "ShareButtonVisible": ["socialShareButtonVisible"],
        "ThumbnailsButton": [],
        "ThumbnailsButtonVisible": ["enableThumbnail"],
        "ZoomButton": [],
        "ZoomButtonVisible": ["enableZoomIn"],
        "FlashDisplaySettings": [],
        "MainBgConfig": [],
        "bgBeginColor": ["bgBeginColor"],
        "bgEndColor": ["bgEndColor"],
        "bgMRotation": ["bgMRotation"],
        "backGroundImgURL": ["mainbgImgUrl", "innerMainbgImgUrl"],
        "pageBackgroundColor": ["pageBackgroundColor"],
        "flipshortcutbutton": [],
        "BookMargins": [],
        "topMargin": [],
        "bottomMargin": [],
        "leftMargin": [],
        "rightMargin": [],
        "HTMLControlSettings": [],
        "linkconfig": [],
        "LinkDownColor": ["linkOverColor"],
        "LinkAlpha": ["linkOverColorAlpha"],
        "OpenWindow": ["linkOpenedWindow"],
        "searchColor": [],
        "searchAlpha": [],
        "SearchButtonVisible": ["searchButtonVisible"],
        "productName": [],
        "homePage": [],
        "enableAutoPlay": ["autoPlayAutoStart"],
        "autoPlayDuration": ["autoPlayDuration"],
        "autoPlayLoopCount": ["autoPlayLoopCount"],
        "BookMarkButtonVisible": [],
        "googleAnalyticsID": ["googleAnalyticsID"],
        "OriginPageIndex": [],
        "HardPageEnable": ["isHardCover"],
        "UIBaseURL": [],
        "RightToLeft": ["isRightToLeft"],
        "LeftShadowWidth": ["leftPageShadowWidth"],
        "LeftShadowAlpha": ["pageShadowAlpha"],
        "RightShadowWidth": ["rightPageShadowWidth"],
        "RightShadowAlpha": ["pageShadowAlpha"],
        "ShortcutButtonHeight": [],
        "ShortcutButtonWidth": [],
        "AutoPlayButtonVisible": ["enableAutoPlay"],
        "DownloadButtonVisible": ["enableDownload"],
        "DownloadURL": ["downloadURL"],
        "HomeButtonVisible": ["homeButtonVisible"],
        "HomeURL": ["btnHomeURL"],
        "BackgroundSoundURL": ["bacgroundSoundURL"],
        "PrintButtonVisible": ["enablePrint"],
        "toolbarColor": ["mainColor", "barColor"],
        "loadingBackground": ["mainColor", "barColor"],
        "BackgroundSoundButtonVisible": ["enableFlipSound"],
        "FlipSound": ["enableFlipSound"],
        "MiniStyle": ["userSmallMode"],
        "retainBookCenter": ["moveFlipBookToCenter"],
        "totalPagesCaption": ["totalPageNumberCaptionStr"],
        "pageNumberCaption": ["pageIndexCaptionStrs"]
    },
    "aliasLanguage": {
        "frmPrintbtn": ["frmPrintCaption"],
        "frmPrintall": ["frmPrintPrintAll"],
        "frmPrintcurrent": ["frmPrintPrintCurrentPage"],
        "frmPrintRange": ["frmPrintPrintRange"],
        "frmPrintexample": ["frmPrintExampleCaption"],
        "btnLanguage": ["btnSwicthLanguage"],
        "btnTableOfContent": ["btnBookMark"],
        "btnExitFullscreen": ["btnDisableFullScreen"],
        "btnFullscreen": ["btnFullScreen"],
        "btnHome": ["homebtnHelp"],
        "btnMore": ["btnMoreOptionsLeft"],
        "frmToc": ["btnBookMark"],
        "frmSearch": ["btnSearch"],
        "frmLinkLabel": ["lblLink"]
    },
    "meta": {
        "htmlTemplate": "Popular",
        "theme": "Default",
        "title": "Menu Brothers",
        "description": "",
        "url": "https:\/\/online.fliphtml5.com\/hbozp\/onfk\/index.html",
        "pageCount": 32,
        "pageWidth": 612,
        "pageHeight": 792,
        "template": "Popular"
    },
    "project-config": [],
    "bmtConfig": {
        "tabs": [],
        "onSideEdge": false,
        "hasTexture": false
    },
    "videoList": [],
    "staticAd": {
        "haveAd": false,
        "bgColor": "#000",
        "bgOpacity": 1,
        "interval": 0,
        "adPosition": 0,
        "data": []
    },
    "language": [{
        "language": "English",
        "btnFirstPage": "First",
        "btnNextPage": "Next Page",
        "btnLastPage": "Last",
        "btnPrePage": "Previous Page",
        "btnDownload": "Download",
        "btnPrint": "Print",
        "btnSearch": "Search",
        "btnClearSearch": "Clear",
        "frmSearchPrompt": "Enter key to search.",
        "btnBookMark": "Table of content",
        "btnHelp": "Help",
        "btnHome": "Home",
        "btnFullscreen": "Fullscreen",
        "btnSoundOn": "Sound On",
        "btnSoundOff": "Sound Off",
        "btnShareEmail": "Email",
        "btnSocialShare": "Social Share",
        "btnZoomIn": "Zoom In",
        "btnZoomOut": "Zoom Out",
        "btnDragToMove": "Move by mouse drag",
        "btnAutoFlip": "Auto Flip",
        "btnStopAutoFlip": "Stop Auto Flip",
        "btnGoToHome": "Return Home",
        "frmHelpCaption": "Help",
        "frmHelpTip1": "Double click to zoom in or out",
        "frmHelpTip2": "Drag the page corner to view",
        "frmPrintCaption": "Print",
        "frmPrintBtnCaption": "Print",
        "frmPrintPreparePage": "Preparing Page:",
        "frmPrintPrintFailed": "Print Failed:",
        "pnlSearchInputInvalid": "The search text is too short.",
        "loginCaption": "Login",
        "loginInvalidPassword": "Not a valid password!",
        "loginPasswordLabel": "Password:",
        "loginBtnLogin": "Login",
        "loginBtnCancel": "Cancel",
        "btnThumb": "Thumbnails",
        "lblPages": "Pages:",
        "lblPagesFound": "Pages:",
        "lblPageIndex": "Page",
        "btnAbout": "Profile",
        "frnAboutCaption": "About & Contact",
        "btnSinglePage": "Single Page",
        "btnDoublePage": "Double Page",
        "tipChangeLanguage": "Please select a language below...",
        "btnMoreOptionsRight": "More Options",
        "btnFit": "Fit Window",
        "smallModeCaption": "Click to view in fullscreen",
        "btnAddAnnotation": "Add Annotations",
        "btnAnnotation": "Annotations",
        "FlipPageEditor_SaveAndExit": "Save and Exit",
        "FlipPageEditor_Exit": "Exit",
        "DrawToolWindow_Redo": "Redo",
        "DrawToolWindow_Undo": "Undo",
        "DrawToolWindow_Clear": "Clear",
        "DrawToolWindow_Brush": "Brush",
        "DrawToolWindow_Width": "Width",
        "DrawToolWindow_Alpha": "Alpha",
        "DrawToolWindow_Color": "Color",
        "DrawToolWindow_Eraser": "Eraser",
        "DrawToolWindow_Rectangular": "Rectangular",
        "DrawToolWindow_Ellipse": "Ellipse",
        "TStuff_BorderWidth": "Border Width",
        "TStuff_BorderAlph": "Border Alpha",
        "TStuff_BorderColor": "Border Color",
        "DrawToolWindow_TextNote": "Text Note",
        "AnnotMark": "Bookmarks",
        "lastpagebtnHelp": "Last page",
        "firstpagebtnHelp": "First page",
        "aboubtnHelp": "About",
        "screenbtnHelp": "Open this application in full-screen mode",
        "helpbtnHelp": "Show help",
        "searchbtnHelp": "Search from pages",
        "pagesbtnHelp": "Take a look at the thumbnail of this brochure",
        "bookmarkbtnHelp": "Open Bookmarks",
        "AnnotmarkbtnHelp": "Open Table of content",
        "printbtnHelp": "Print the brochure",
        "soundbtnHelp": "Turn on or off the sound",
        "sharebtnHelp": "Send Email to",
        "socialSharebtnHelp": "Social Share",
        "zoominbtnHelp": "Zoom in",
        "downloadbtnHelp": "Downdlaod this brochure",
        "pagemodlebtnHelp": "Switch Single and double page mode",
        "languagebtnHelp": "Switch Lauguage",
        "annotationbtnHelp": "Add Annotation",
        "addbookmarkbtnHelp": "Add Bookmark",
        "removebookmarkbtnHelp": "Remove Bookmark",
        "updatebookmarkbtnHelp": "Update Bookmark",
        "btnShoppingCart": "Shopping Cart",
        "Help_ShoppingCartbtn": "Shopping Cart",
        "Help_btnNextPage": "Next page",
        "Help_btnPrePage": "Previous page",
        "Help_btnAutoFlip": "Auto filp",
        "Help_StopAutoFlip": "Stop atuo filp",
        "btnaddbookmark": "Add",
        "btndeletebookmark": "Delete",
        "btnupdatebookmark": "Update",
        "frmyourbookmarks": "Your bookmarks",
        "frmitems": "items",
        "DownloadFullPublication": "Full Publication",
        "DownloadCurrentPage": "Current Page",
        "DownloadAttachedFiles": "Attached Files",
        "btnCopy": "Copy Button",
        "infCopyToClipboard": "Your browser does not support clipboard.",
        "restorePage": "Would you like to restore your previous session?",
        "tmpl_Backgoundsoundon": "Background Sound On",
        "tmpl_Backgoundsoundoff": "Background Sound Off",
        "tmpl_Flipsoundon": "Flip Sound On",
        "tmpl_Flipsoundoff": "Flip Sound Off",
        "Help_PageIndex": "The current page number",
        "tmpl_PrintPageRanges": "PAGE RANGES",
        "tmpl_PrintPreview": "PREVIEW",
        "btnSelection": "Select Text",
        "loginNameLabel": "Name:",
        "btnGotoPage": "Go",
        "btnSettings": "Setting",
        "soundSettingTitle": "Sound Setting",
        "closeFlipSound": "Page-flipping Sound",
        "closeBackgroundSound": "Background Sound",
        "frmShareCaption": "Share",
        "frmShareLinkLabel": "Link:",
        "frmShareBtnCopy": "Copy",
        "frmShareItemsGroupCaption": "Social Share",
        "frmPanelTitle": "Share it",
        "frmShareQRcode": "QR Code",
        "TAnnoActionPropertyStuff_GotoPage": "Go to page",
        "btnPageBack": "Backward",
        "btnPageForward": "Forward",
        "SelectTextCopy": "Copy Selected Text",
        "selectCopyButton": "Copy",
        "TStuffCart_TypeCart": "Shopping Cart",
        "TStuffCart_DetailedQuantity": "Quantity",
        "TStuffCart_DetailedPrice": "Price",
        "ShappingCart_Close": "Close",
        "ShappingCart_CheckOut": "Checkout",
        "ShappingCart_Item": "Item",
        "ShappingCart_Total": "Total",
        "ShappingCart_AddCart": "Add to cart",
        "ShappingCart_InStock": "In Stock",
        "TStuffCart_DetailedCost": "Shipping cost",
        "TStuffCart_DetailedTime": "Delivery time",
        "TStuffCart_DetailedDay": "day(s)",
        "ShappingCart_NotStock": "Not enough in stock",
        "btnCrop": "Crop",
        "btnDragButton": "Drag",
        "btnFlipBook": "Flip Book",
        "btnSlideMode": "Slide Mode",
        "btnSinglePageMode": "Single Page Mode",
        "btnVertical": "Vertical Mode",
        "btnHotizontal": "Horizontal Mode",
        "btnClose": "Close",
        "btnBookStatus": "Book View",
        "checkBoxInsert": "Insert Current Page",
        "lblLast": "This is the last page.",
        "lblFirst": "This is the first page.",
        "lblFullscreen": "Click to view in fullscreen",
        "lblName": "Name",
        "lblPassword": "Password",
        "lblLogin": "Login",
        "lblCancel": "Cancel",
        "lblNoName": "User name can not be empty.",
        "lblNoPassword": "Password can not be empty.",
        "lblNoCorrectLogin": "Please enter the correct user name and password.",
        "btnVideo": "Video Gallery",
        "btnSlideShow": "Image Gallery",
        "btnPositionToMove": "Move by mouse position",
        "lblHelp1": "Drag the page corner to view",
        "lblHelp2": "Double click to zoom in, out",
        "lblCopy": "Copy",
        "lblAddToPage": "add to page",
        "lblPage": "Page",
        "lblDescription": "Title",
        "lblEdit": "Edit",
        "lblDelete": "Delete",
        "lblRemoveAll": "Remove All",
        "tltCursor": "cursor",
        "tltAddHighlight": "add highlight",
        "tltAddTexts": "add texts",
        "tltAddShapes": "add shapes",
        "tltAddNotes": "add notes",
        "tltAddImageFile": "add image file",
        "tltAddSignature": "add signature",
        "tltAddLine": "add line",
        "tltAddArrow": "add arrow",
        "tltAddRect": "add rect",
        "tltAddEllipse": "add ellipse",
        "lblDoubleClickToZoomIn": "Double click to zoom in.",
        "frmShareLabel": "Share",
        "frmShareInfo": "You can easily share this publication to social networks.Just cilck the appropriatebutton below.",
        "frminsertLabel": "Insert to Site",
        "frminsertInfo": "Use the code below to embed this publication to your website.",
        "btnQRCode": "Click to scan QR code",
        "btnRotateLeft": "Rotate Left",
        "btnRotateRight": "Rotate Right",
        "lblSelectMode": "Select view mode please.",
        "frmDownloadPreview": "Preview",
        "frmDownload": "Download",
        "frmHowToUse": "How To Use",
        "lblHelpPage1": "Swipe your finger to flip through pages.",
        "lblHelpPage2": "Pinch to zoom or double-tap on the page.",
        "lblHelpPage3": "Rotate your device to landscape mode for reading.",
        "lblHelpPage4": "Access thumbnails, use the search function, or enable auto-flip.",
        "lblHelpPage5": "Tap the logo to open a website.",
        "TTActionQuiz_PlayAgain": "Do you wanna play it again",
        "TTActionQuiz_Ration": "Your ratio is",
        "frmTelephone": "Telephone list",
        "btnDialing": "Dialing",
        "lblSelectMessage": "Please copy the the text content in the text box",
        "btnSelectText": "Select Text",
        "btnNote": "Annotation",
        "btnPhoneNumber": "Telephone",
        "btnWeCharShare": "WeChat Share",
        "btnMagnifierIn": "Magnifier",
        "btnMagnifierOut": "Magnifier Reduction",
        "frmShareSmallProgram": "smallProgram",
        "btnMagnifier": "Magnifier",
        "frmPrintPrintLimitFailed": "Sorry, you can't print the pages.",
        "infNotSupportHtml5": "HTML5 is not supported by your current web browser, please read the book with latestverson web browser. Here we recommend you to read it with Chrome.",
        "btnReport": "Report",
        "btnDoubleSinglePage": "Page switch",
        "btnDownloadPosterPrompt": "Click to download the poster",
        "infLongPressToSavePoster": "Press and hold the mobile terminal to save the poster",
        "infLongPressToIndentify": "Long press to identify QR code",
        "infScanCodeToView": "Scan code to read",
        "frmaboutcaption": "Contact",
        "frmaboutDESCRIPTION": "Description",
        "frmaboutAUTHOR": "Author",
        "frmaboutADDRESS": "Address",
        "frmaboutEMAIL": "Email",
        "frmaboutWEBSITE": "Website",
        "frmaboutMOBILE": "Mobile",
        "infDeleteNote": "Do you want to delete the note?",
        "proFullScreenWarn": "Current browser does not support full-screen,Please use Chrome for best results",
        "btnBack": "Backs",
        "frmVideoListTitle": "Video list",
        "frmVideoTitle": "Video",
        "lblConfirm": "Confirm",
        "frmBookMark": "Bookmark",
        "btnExitFullscreen": "Exit fullscreen",
        "btnMore": "More",
        "frmPrintall": "Print All Pages",
        "frmPrintcurrent": "Print Current Page",
        "frmPrintRange": "Print Range",
        "frmPrintexample": "Example: 2,3,5-10",
        "frmPrintbtn": "Print",
        "frmaboutcontactinformation": "Contact Information",
        "frmSearch": "Search",
        "frmToc": "Table of Contents",
        "btnTableOfContent": "Show Table of Contents",
        "frmLinkLabel": "Link",
        "frmQrcodeCaption": "Scan the bottom two-dimensional code to view with mobile phone.",
        "btnLanguage": "Change Language",
        "msgConfigMissing": "Configuration file is missing, unable to open the book.",
        "lblSave": "Save",
        "accessRestrictedTitle": "Access Restricted",
        "enterYourName": "Enter your name",
        "enterVisitCode": "Please enter your password",
        "enterReadingCode": "enter your reading code",
        "enterTheReason": "Enter your reason for application",
        "enterPhoneNumber": "Enter your email address",
        "enterVerificationCode": "Enter your verification code",
        "getVerificationCode": "Send",
        "sendValidCodeSuccess": "Verification code sent",
        "getVerificationCodePrompt": "Get a verification code sent to your email",
        "enterPasswordPrompt": "Password required to proceed reading",
        "leaveMsgSimilarBooks": "Explore More Books",
        "leaveMsgToAuthor": "Contact Author",
        "leaveMsgName": "Your Name",
        "leaveMsgContact": "Your Contact Information (visible only to the author)",
        "leaveMsgEnter": "Please Enter the Message",
        "leaveMsgCancel": "Cancel",
        "leaveMsgCommitTitle": "Submit",
        "leaveMsgPrompt": "We will forward your message to the book uploader.",
        "leaveMsgErrorPrompt": "Exception occurred. Please try again later",
        "readingCodeErrorPrompt": "Invalid reading code. Please try again",
        "passwordErrorPrompt": "Invalid password. Please try again",
        "invalidPhoneNumber": "Invalid number. Please try again",
        "invalidEmail": "Invalid Email. Please try again",
        "verificationCodeErrorPrompt": "Invalid verification code. Please try again",
        "codeSendingFrequent": "Frequent operation, please try again later",
        "commiteTitle": "Verify",
        "shamStopTitle": "The author's account privileges have resulted in book access suspension.",
        "shamStopSubTitle": "Contact <a target='_blank' href='{%host}\/homepage\/{%uLink}\/' style='text-decoration: underline' >the author<\/a> for further information.",
        "shamStopLeavePrompt": "Please complete the question.",
        "shamStopLeaveMsgSuccessPrompt": "Send successfully",
        "codeSending": "Sending",
        "viewFullScreen": "Fullscreen",
        "cardsSign": "click to view card",
        "frmaboutViews": "Views",
        "btnMessage": "Message",
        "btnInstructions": "instructions",
        "btnArticlePages": "Pages",
        "btnArticleList": "Articles",
        "btnCalendar": "Calendar",
        "btnBook": "Book",
        "btnEnlarge": "Enlarge",
        "btnReduce": "Reduce",
        "btnPrevArticle": "Prev Article",
        "btnNextArticle": "Next Article",
        "copySuccessfully": "Copy Successfully",
        "cardsWechat": "Wechat",
        "cardsTelephone": "phone",
        "close": "close",
        "jumpPageByEnterNumber": "Enter the page number to jump quickly to the specified page",
        "jump": "Jump",
        "relatedContent": "related information",
        "brandTitleUndefined": "No brand name is set yet",
        "more": "More",
        "fold": "Put away",
        "otherWorks": "other works",
        "flipSound": "page turning sound",
        "backgroundSound": "Background music",
        "report": "report",
        "copySuccessTip": "copy successfully",
        "saveSuccessTip": "Saved successfully",
        "scanCodeAddMy": "After saving, WeChat scan the code and add my friend",
        "saveImg": "save Picture",
        "searchTheBook": "Search this book content",
        "historicalRecord": "history record",
        "searchResultCount": "A total of {%count} results",
        "noRelevantResults": "No relevant results",
        "changeTheKeyWords": "Try another keyword ~",
        "leastWordsTip": "Please enter at least 2 words",
        "jumpPageInputTip": "Enter the page number to jump quickly to the specified page",
        "jumpto": "Jump to",
        "foldThumbnailTip": "Click here to put away the thumbnail ~",
        "btnLoadingText": "In loading, it's fine soon",
        "btnTitleText": "Read now",
        "relatedInfoText": "Related Information",
        "brandContactFrTitle": "Contact the author",
        "shareFromPage": "Share starting from page N",
        "TStuffShowInformatin_Width": "Background width",
        "TStuffShowInformatin_Height": "Background height",
        "TPageList_BlankPage": "Blank page",
        "morePanelBookLink": "Link",
        "morePanelPoster": "Poster",
        "morePanelOtherShare": "Other",
        "doublePageTitle": "Enable Landscape Mode to Read in Two-page View",
        "doublePageAndroidTitle": "Enable Landscape Mode to Read in Two-page View?",
        "doublePageDescription": "How to set landscape ?",
        "doublePageGotIt": "Got it",
        "doublePageAndroidSettingStep1": "1.Allow auto-rotation in phone settings",
        "doublePageAndroidSettingStep2": "2.Allow landscape in browser settings",
        "doublePageAndroidSettingStep3": "3.Turn your phone sideways to read",
        "doublePageIPhoneSettingStep1": "1.Disable portrait orientation lock",
        "doublePageIPhoneSettingStep2": "2.Rotate your phone",
        "noFilesAvailablePrompt": "No Files Available!",
        "reportBtn": "Report",
        "reportConfirm": "Submit",
        "reportCancel": "Cancel",
        "reportAlertBoxCloseBtn": "Close",
        "reportTitle": "Please select the reason for reporting",
        "reportSuccessPrompt": "Report successful",
        "reportError": "Report failed",
        "reportNetworkError": "Report failed, request link error",
        "reportDescErrorPrompt": "Detailed description cannot be empty or contain only whitespace characters",
        "reportContactErrorPrompt": "Contact information cannot be empty or contain only whitespace characters",
        "reportTextareaPlaceholder": "Please provide detailed reasons for reporting (required)",
        "reportNumberPlaceholder": "Please provide a valid phone number for better understanding of the situation;otherwise, it will not be processed",
        "reportReasonSource": "Please select the reason for reporting; Piracy Copyright Infringement; Medical HealthPlastic Surgery False Advertising; Cult Violation of National Policies; Pornography GamblingDrugs Pyramid Scheme; Other reasons",
        "businessNone": "None",
        "lblSimulatePageFlip": "Simulate page-flipping on a computer",
        "lblSimulatePageSlide": "Tailor to the sliding habits on a tablet",
        "suspendedForExpiredMembership": "Due to the expiration of the account member service, the access to the book has been suspended by the system",
        "suspendedForMaxReadLimit": "Due to the account reading times being exhausted, the book has been suspended by the system",
        "suspendedForReadLimit": "Due to the limit on the number of readings, the access to the book has been suspended by the system",
        "suspendedForContact": "To resume it, you can contact the author directly.",
        "expiredRedirectButton": "Explore More Books",
        "btnPhoneticReading": "Listen",
        "btnPhoneticTips": "You can listen to and read this book at the same time.",
        "articleSummary": "Article Summary",
        "articleFirst": "This is the first article.",
        "articleLast": "This is the last article.",
        "articleBack": "Back",
        "multimediaSoundOn": "Music on",
        "multimediaSoundOff": "Music off",
        "downloadRestrictionTips": "Download access for this book is restricted by the publisher.",
        "encrpytionSearchTips": "The book has restricted access.<br\/>Please obtain permission before searching.",
        "chatbotBtnTips": "Hi~ Ask me about the book here!",
        "searchMatchType": "Split term search",
        "settingMultimediaSoundTitle": "Music",
        "settingMultimediaSoundPlayTips": "There are pages without music currently. Once music is enabled, it will only play on pages with music.",
        "settingMultimediaSoundPauseTips": "After music is disabled, pages with music will no longer play.",
        "downloadingTips": "Downloading...",
        "downloadSuccessfully": "Download successful!",
        "comment_title": "Reader Message",
        "comment_userNameTip": "Name",
        "comment_numTip": "Contact Number (visible to author only)",
        "comment_leaveMess": "Please enter your message",
        "comment_submitText": "Submit",
        "comment_emptyPrompt": "Be the first to post a message!",
        "comment_closeLeaveMessage1": "Sorry!",
        "comment_closeLeaveMessage2": "The author has disabled the display of messages",
        "comment_closeLeaveMessage3": "You cannot view other readers' messages",
        "comment_successMess": "Message submitted successfully",
        "comment_successShowText": "Your message will be displayed after admin approval",
        "comment_successHideText": "The admin will receive your message",
        "comment_successGotIt": "Got it",
        "comment_loadingText": "Loading, please wait...",
        "comment_noMoreText": "No more messages...",
        "comment_emptyErrorMsg": "Message content cannot be empty",
        "comment_specialErrorMsg": "Message content cannot contain special characters",
        "comment_frequentlyErrorMsg": "Sorry, you're posting too frequently. Please wait a moment before submitting again.",
        "comment_errorMsg": "Sorry, due to system busy, submission failed. Please try again later.",
        "comment_username": "Anonymous",
        "comment_authorName": "Author",
        "comment_replyMsg": "Reply",
        "accessLimitedText": "The book is protected. Please purchase it, or verify password \/ your email to continue reading.",
        "printRestrictionTips": "*Print access for this book is restricted by the publisher.",
        "lblVerifyPwdBtn": "Verify",
        "ariaPage": "Page",
        "ariaAddBookmark": "Add bookmark",
        "ariaColorSelection": "Color selection",
        "ariaShareLink": "Book link",
        "ariaCopy": "Copy",
        "ariaPreviousPage": "Previous page",
        "ariaNextPage": "Next page",
        "ariaFirstPage": "First page",
        "ariaLastPage": "Last page",
        "ariaSearchTableOfContents": "Search table of contents",
        "ariaPageNumber": "Page number",
        "decreaseFontSizeBtn": "Decrease font size",
        "increaseFontSizeBtn": "Increase font size",
        "shareItem_email": "Email",
        "shareItem_copy": "Copy",
        "shareItem_qrcode": "QRcode",
        "shareItem_poster": "Poster",
        "shareItem_more": "More",
        "Annotation_Sticker": "Sticker",
        "Annotation_AddText": "Add Text",
        "Annotation_SelectText": "Select Text to Copy or Add Notes",
        "Annotation_Brush": "Brush",
        "Annotation_Highlighter": "Highlighter",
        "Annotation_Rectangle": "Rectangle",
        "Annotation_Ellipse": "Ellipse",
        "Annotation_Eraser": "Eraser",
        "Annotation_Clear": "Clear",
        "Annotation_Undo": "Undo (Ctrl+Z)",
        "Annotation_Redo": "Redo (Ctrl+Shift+Z)",
        "Annotation_Done": "Done",
        "Annotation_Exit": "Exit",
        "Annotation_AddSticker": "Add Sticker",
        "Annotation_Color": "Color",
        "Annotation_Alpha": "Alpha",
        "Annotation_Size": "Size",
        "Annotation_DeleteNote_tips": "Sure to delete?",
        "Annotation_DeleteNote_Confirm_Btn": "Yes",
        "Annotation_DeleteNote_Cancel_Btn": "No",
        "Annotation_Edit": "Edit",
        "Annotation_Delete": "Delete",
        "Annotation_color_title": "Select color",
        "Annotation_SaveSuccess": "Saved successfully",
        "Annotation_SelectText_Disabled_Message": "You cannot select text in this book. This restriction may be due to the publisher's settings or the nature of the book's content.",
        "modern_panel_done": "Done",
        "modern_panel_see_all_text": "See All Text",
        "modern_panel_swipe_to_select": "Swipe over the text to select",
        "modern_select_text_empty": "No text can be selected",
        "modern_copy_success": "Successfully copied",
        "modern_copy_error": "Failed to copy",
        "modern_select_text_title": "Select Text",
        "modern_search_text": "Search text",
        "modern_select_all": "Select all",
        "modern_copy": "Copy",
        "modern_loading_text": "Loading...",
        "modern_cancel": "Cancel",
        "bookmarkEmptyTitle": "No bookmark yet",
        "bookmarkEmptyDescription": "You can add or delete bookmarks by pulling down the book page",
        "modern_search_result_count": "Total",
        "modern_search_result": "results",
        "modern_search_recent": "Recent",
        "searchContentPlaceholder": "Search book content",
        "searchBookmarkPlaceholder": "Search bookmark",
        "searchThumbnailsPlaceholder": "Search pages",
        "searchTocPlaceholder": "Search table of content",
        "bookmarkDefaultTitle": "Page",
        "modernShareCurrentPage": "Share from current page",
        "mdnSearchPage": "P",
        "modern_copy_empty": "No text to copy",
        "modern_select_all_success": "All text selected",
        "modern_select_all_hint": "Please manually select text",
        "Annotation_Add_Note_Title": "Add text note",
        "Annotation_Add_Note_Placeholder": "add texts ...",
        "noLanguageAvailable": "No language available",
        "infGeneratingPoster": "loading...",
        "modern_btn_dialing": "Dialing",
        "add_bookmark_btn": "Add Bookmark",
        "delete_bookmark_btn": "Delete Bookmarks",
        "bookmarkedTips": "Bookmarked",
        "deletedBookmarkTips": "Deleted bookmarks",
        "pullToAddBookmark": "Pull to add bookmark",
        "releaseToAddBookmark": "Release to add bookmark",
        "tryAnotherKeyword": "please try another keyword",
        "frmaboutEmptyProfile": "Please set up your profile content first.",
        "noPhoneNumber": "No phone number.",
        "frmvideoGalleryEmpty": "Please set up your video gallery content first.",
        "Annotation_Tip_SavedInBrowser": "1.Your annotations are saved in the browser, so switching browsers or computers will hide your notes.",
        "Annotation_Tip_StorageFull": "2.If its storage is full, you are not able to add more annotations. You can delete some to add more.",
        "Annotation_Tip_Title": "Tips",
        "Annotation_Tip_Know": "I know",
        "Annotation_Tip_OK": "OK",
        "Annotation_Tip_DontRemind": "Don't remind me later.",
        "Annotation_Save_Fail_Title": "Fail to save!",
        "Annotation_Save_Fail_Text": "You are not able to add more annotations because the browser's storage is full. You can delete some annotations to add more.",
        "Annotation_SelectTextTip": "What's new ? You can add notes after selecting texts !",
        "Annotation_IKnow": "I know",
        "Bookmark_Already_Exists": "This page already has a bookmark.",
        "Bookmark_Add_Success_Tips": "The bookmark has been added.",
        "Bookmark_Delete_Success_Tips": "The bookmark has been deleted.",
        "Bookmark_No_Bookmark_Yet": "This page has no bookmark yet.",
        "Bookmark_Author_Added_Tips": "If a bookmark has been added to a page by the author, you cannot add any bookmark to that page.",
        "Bookmark_Placeholder": "Caption",
        "nextPageBtn": "Next page",
        "previousPageBtn": "Previous page",
        "accessPageNum": "Page",
        "accessibilityTitle": "Text version of the book",
        "frmPrintNoticeTip": "This book contains too many pages. Printing all pages at once may cause the browser to crash and prevent successful printing.Please use Print Range to print in batches for better results.",
        "frmPrintNoticeBtn": "Notice",
        "msgContentNotFound": "Content not found",
        "Annotation_AddNote": "Add Note",
        "Annotation_Copy": "Copy",
        "Annotation_NoteList": "Note List",
        "Annotation_DownloadAll": "Download All Notes",
        "Annotation_CopySuccess": "Copy Successfully!",
        "annotation_AddTexts": "Enter your note here...",
        "frmBookMarkAuthorHint": "If a bookmark has been added to a page by the author, you cannot add any bookmark to that page.",
        "frmBookMarkAuthorInfoAria": "More information about bookmarks",
        "frmLanguageTitle": "Display Language",
        "modernLanguageTitle": "Language"
    }],
    "ols": [],
    "slideshow": [],
    "pageEditor": [],
    "flipByAudio": null,
    "downloadconfig": {
        "pdf": null,
        "isDownloadProject": false,
        "isDownloadAttach": false,
        "attachments": [],
        "hideDownloadSinglePage": false
    },
    "assistantConfig": null,
    "phoneNumber": [],
    "bookPlugin": null,
    "phoneTemplate": {
        "name": "",
        "path": ""
    },
    "slider": [],
    "downloadConfig": null,
    "fliphtml5_pages": "v0100011020d6JWiyNUk1Pap5Bfg6Les5Dbm0Efo6BXvxAUp4ATl4CZtuNfruJVk8GYixEWv4OSi5OXnzAem2JSq9KXt9PRh1Mfo6NdkyGQn8Ebi1CVr1NUi8PTixEZiyNdq7Kfu5AZmvIdt5Nbg1LXiuCQv5OVp1JSl3OchxDWqzFRm0CUu9BYk2HVj3JWnvIZp6KUu5DRj5OVi2OSouJVrxDYp6ISquMZu3Nep5FQnwAXv8HWi3FQq0Fbi7BZm8Hdk7OdnzLbu5MfqvASj6HQvzOSuvOZm9Jei6EdiuOZiwBbp1BVswJWg7LUk6OTn8KTo8Pas7AcgwDct7FVk6JZgxPbsxEbs7ISv7PWs9DQp6ITj9CRs4FRu0AVj8Ebi3IQl4Caq2NYg3HSj7Jer2Hbl4PTswOcq7Jdn3CWpyFWn2Ieq4IcqzJXp4EYl0Ndm0LXm2Ndh9Bfk1JdryOVs5Bas8MYr1IZqxHXkwEUq2ITg5KTl0HYp5MeruKagxDTmyPXn5AYr9JTnwEQm1BRuuEdv9FUrwIcp8CYl6Ncj9AWmxLTqxOasyHVm2KRt7HbkwCVq4KQm1NQq1GYl0CVj9BVqvGct9Odt7KVsyPWlwGWh9KVjzPbh6PfhzIbpvPUo0HVs3Lfr1GbnwOan7HZhuJWr2Gbq2PZivMci5MemyBSv8KWp1NXt1PXmxNYkyAcjzOQluKXp3AYpvNQq5PfrwCRq5Mbp8HVouKZnwLRg3BTmxKWh2MahzEXt0GYk2KRq3Daq1MXsxEXj6Lfg6AQsxHUjxKeh4HeswKWn9MTgvDQn0MVu9BfrxDagyBcpwDbsyFaq5BVq3ATn3FagxIal3Nct6Ffl0NTg9NftyPdiuIQu6Cbq1EZi6EVl1OVnvIXt8LWt6Deo5ETtzGfj9Gem8BTlvFYu9LWo1PXi9JcuwHTqvORl8NXmwJQo9AVs8OSu7FQh9CaovDam9BZk7DRpxGWj6DVg8KYt8EVrzIegwLev6Afv6MdswCQq4KXtvMVi0Ces0NWm2JSmxAdl4IRpzDQk1DStwJXiyMVqvFeq5Jdl2LbvuMTs0Ech5ATh3Edl3ObuyIUk9LZv4FTu7Kft1KbmyPQr8LVuwDfnyEXlwAXowIQt6ISm6PSp4CTi1IRg3EXs6HRp1IWn3JVh7BVp2ISp3Mbv7BfkyFXn6Jbj5ESkuGSn2Oet8AYo1Aau3GTrvJdouARm5MXh5Cbp2LYo5DUr4MXg6Jbo1LZuzDQr5EXo0GSq3Pai1ERp3JZk9Bcu3AZr5CSo8DbmuFTg6MUoxIZlyDel3ARq6GdsuOcm7GRs1MSsuJWg7AUt5OWs2JVq2Ddu7PVtxJej4OckzKUnzFYiyMdi3JTnuOcs1GVgwHWpwHTi8IYh7JWrwNequKag5IWnvLXuxBdmzEcq5EUp7Fbs9Cdt7CWkuFdswMQpzEVi4CRguPfv0Jfn9JRmzOVnuKXuxGVtzPbv4FRkzOUh8Dft9OQt8EXpwFRjxCahwDXgwLTkyDZi7CUhxJUk0FRr9IUjvIaryIdn8Pdo3JSm6FQmwGUt7NUr5FSj7Lcl2ASuzGaowCSu6EUk4MWgxJVj2ISqyBQuzJUnxOWqyBZgyAdkyPfovDYp6BapvIdk9Kfp2KQgwLTh8Bfl0GUmzFXg4CTr3MWtzIdq2EehzPWg1LWjxKei9HfjvPXhuGZp5DVsvFSn8JduxFXo2Pbt1MTv5BXuuKfq2Hbl7MdgxOcq2Abj5DYlyBUruLTg9DSv1GSh2ORm5KTnxIen2Mat2LWrxEXh0KdsxIdj5GWp6BSt2DWqvJegwFYt6Das1Jfl5OYk4OXm6LQryPQv4CUi3OWhxBVm3OWh7PYh7PWh2Ffr1BZm3KSuwPdpzAXn3EQi1JSrxBbjyMVryGRl5HYizEcs5HbgyIbtyCXvvEXoyMUu9EQm4PfmwFQvuASg3Kcl8Lci9NRq1Ofr8PZtxCRo3Ocr2GfnxDUj0IVn8EWi0Dfm4NRi9Ofu0DZn8Gbu5Nfu9CSrxNdu6PduvLRi6LUhvNbo4ESr7JUnyPbqvBUq7CTouOcvzKQhzJdh6KXlzFVr0FWn5DTu1AQlyIVmwEWv4Kbl2JQqzFdj1Icm5KUiwMWuyBXkvJfhxKUi2DYpwJUkyKRtzKdr9MZg9GRv1LUn5PQt3DSvvObmzAZk4Nap1OarxKauxEfoyDRq2KZl3HRk9OQpvJXoyPbr6HSu9Pch2PYizISu4OSu1EYm5PUi7Cag2OfluFch5LWh8JQsuCSs4EYovHbh3IVm7MRvwJZs6Cco4DXgvPdr8KajuOVr0EajvKUs2CRmuPZr5BVmwKTo6LbhxAQh4Mfr5IahwNWvxBdsxNapuIcmuAbi4FQhwCXl8Dfq7KVuzDQoxAYhxLeo3GQnyBbp2IWg3IRk3Hbl8ARq0MZiyOenxNXu3KVjxBSuyBUu7GXl6AVhwKeruMYuuCcgvIfi7ORq9MbvuIfhzFRn4Pfs0GTs9EcmzLfg9EWk4KSj0Mai8GQh1BYjxPdo8IQs7JTvuOXoyMdv5FYvuOarvMZt5Kbv9OYg1CSgyLeq7GTi1MTv0JenyDbp9NcjyDWk1DYivCZiuAeuzAQn6PZt8PQuxMUs3BUt2LSs7ERnuFcg0Ebk0FdqzMauzETjxLTn3IZp1CfjwDam1Bau0PSszHdi7FYguPRs9CRiyOdu5MRk8Fei5Cci0AWu4FWi5FZluKWovFbq5Nbt9JQryIVp8DZuyASs4ATp4OUsuHZt7HXjvIfr1MRj8Bbj4PUk4IYtuKfouAcm1OXrvGXn7EeuzIRv4GSgyEXn3HVk1Eam6CUj3GRuzORqyFfh2OWsyOVr1JZrzBWvzHdhzNbh3PYlvKdq1DQgxMWp5Dbg5BUv4BZn4Jcv2JdgwGXg5AUhzPQkvCXpxITh8EYn0KSkuEUp5HUgzBWn1BQnuKRgvJYn8GSjuOZp5FVk9JUizLRi3CfkxMet6CekzGUqwHfk8KSt8MVvwFeh5McrxOUi6JRt6AaozDbr1HZo1ASg6GSv4Ner1PbivEfs7Ecq5Idl3HbnwEXg9KTo9Pfn0MZj8Jcq1EQv0Efl0IfgyKbg4KSl0Lfk3EXv2Ocl3NYl8Kak9ASt9DRm0GcoxDSn2CcswMTrvOQu5JajuFSqxJYq5JQqxNZr0OcquATg4NRm1FQv2PXsxMSkwPZo0FYr2CemyKUvuPQn4FYj1HUg8BfiwGcv9OZv0CYtzLZi1Eel8CRt2EVl6IZs1OQg9PdmyFdiuLSo2MUv8BQgvIao0JSk5Hbm9PTm9Pav9KYrzGWouOVv5Ccl8Daj2LRg7Cct3NWv7FQkvIUhzMYo8Pbk0KVi7Das7Ndp2LTixBVv7NYk3GYqxGRo3KahwAYt4ETpxOet5ORh2BbkzDcs8HQp7Efu1DTm7HWgyKYmzPThwLetzAWlzMcnwLRi1BXvyAZh2NXm1KcsxPYi8HVhzPYouCXn9Gfn5Bah5Gel9AflxOen6OQlzOWvxDXq3LVp4HVmyHQk0JWi2GYn6JZk3Acl3MZnvMQj7ParvOckuFfq6MZr3EejzNUu7GVs1HYnuIXq7NRkuEci3Abo6BXh7Edk6Ddh9PZq0Lau3CarxIThyDUm8Kbt8CXp4OUoyOSi8JVp5GXs7IRsyBWu1OWnyFWnyNQnyNfiyCTr7HUg7BRnzEYmwOeruJdo1FSi0KcswPQg0HTq3Abv5HeqyFTruOTr8CTm9Mdm7JTm6HTtvGWv5LYo3Kfm8Jen9IZqyNTk8OZr6DZu8PUo4Iep6EYi5AZk6HTt7HVv2Pco5AZkwERs1HRvxGXs6MQn0GSj8LUpzKTg0AQsvEcoyIfm2Bfu1NRixFSv2OXixKfj0GYi6HTixASn7FanuKZuzIcp6LWn8FYg4GVivPah3Aeh8KQixCfl3LXo2FbnxJUhzKQk4DWm0PSv7Neg1OWlyLdnuIXo1JTo6FWjwKVr3MauvLYs8BRn8ATlvNZs1FfmwBbnxDZszPeq5PWm3EQr2HXt5AWg7MTp6GcjyKci9HTsvLaq7KYq9Mej3GTmyFZk0NZhzPYv5NepuNSv9EfuwOeo8ARiwHYoxMej8HctwBciuFSjuAan9CSmvIbk6JVh0JZn1AQv2DQh1DTmxMRsvBSr5BTlyIQo3Lbo0PQh2Bfl3KbpwFbo1JVl8KSjxEZr5OYj7LZl0DQk6HSuyIRh8EWr3PYgxMcm1KdlxBWmvNRk1ITj9JQo3OSozKcqzLclwPWi9MRl4MTv3EUr1OUnwIbvvHSh4Dbg9HYt2Kfh5OXp3IRq8Fcp0ISv1FchvFbowJXi1Acm2EVtuNXg2Dcn2LcqvIUo1OVo1Jan5Ddl9NWt6JXt2KVh7CVnyAUv7CYpvEct0KVruERozCUt4BTg9JXtwCThuMZi3Cbg3MWm7FetvFTj7Ofu0BSn3ESh7Jcl5GSnyCWs0CdgyMci4HZl4JUvxMQp1PTk6KXrvBVl2IWj8DXj1NTt6GQsvCQgwMZp5LXt2FQrwCUvvKXnyHbi0OTpyGQr0MXq7AXq0HUg7JTm3MUvvMYq2JVhyMSg1HVi3OeguGfjvIZj1MRgxPchvFXu9Eej3PQl3ITr6IdmzGdl5AWl9Dau9LfhwOTr0EVt5KSm3Ifg7ARv6BcjyAZoxDWn4HSv7Dfp7FZt7PXo1EXr8HTmvBZuwGelzCXjvDcq4KWo0FZlyHQg9Feo5ISnzNRt0Nco9EYlwGQg9Cct7JXoyJfk4LZlzGft3MbswDchwIfh9CTkyGVnzAfhvJSoxKQn7Fei4JQiyIauwIUq7IUg5OYg8Pbj6Pah3KQm4EQrvJeq3IRq2LSp1Ifs9PVhzMclyNQm3EZq1AZmzKat7Cfp1ISq7BTq9IZj4BRhuAWn0Mat4CWg5CfvuIRl3Lbt6OZo5HTtzEbr2JWq5GcgvOZl8Pbv9GZm5JarvKaiyLSt9Gau8Pdq8Kbo1FavyOUtzNVj2LYhwPTqzLZi8Jbu9Gcg2JaruHaj0FaouHRjvIfv4Pen0IYt2PUt4HVhxCdg7PRt8LdpzMdj0IWo7EUkuAdg2Jeq8BZm3GXs7IUl1CWs4HduwMbo4Ofk7JejvAVouMTivHTu4JVjzAduzHeg0NWl3HWg9Las7Peq8PSrxJah5OZm3JRkuLTj2IUm0MRi0MSruMepuLft7NfquESnxKYtvDYqyFTp8PSh3Cek6MWs5BZkyPbrwEah2FQo2PXj8PfjyFSo3FSrzNWv8Icg3FQn3Mdk9LSvxLWowCXm9GTi3Pco1PTq3IbnzFWmxMbswAStvEej5AVpxDSr4ETn8Eah1DRs0CYoxDSl7DRkwEdvuPZp4AXv7PZlxJanvNfk3MVp4ManyKZpyOTn5LenxJUq5Hfg8Bct5FckvMdkxCWu9Kag9Ial1BTrwOcl8AdgzNdovKepzCUnyOYm8GUu2HWn6FTpxNUl1GWu9Cag5CVnxOXmyDbtvEQhzMYs1IclyAeg2CfvzEbvuAWv4Has0Neg0CSk5LZl7EZl3BYp3FckuPRu9DQs6JQn5JWuxCQivATh2Dav4FVvxBZu5Lan9HfsxPbjvPfp7LUo5AUk2ERk1AXg2FYi9Neh0Faq6PZmvAZs9KXk2IbguJXt2Ieh0MZu0Hbj2PQp3DWsyKdh0AfhyISm4IcmxAQs7IfuyFYm4NSo7NSpyEfiwLen0GRjxNZnwIRh7LStxJSo2OSnyORt4DeizDdi2IUn8MUh6Kdo4Ecp5CTqxIWuuAUvzHTu4Gdp6IXt3BXo1KTh1PTkyDfq5JTuzAev6GcqzEWv9DfuyLak0AbiuOYj4EYuzATlyCek7Dbr3GclwJXu4NRg0GTn4NeluBTj3KWtvFdsxISqxIUt6AarzEbmxKVj0HXgzKVmyKSn7EWh4HQk8OTn9AbvvOch7IRkxMeu4GemzGfs3CbjzFQn0LXnuKaq2LQlxFRn1FXi6IegwLQu3Kap9IUm8BVk8DQkuIXr2OUhvKTl8Ibn9EQh2Las4Meq6Mcm6Bbr2IRsxBcmuMfjxGcl2CQi0IRp3EQuzKTv2LZtyCSl2FbvxBdu9HQp4JUgxGXuuJSg7FSqzIek3FUtxIdiyERluIen5JbuuMfr1HWh4EXh8NUv3BSn8DZkzKXj5DRtzCepyDTr8DajxGbqvMfu7PRs1ATvyDasyNQswNQm5Afo5DUsxKSt6LcsyPRn6EYo2JUm4PXtzKTrwIQozMYn9Geo5MUmxEXr2CTi8Afp3BSr3CSk7Cbt1MZo1GZp2BZi5BWp0FQv8DbrxLVjyJVpwAbuwGTv6ISp3OVjuDfl8Ndg3GYp8KSk8HVsxLWt7GfvvKZu4Hap0LUmzPag8DZqxGch6AXq5JRr2EdqwDSsyEboxGat1NUjyPRq2Naj6Bao1Peg8LVi7Ebt5NUqzHbu2BSh0BUjxKVi9BVk1Kdt3DWg8ITk2HTh9DZp0DVqzPTo3Ndu4MYr1IYu7MepxDQm6AXl3AVh4PVh6Kfk0LVm8BahwBequIbg9JYsvORk5IYv7GTgzBSk3Ffl5JZs7IRsxISh2JRhwEXu4JcrzKTn7FRi2MbrxDZl6Nbq8ASv5Mfg8AUlyOUi8KRu1CSmvKTs2Fam6KZsyJYi6HXqyFSr9Nar3FWt9Hej7OetvFQlyPdgxKbp3PXv3Mcu8AQkvCWj3JTq7PYvyMXkwOakzAVv5NYt6LUuwHZs8Hdn9FXi5Des2NagyAfnwFVuzKYh7IVkzPbnwCWj1Iao2ARq5IVo9LWv9GXt8FegyAbqzBYvuPTr6FXn8BXjxAQkyNcn1LRq3GTj5FTv5LVt6FZm2EelxIfv5Mdg4Kfi1Aev5NSoxGYt3EZm3BSl9OQg9CUuwOWq5Jas5AWswJej3MQq1FUsvCaq7BTs7Odr7BZo3MUj2Afi7PZi8Ibu2HWhuOev8MfizDQhuCSk9Pdq2AQr3IYmvBXquNeo8Nfv1HZjwPTg4FWgxGavzGSv6IVixOWn4PZm1GVp4NUl8KVrzJcq2FVg8CZk7NVjvJbuyGSiyGarzPVm6Jds4KZjuPVquAXi1GYj6GTq4BZkwCak6CYk7JYtyHZg0BZl9IasxGeh3GWr2ISgyBdpwJThvIVi1KUqvNVp5ASk0Dft7Ndj5Mbm5MTr1CQi2KTi1Oej7MfjuGdk7BfnzDUpxJdq6EZg9Adh1DXk9Cfj4NXo2FQo9OUp1FUm6AerwDTjzCctvHds5NSn2MXkyFfm4HRu5OZs6HYh4BZiuLbrxCUi2Gct4HRi9GVuwORl7JesuCbqyPUj8DVs1Fbo1OYs5AZjzCYj8DRiyPRi1Ocl3DZg0NTh9Ndl5ISp1FTg9NXqyDfm4JbmxLRlwOel8IcrvFXovNav2ITkxPbh4CflyKal1PXkwNTs8FYvzCRhzAXguIQm3KalxGUmxCUs4AUs5EQl9BRoyEdu3FenuDah7Ffh0OTq3JZtvMSszCRu4KYjyBRi5MRs3JRu2Hek6GRoxBTquNVv5KWpxGRu2HVm0OQg6DSvzNer2DUu1FfvvFRg7Hdv4MUuyAXh1PUqvNXt7Fdr5ERjwDRrwOUizORnuPRq7ObkwHek7IfuzGZvuKcn3MXm4DUtyBbt3Bft6HfhxOdq5DbvwDUqwGSs8Lck6FUp3FYsuEcvuGajxPQu8GYt5MYmuEUq2HcqzJQoxCRg7Mdo8JfhxAXm4NVv8KauyLdgxBQq6ETk2GbjwJag6AbuzIdq3KSq8OUn4Gbt0DVi3CVr4CbvzJXmwPZm5LWu2PRr9FQg8Ift3Aen3Ffi6ESn5Eag7NYqzJar8GZp1LZi1LTp5Oet7GRkzKZvzIdu5MZs8Afs9JYp3FeuzGfjuLUn0ETkwKSl3HTi3FasuEfs2MahwHXrxJTo2MXo2Ddt4Nav2MVpvJWjxAejyLZtwAbjxGajuOXhyPVm1NbjxNWh3GTl3FSh5DXoyAYvyDWr6OQhwCUjzEYpwJRs5HbquJXg8Dfj4GYqwFdixIeuvPYrvLcquEcl5MQn2LWq6Bcj0BSuwKRq2Hbm9GRi0MXq8AYj9Lan6PXm1MSpwPTn8GRmvAeo5BRiyFcg4PYl7OUuuBTsxCagzMThzNbj3DQt0OfkvPdrzBQk6Kap0ARv7BQiyBVi3Eas2NdrvPUqwJYkwJVk2IQs0Nej7LUu7KbszBeq0CWh6GSguKau1PdoxIYn6Dds0Bct7CfkuNdn6MQtuEVp7FSr1HfuxNZu2BRhyFXj7CVg4Kfo4JQpvAdl9Pdv5AXqyPYr9FXg5GUg5AXk6Iet0OakuOWg7Adu8LXnvOZh7Hcm1FepuIThuJZq2LRmxLXm0PRgzNfg3Bdk4CUj3NXj8Gcg8Obg6FZgxKRpyLRj0JWpvEds5PSGWmyHSk8EenzHXn6FWQ566ec842d7cad37b565317875ced14b6e20",
    "search_pages": [{
        "index": 0
    }, {
        "index": 1
    }, {
        "index": 2
    }, {
        "index": 3
    }, {
        "index": 4
    }, {
        "index": 5
    }, {
        "index": 6
    }, {
        "index": 7
    }, {
        "index": 8
    }, {
        "index": 9
    }, {
        "index": 10
    }, {
        "index": 11
    }, {
        "index": 12
    }, {
        "index": 13
    }, {
        "index": 14
    }, {
        "index": 15
    }, {
        "index": 16
    }, {
        "index": 17
    }, {
        "index": 18
    }, {
        "index": 19
    }, {
        "index": 20
    }, {
        "index": 21
    }, {
        "index": 22
    }, {
        "index": 23
    }, {
        "index": 24
    }, {
        "index": 25
    }, {
        "index": 26
    }, {
        "index": 27
    }, {
        "index": 28
    }, {
        "index": 30
    }, {
        "index": 31
    }, {
        "index": 29
    }],
    "pages_information": [{
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }, {
        "pageColor": "var(--e_backgroundcolor_1)",
        "pageIsStrech": false
    }],
    "themeCssVarList": {
        "--e_theme_1": "#397AF3",
        "--e_theme_2": "#D7E5FD",
        "--e_theme_3": "#B0CAFA",
        "--e_theme_4": "#88B0F8",
        "--e_theme_5": "#0C53D5",
        "--e_theme_6": "#08378E",
        "--e_titlecolor_1": "#262626",
        "--e_titlecolor_2": "#E9E9E9",
        "--e_titlecolor_3": "#C9C9C9",
        "--e_titlecolor_4": "#939393",
        "--e_titlecolor_5": "#5C5C5C",
        "--e_titlecolor_6": "#3C3C3C",
        "--e_fontcolor_1": "#333333",
        "--e_fontcolor_2": "#EBEBEB",
        "--e_fontcolor_3": "#CCCCCC",
        "--e_fontcolor_4": "#999999",
        "--e_fontcolor_5": "#666666",
        "--e_fontcolor_6": "#474747",
        "--e_backgroundcolor_1": "#FFFFFF",
        "--e_backgroundcolor_2": "#E6E6E6",
        "--e_backgroundcolor_3": "#BFBFBF",
        "--e_backgroundcolor_4": "#808080",
        "--e_backgroundcolor_5": "#404040",
        "--e_backgroundcolor_6": "#191919",
        "--e_color1_1": "#13A6E5",
        "--e_color1_2": "#CFEEFB",
        "--e_color1_3": "#9FDDF7",
        "--e_color1_4": "#6FCCF3",
        "--e_color1_5": "#0E7EAD",
        "--e_color1_6": "#095474",
        "--e_color2_1": "#00BDDE",
        "--e_color2_2": "#C6F6FF",
        "--e_color2_3": "#8DEEFF",
        "--e_color2_4": "#54E5FF",
        "--e_color2_5": "#008FA8",
        "--e_color2_6": "#005F70",
        "--e_color3_1": "#24D3BB",
        "--e_color3_2": "#D2F7F2",
        "--e_color3_3": "#A4F0E6",
        "--e_color3_4": "#77E8D9",
        "--e_color3_5": "#1B9D8C",
        "--e_color3_6": "#12695D",
        "--e_color4_1": "#55DD95",
        "--e_color4_2": "#DDF8EA",
        "--e_color4_3": "#BBF2D4",
        "--e_color4_4": "#99EBBF",
        "--e_color4_5": "#26C06E",
        "--e_color4_6": "#198049",
        "--e_theme_1_trans_1": "#D7E5FD",
        "--e_theme_1_trans_2": "#B0CAFA",
        "--e_theme_1_trans_3": "#88B0F8",
        "--e_theme_1_trans_4": "#0C53D5",
        "--e_theme_1_trans_5": "#08378E",
        "--e_theme_2_trans_1": "#ACC9FB",
        "--e_theme_2_trans_2": "#699DF7",
        "--e_theme_2_trans_3": "#0C59DF",
        "--e_theme_2_trans_4": "#062D6F",
        "--e_theme_2_trans_5": "#02122D",
        "--e_theme_3_trans_1": "#8AB0F8",
        "--e_theme_3_trans_2": "#4E88F4",
        "--e_theme_3_trans_3": "#0D4FC9",
        "--e_theme_3_trans_4": "#062765",
        "--e_theme_3_trans_5": "#031028",
        "--e_theme_4_trans_1": "#E7EFFE",
        "--e_theme_4_trans_2": "#CFDFFC",
        "--e_theme_4_trans_3": "#B7CFFB",
        "--e_theme_4_trans_4": "#2C72F3",
        "--e_theme_4_trans_5": "#0B46B5",
        "--e_theme_5_trans_1": "#C9DBFC",
        "--e_theme_5_trans_2": "#93B7F9",
        "--e_theme_5_trans_3": "#5D92F6",
        "--e_theme_5_trans_4": "#093E9F",
        "--e_theme_5_trans_5": "#06296A",
        "--e_theme_6_trans_1": "#BBD1FB",
        "--e_theme_6_trans_2": "#76A3F7",
        "--e_theme_6_trans_3": "#3275F3",
        "--e_theme_6_trans_4": "#062969",
        "--e_theme_6_trans_5": "#041B46",
        "--e_titlecolor_1_trans_1": "#E9E9E9",
        "--e_titlecolor_1_trans_2": "#C9C9C9",
        "--e_titlecolor_1_trans_3": "#939393",
        "--e_titlecolor_1_trans_4": "#5C5C5C",
        "--e_titlecolor_1_trans_5": "#3C3C3C",
        "--e_titlecolor_2_trans_1": "#D1D1D1",
        "--e_titlecolor_2_trans_2": "#AEAEAE",
        "--e_titlecolor_2_trans_3": "#747474",
        "--e_titlecolor_2_trans_4": "#3A3A3A",
        "--e_titlecolor_2_trans_5": "#171717",
        "--e_titlecolor_3_trans_1": "#F4F4F4",
        "--e_titlecolor_3_trans_2": "#EAEAEA",
        "--e_titlecolor_3_trans_3": "#DFDFDF",
        "--e_titlecolor_3_trans_4": "#979797",
        "--e_titlecolor_3_trans_5": "#656565",
        "--e_titlecolor_4_trans_1": "#EAEAEA",
        "--e_titlecolor_4_trans_2": "#D4D4D4",
        "--e_titlecolor_4_trans_3": "#BFBFBF",
        "--e_titlecolor_4_trans_4": "#6F6F6F",
        "--e_titlecolor_4_trans_5": "#4A4A4A",
        "--e_titlecolor_5_trans_1": "#DEDEDE",
        "--e_titlecolor_5_trans_2": "#BEBEBE",
        "--e_titlecolor_5_trans_3": "#9D9D9D",
        "--e_titlecolor_5_trans_4": "#454545",
        "--e_titlecolor_5_trans_5": "#2E2E2E",
        "--e_titlecolor_6_trans_1": "#D8D8D8",
        "--e_titlecolor_6_trans_2": "#B1B1B1",
        "--e_titlecolor_6_trans_3": "#8B8B8B",
        "--e_titlecolor_6_trans_4": "#2E2E2E",
        "--e_titlecolor_6_trans_5": "#1F1F1F",
        "--e_fontcolor_1_trans_1": "#EBEBEB",
        "--e_fontcolor_1_trans_2": "#CCCCCC",
        "--e_fontcolor_1_trans_3": "#999999",
        "--e_fontcolor_1_trans_4": "#666666",
        "--e_fontcolor_1_trans_5": "#474747",
        "--e_fontcolor_2_trans_1": "#D3D3D3",
        "--e_fontcolor_2_trans_2": "#B0B0B0",
        "--e_fontcolor_2_trans_3": "#757575",
        "--e_fontcolor_2_trans_4": "#3B3B3B",
        "--e_fontcolor_2_trans_5": "#171717",
        "--e_fontcolor_3_trans_1": "#B8B8B8",
        "--e_fontcolor_3_trans_2": "#999999",
        "--e_fontcolor_3_trans_3": "#666666",
        "--e_fontcolor_3_trans_4": "#333333",
        "--e_fontcolor_3_trans_5": "#141414",
        "--e_fontcolor_4_trans_1": "#EBEBEB",
        "--e_fontcolor_4_trans_2": "#D6D6D6",
        "--e_fontcolor_4_trans_3": "#C2C2C2",
        "--e_fontcolor_4_trans_4": "#737373",
        "--e_fontcolor_4_trans_5": "#4D4D4D",
        "--e_fontcolor_5_trans_1": "#E0E0E0",
        "--e_fontcolor_5_trans_2": "#C2C2C2",
        "--e_fontcolor_5_trans_3": "#A3A3A3",
        "--e_fontcolor_5_trans_4": "#4D4D4D",
        "--e_fontcolor_5_trans_5": "#333333",
        "--e_fontcolor_6_trans_1": "#DADADA",
        "--e_fontcolor_6_trans_2": "#B6B6B6",
        "--e_fontcolor_6_trans_3": "#919191",
        "--e_fontcolor_6_trans_4": "#363636",
        "--e_fontcolor_6_trans_5": "#242424",
        "--e_backgroundcolor_1_trans_1": "#E6E6E6",
        "--e_backgroundcolor_1_trans_2": "#BFBFBF",
        "--e_backgroundcolor_1_trans_3": "#808080",
        "--e_backgroundcolor_1_trans_4": "#404040",
        "--e_backgroundcolor_1_trans_5": "#191919",
        "--e_backgroundcolor_2_trans_1": "#CFCFCF",
        "--e_backgroundcolor_2_trans_2": "#ACACAC",
        "--e_backgroundcolor_2_trans_3": "#737373",
        "--e_backgroundcolor_2_trans_4": "#393939",
        "--e_backgroundcolor_2_trans_5": "#171717",
        "--e_backgroundcolor_3_trans_1": "#F2F2F2",
        "--e_backgroundcolor_3_trans_2": "#E6E6E6",
        "--e_backgroundcolor_3_trans_3": "#D9D9D9",
        "--e_backgroundcolor_3_trans_4": "#8F8F8F",
        "--e_backgroundcolor_3_trans_5": "#606060",
        "--e_backgroundcolor_4_trans_1": "#E6E6E6",
        "--e_backgroundcolor_4_trans_2": "#CCCCCC",
        "--e_backgroundcolor_4_trans_3": "#B3B3B3",
        "--e_backgroundcolor_4_trans_4": "#606060",
        "--e_backgroundcolor_4_trans_5": "#404040",
        "--e_backgroundcolor_5_trans_1": "#D9D9D9",
        "--e_backgroundcolor_5_trans_2": "#B3B3B3",
        "--e_backgroundcolor_5_trans_3": "#8C8C8C",
        "--e_backgroundcolor_5_trans_4": "#303030",
        "--e_backgroundcolor_5_trans_5": "#202020",
        "--e_backgroundcolor_6_trans_1": "#E8E8E8",
        "--e_backgroundcolor_6_trans_2": "#C6C6C6",
        "--e_backgroundcolor_6_trans_3": "#8C8C8C",
        "--e_backgroundcolor_6_trans_4": "#535353",
        "--e_backgroundcolor_6_trans_5": "#303030",
        "--e_color1_1_trans_1": "#CFEEFB",
        "--e_color1_1_trans_2": "#9FDDF7",
        "--e_color1_1_trans_3": "#6FCCF3",
        "--e_color1_1_trans_4": "#0E7EAD",
        "--e_color1_1_trans_5": "#095474",
        "--e_color1_2_trans_1": "#A5DFF8",
        "--e_color1_2_trans_2": "#66C8F3",
        "--e_color1_2_trans_3": "#119AD4",
        "--e_color1_2_trans_4": "#094D6A",
        "--e_color1_2_trans_5": "#031F2A",
        "--e_color1_3_trans_1": "#7BD0F4",
        "--e_color1_3_trans_2": "#42BCF0",
        "--e_color1_3_trans_3": "#0F89BD",
        "--e_color1_3_trans_4": "#08445E",
        "--e_color1_3_trans_5": "#031B26",
        "--e_color1_4_trans_1": "#E2F5FD",
        "--e_color1_4_trans_2": "#C5EAFA",
        "--e_color1_4_trans_3": "#A7E0F8",
        "--e_color1_4_trans_4": "#1BAEED",
        "--e_color1_4_trans_5": "#0D76A3",
        "--e_color1_5_trans_1": "#C4EAFA",
        "--e_color1_5_trans_2": "#88D5F5",
        "--e_color1_5_trans_3": "#4DBFF1",
        "--e_color1_5_trans_4": "#0B5F83",
        "--e_color1_5_trans_5": "#073F57",
        "--e_color1_6_trans_1": "#B8E6FA",
        "--e_color1_6_trans_2": "#71CDF4",
        "--e_color1_6_trans_3": "#2AB4EF",
        "--e_color1_6_trans_4": "#074059",
        "--e_color1_6_trans_5": "#042B3B",
        "--e_color2_1_trans_1": "#C6F6FF",
        "--e_color2_1_trans_2": "#8DEEFF",
        "--e_color2_1_trans_3": "#54E5FF",
        "--e_color2_1_trans_4": "#008FA8",
        "--e_color2_1_trans_5": "#005F70",
        "--e_color2_2_trans_1": "#9AF0FF",
        "--e_color2_2_trans_2": "#55E6FF",
        "--e_color2_2_trans_3": "#00C1E3",
        "--e_color2_2_trans_4": "#006071",
        "--e_color2_2_trans_5": "#00272D",
        "--e_color2_3_trans_1": "#E9FCFF",
        "--e_color2_3_trans_2": "#D2F8FF",
        "--e_color2_3_trans_3": "#BCF5FF",
        "--e_color2_3_trans_4": "#2BDFFF",
        "--e_color2_3_trans_5": "#00A9C7",
        "--e_color2_4_trans_1": "#DCFAFF",
        "--e_color2_4_trans_2": "#BAF5FF",
        "--e_color2_4_trans_3": "#97EFFF",
        "--e_color2_4_trans_4": "#00D7FC",
        "--e_color2_4_trans_5": "#008FA8",
        "--e_color2_5_trans_1": "#BBF5FF",
        "--e_color2_5_trans_2": "#76EAFF",
        "--e_color2_5_trans_3": "#32E0FF",
        "--e_color2_5_trans_4": "#006B7E",
        "--e_color2_5_trans_5": "#004854",
        "--e_color2_6_trans_1": "#AFF3FF",
        "--e_color2_6_trans_2": "#60E7FF",
        "--e_color2_6_trans_3": "#10DBFF",
        "--e_color2_6_trans_4": "#004854",
        "--e_color2_6_trans_5": "#003038",
        "--e_color3_1_trans_1": "#D2F7F2",
        "--e_color3_1_trans_2": "#A4F0E6",
        "--e_color3_1_trans_3": "#77E8D9",
        "--e_color3_1_trans_4": "#1B9D8C",
        "--e_color3_1_trans_5": "#12695D",
        "--e_color3_2_trans_1": "#ADF0E7",
        "--e_color3_2_trans_2": "#72E6D7",
        "--e_color3_2_trans_3": "#22C3AE",
        "--e_color3_2_trans_4": "#116257",
        "--e_color3_2_trans_5": "#072723",
        "--e_color3_3_trans_1": "#EDFCFA",
        "--e_color3_3_trans_2": "#DAF9F5",
        "--e_color3_3_trans_3": "#C8F6F0",
        "--e_color3_3_trans_4": "#4CE2CE",
        "--e_color3_3_trans_5": "#1CAD9A",
        "--e_color3_4_trans_1": "#E4FAF7",
        "--e_color3_4_trans_2": "#C9F6F0",
        "--e_color3_4_trans_3": "#AEF1E8",
        "--e_color3_4_trans_4": "#2DDBC4",
        "--e_color3_4_trans_5": "#1A9686",
        "--e_color3_5_trans_1": "#C7F6EF",
        "--e_color3_5_trans_2": "#8FECE0",
        "--e_color3_5_trans_3": "#58E3D0",
        "--e_color3_5_trans_4": "#147669",
        "--e_color3_5_trans_5": "#0D4E46",
        "--e_color3_6_trans_1": "#BDF4EC",
        "--e_color3_6_trans_2": "#7AE9DA",
        "--e_color3_6_trans_3": "#38DDC7",
        "--e_color3_6_trans_4": "#0D4E46",
        "--e_color3_6_trans_5": "#09342F",
        "--e_color4_1_trans_1": "#DDF8EA",
        "--e_color4_1_trans_2": "#BBF2D4",
        "--e_color4_1_trans_3": "#99EBBF",
        "--e_color4_1_trans_4": "#26C06E",
        "--e_color4_1_trans_5": "#198049",
        "--e_color4_2_trans_1": "#B6F0D2",
        "--e_color4_2_trans_2": "#7CE4AE",
        "--e_color4_2_trans_3": "#28C373",
        "--e_color4_2_trans_4": "#146139",
        "--e_color4_2_trans_5": "#082717",
        "--e_color4_3_trans_1": "#96EBBD",
        "--e_color4_3_trans_2": "#60E19A",
        "--e_color4_3_trans_3": "#22B464",
        "--e_color4_3_trans_4": "#115A32",
        "--e_color4_3_trans_5": "#072414",
        "--e_color4_4_trans_1": "#EBFBF2",
        "--e_color4_4_trans_2": "#D6F7E5",
        "--e_color4_4_trans_3": "#C2F3D9",
        "--e_color4_4_trans_4": "#48DB8C",
        "--e_color4_4_trans_5": "#20A25D",
        "--e_color4_5_trans_1": "#D0F6E2",
        "--e_color4_5_trans_2": "#A1ECC4",
        "--e_color4_5_trans_3": "#72E3A7",
        "--e_color4_5_trans_4": "#1C9052",
        "--e_color4_5_trans_5": "#136037",
        "--e_color4_6_trans_1": "#C3F3DA",
        "--e_color4_6_trans_2": "#88E7B4",
        "--e_color4_6_trans_3": "#4CDC8F",
        "--e_color4_6_trans_4": "#136037",
        "--e_color4_6_trans_5": "#0D4025",
        "--e_theme_l50": "#9CBDF9",
        "--e_theme_l35": "#7FA9F8",
        "--e_theme_l25": "#6B9CF6",
        "--e_theme_l15": "#578EF5",
        "--e_theme_l5": "#4381F4",
        "--e_theme_l90": "#EBF2FE",
        "--e_theme_l75": "#CEDEFC",
        "--e_theme_l10": "#4D88F5",
        "--e_theme_l80": "#D7E5FD",
        "--e_theme_l60": "#B0CAFA",
        "--e_theme_l40": "#88B0F8",
        "--e_theme_d25": "#0C53D5",
        "--e_theme_d50": "#08378E",
        "--e_theme_d10": "#1D67F2",
        "--e_theme_d75": "#041C47",
        "--e_theme_d90": "#020B1C",
        "--e_theme_d5": "#2B71F3",
        "--e_theme_d15": "#0F5EF1",
        "--e_theme_d35": "#0B48B9",
        "--e_titlecolor_l50": "#939393",
        "--e_titlecolor_l35": "#727272",
        "--e_titlecolor_l25": "#5C5C5C",
        "--e_titlecolor_l15": "#474747",
        "--e_titlecolor_l5": "#313131",
        "--e_titlecolor_l90": "#E9E9E9",
        "--e_titlecolor_l75": "#C9C9C9",
        "--e_titlecolor_l10": "#3C3C3C",
        "--e_titlecolor_l80": "#D4D4D4",
        "--e_titlecolor_l60": "#A8A8A8",
        "--e_titlecolor_l40": "#7D7D7D",
        "--e_titlecolor_d25": "#1D1D1D",
        "--e_titlecolor_d50": "#131313",
        "--e_titlecolor_d10": "#222222",
        "--e_titlecolor_d75": "#0A0A0A",
        "--e_titlecolor_d90": "#040404",
        "--e_titlecolor_d5": "#242424",
        "--e_titlecolor_d15": "#212121",
        "--e_titlecolor_d35": "#191919",
        "--e_fontcolor_l50": "#999999",
        "--e_fontcolor_l35": "#7A7A7A",
        "--e_fontcolor_l25": "#666666",
        "--e_fontcolor_l15": "#525252",
        "--e_fontcolor_l5": "#3D3D3D",
        "--e_fontcolor_l90": "#EBEBEB",
        "--e_fontcolor_l75": "#CCCCCC",
        "--e_fontcolor_l10": "#474747",
        "--e_fontcolor_l80": "#D6D6D6",
        "--e_fontcolor_l60": "#ADADAD",
        "--e_fontcolor_l40": "#858585",
        "--e_fontcolor_d25": "#262626",
        "--e_fontcolor_d50": "#1A1A1A",
        "--e_fontcolor_d10": "#2E2E2E",
        "--e_fontcolor_d75": "#0D0D0D",
        "--e_fontcolor_d90": "#050505",
        "--e_fontcolor_d5": "#303030",
        "--e_fontcolor_d15": "#2B2B2B",
        "--e_fontcolor_d35": "#212121",
        "--e_backgroundcolor_l50": "#FFFFFF",
        "--e_backgroundcolor_l35": "#FFFFFF",
        "--e_backgroundcolor_l25": "#FFFFFF",
        "--e_backgroundcolor_l15": "#FFFFFF",
        "--e_backgroundcolor_l5": "#FFFFFF",
        "--e_backgroundcolor_l90": "#FFFFFF",
        "--e_backgroundcolor_l75": "#FFFFFF",
        "--e_backgroundcolor_l10": "#FFFFFF",
        "--e_backgroundcolor_l80": "#FFFFFF",
        "--e_backgroundcolor_l60": "#FFFFFF",
        "--e_backgroundcolor_l40": "#FFFFFF",
        "--e_backgroundcolor_d25": "#BFBFBF",
        "--e_backgroundcolor_d50": "#808080",
        "--e_backgroundcolor_d10": "#E6E6E6",
        "--e_backgroundcolor_d75": "#404040",
        "--e_backgroundcolor_d90": "#191919",
        "--e_backgroundcolor_d5": "#F2F2F2",
        "--e_backgroundcolor_d15": "#D9D9D9",
        "--e_backgroundcolor_d35": "#A6A6A6",
        "--e_color1_l50": "#87D4F5",
        "--e_color1_l35": "#63C7F2",
        "--e_color1_l25": "#4BBFF0",
        "--e_color1_l15": "#32B6EE",
        "--e_color1_l5": "#1AADEC",
        "--e_color1_l90": "#E7F6FD",
        "--e_color1_l75": "#C3EAFA",
        "--e_color1_l10": "#26B2ED",
        "--e_color1_l80": "#CFEEFB",
        "--e_color1_l60": "#9FDDF7",
        "--e_color1_l40": "#6FCCF3",
        "--e_color1_d25": "#0E7EAD",
        "--e_color1_d50": "#095474",
        "--e_color1_d10": "#1197D0",
        "--e_color1_d75": "#052A3A",
        "--e_color1_d90": "#021117",
        "--e_color1_d5": "#129FDC",
        "--e_color1_d15": "#108EC4",
        "--e_color1_d35": "#0C6D96",
        "--e_color2_l50": "#70EAFF",
        "--e_color2_l35": "#45E3FF",
        "--e_color2_l25": "#29DFFF",
        "--e_color2_l15": "#0CDBFF",
        "--e_color2_l5": "#00CBEF",
        "--e_color2_l90": "#E2FBFF",
        "--e_color2_l75": "#B8F4FF",
        "--e_color2_l10": "#00D7FD",
        "--e_color2_l80": "#C6F6FF",
        "--e_color2_l60": "#8DEEFF",
        "--e_color2_l40": "#54E5FF",
        "--e_color2_d25": "#008FA8",
        "--e_color2_d50": "#005F70",
        "--e_color2_d10": "#00ACCA",
        "--e_color2_d75": "#003038",
        "--e_color2_d90": "#001316",
        "--e_color2_d5": "#00B5D5",
        "--e_color2_d15": "#00A2BF",
        "--e_color2_d35": "#007C92",
        "--e_color3_l50": "#8EECDF",
        "--e_color3_l35": "#6CE6D6",
        "--e_color3_l25": "#55E2CF",
        "--e_color3_l15": "#3EDEC9",
        "--e_color3_l5": "#28DAC3",
        "--e_color3_l90": "#E8FBF9",
        "--e_color3_l75": "#C6F5EF",
        "--e_color3_l10": "#33DCC6",
        "--e_color3_l80": "#D2F7F2",
        "--e_color3_l60": "#A4F0E6",
        "--e_color3_l40": "#77E8D9",
        "--e_color3_d25": "#1B9D8C",
        "--e_color3_d50": "#12695D",
        "--e_color3_d10": "#20BCA8",
        "--e_color3_d75": "#09342F",
        "--e_color3_d90": "#041513",
        "--e_color3_d5": "#22C7B1",
        "--e_color3_d15": "#1EB29E",
        "--e_color3_d35": "#178879",
        "--e_color4_l50": "#AAEECA",
        "--e_color4_l35": "#90E9BA",
        "--e_color4_l25": "#7FE6AF",
        "--e_color4_l15": "#6EE2A4",
        "--e_color4_l5": "#5DDF9A",
        "--e_color4_l90": "#EEFCF4",
        "--e_color4_l75": "#D4F7E4",
        "--e_color4_l10": "#66E19F",
        "--e_color4_l80": "#DDF8EA",
        "--e_color4_l60": "#BBF2D4",
        "--e_color4_l40": "#99EBBF",
        "--e_color4_d25": "#26C06E",
        "--e_color4_d50": "#198049",
        "--e_color4_d10": "#3BD884",
        "--e_color4_d75": "#0D4025",
        "--e_color4_d90": "#051A0F",
        "--e_color4_d5": "#48DB8C",
        "--e_color4_d15": "#2ED67C",
        "--e_color4_d35": "#21A65F"
    },
    "theme": {
        "colorList": ["#13A6E5", "#00BDDE", "#24D3BB", "#55DD95"],
        "fontColor": "#333333",
        "backgroundColor": "#FFFFFF",
        "titleColor": "#262626",
        "theme": "#397AF3",
        "nameKey": "Skyblue",
        "name": "Sky Blue",
        "id": "theme1"
    },
    "fileExist": {
        "pageEditor": 1,
        "updateEditorTime": 1787083428,
        "plugin": 0
    },
    "loadingConfig": {
        "loadingBackground": "#323232",
        "loadingCaptionColor": "#DDDDDD",
        "loadingCaption": "",
        "loadingCaptionFontSize": "20",
        "loadingPicture": "",
        "loadingPictureHeight": "150",
        "showLoadingGif": "Yes",
        "loadingVideo": "",
        "loadingDisplayTime": "0",
        "alwaysDoublePageOnMobile": "false",
        "isEncryptionBook": false,
        "isFakeStopBook": 0
    }
};