var htmlConfig = {
    "bookConfig": "v010001103794Ncr8MSqyIQq4CToxHVryHZqyMSr8Her5Mdo5GRj8KdszDYqvDXm9CYh1PbkuFZg7HUm5Bak7OSuuBYoyLQt2Pcp3Pdh6NdkvPdj3Cal4JRiyEdk2GUtuMcgyMXuuKfv4Cdj8Ldt8LXn6Mfp6IZj9HVp2CbowEcrvKSq0KUhwJai2HVvxARs0NYp1FRp2LRqzDbg2NXp3CYu2MbjzCRh1NfszDXrwPbiwLQp3JXk7EQr5IXuuEdv3IQm1LUm9FenxJdquBXp8DerwKUp2IcjvBWm8Ibg3KcpuFTnzLao7KUo6OQj8KZg5KYguFXt4Kbr7Ncl8Hfo6LShzIZo3Mdr7Nev8OYhuFbk1PSk0CTj5DWk6EZmwOYsvKdo7Lbm8JUm8LUvuAVh4Kak5JWl0ORmyBfl3Mek4FdvxBUszOQkuMTguNXq3Mdl2Cao7Ceg9Mcm3Nfl6PSn3CelxKbrzPch7Ldt8ERu1BZq0OUivDfn7EQg4EbpzDQk8Dem1HXowNWp5AXouKWvwFThyBSn3HYm4HZvyDYhvPds4ASt8Kco6Hcj2GRkzFSm7BQk1PTuuMWmzBRt5MZuuPZiuPau7PVhwPVjzHVr8Icq4DQg7ERq1Mbp2Bbv4BZi4HSm8NUs8Cej4DduwJekvLel2NXiwHUswGQmzPZr9IfgzJUg1JXn9GQj2LdmuKepuNeivJbi2Idv2MYt6OYo1Ofp4MVg5HUp1ASuvBVkxNRmwDTq5Fcj1KctyPaj3CWm5ObmyGdr6OYv6CWg6LRk7BWq3Hfk8BYpyMej0FQizLeg5NfowCbu5LZs9FepuPYt5FVg9Ocm2Kci5ATnwAQp9PQv1Gah0MQj8PZo7MdpxLUl9Jcl0Fdm2IejyPWj0ESo7KQhyLSu7MbhyBYh2Edq4GYh1Obk5KRq8AYkuBViwMUp2FUl0CRvvFUt4KXu6KYu8MakuBZs1LVrwGbo7AZv5Ofq3AZj5IRl9HWsxBdk9PWhxMcj2ETpwPYqyGdi3KdkzFVpvHYq7KcrvGZkyGcjxEXjvDVk7MQi3PfnxLQt7GXo4FdkyOZi2MVi4PWhuMYo9ETrvCUoyCWivGTv0FfkyORp3DctwPanzJXi1JZj9Ndk4DTh2AXnyJcm6Eaj7NXu0LWo7Eft5BWuwJRj0KXpyJboyPQt8IVpwCSvvLUvyNdk9OTs7HYu1KSh3Ccu5CUn3Pbi6GWs6Dak8Cen0PWj9GZoxHSnyMUpwNQm3EQtyIcszCTvzIZkvCVn6Pbk7PTi1HVh8AYnzOUpyGfvyLVt0IblzHTrvMSm1Iap8Mdv1FQn7Hcl0Aep1CTq0FTn8KXn2JSo1HbgvDcu6FfrvEZr9OYk4OaivDTm1Mdi7NdqyNYh6OWryOTg5ARl3JYo1FXg2DYixKXuzLci1Ofm9GRj1Hap2GVu3FYnxNQsuLTs2Ads1Mbo8ASsvAVrwBUo4IXivNQnzHeg3EQt6Hfu6NerwAXlzAWr5IUn8ERh1PVowHXk3Abk9NSuyIdo6CXkzIZs7NZl0CdowGSt3IRp2Iem8JUv4Cdg0HUrzAcg3FVi6CZn0JXq1DZl0PctyFTv3GVm2HVl1CXl9Cbv7Ebk1Eav9Mbt5Ldq4KYo1GXq3EfpuJZt2GQp4Eej7EelzJSh5FZq5OYluAbh2GTlwCYpxLSr1AZvvMcjvKdtvBbvwFflvAek3PdkvIWs0CZkwLQt8GZr3LWtwBRn6GfvuHUouDeiwHchxIfi5KcoyGcn4Hei7GXo1NXjuBWivOZv7Hcg7MejxGan7EZq9CTh8NenyBVgzNQp6PUruBct6Kdr1OUq3MfgyAUmvGZrwMUg2Hcr5IUj7PQi9Kfv3GXi5HdlwJZq7Per3FRt7JXv7Hau7JfvvBbm4DQq0Oai5NZm7DVj7PQr2DTnvBVh6Ecv5Cbh9BWn2AckuFai2MWo7JXnyNYhzKct3PSg3KQs6DYuwFfmyCcj2Kcj7LYt9OUs3NRqvLeu3AcnwAZi3FWv1Pek5EUi2CctxLeiuLbj8Ldg2FQs0GWm3IXtyCbguKZryBQovHasuFYkwDZi8Lfh0BTrwORlwGSv1FZgyAVlxOal9HQh9GYv8GVgyOfovGTm4JSq2OVs1IQuyOav6JXp1Cbp3BftyGfk9BRquIek7AUr8EThwCQm6GUn8GRgxAbjxHSlvKblxMcr7KQuzPXr2HQg8FUl5AQpuEfv1FYoyDbr5ISo7BTpuNZt3Icm2LdvwGTj3PQjxBdm0PUnuMYr3IVt8BbmzKXgzIVkwMflvBVi7LSh4KRt3KUg2AanxIav4PYo7BUryMTgxHYm2GatzDVgyCYm7Oem5Gbq1PXuxGTg0HZg5IVkwDct5LTqwKWnyIUsvARk9BTr1Ndm4IdnyHWo0Kfv5JdmwEWv5GfuwOWguOWn0IVg2JTnuIWu1NTh2Oar6GTi5HXkwDYuxJWp2Cfk5MZm5PbluDVj1OVh5KSh0Ocu4IZg2KevzMVg3JTquFYizHdg8BQh3PVp4BRu9HXh9Ech3MYn5MakyBcr4Dcq3HQq0HRmxNRl4MWgyCTgxNUhyIdv7Gdj1Fdi5CcizLcj7Bet8PbtuHSi7LXn6Kep5Lfl0JUuvNag4KZuzLRr6BVu9DTi0LYr7IQr4GUo9LXt6LRo5AYkzNWj8PUq5Dep8NRh2KcpxBej3Ocn8GSm5LVk9LRh3DVh2IVp8KWg9OXrwOWgxKQuzLbg8JVq8Naq7JYtwLav8LajxAWj7BRi2NXn0ATg0MZgyGfv8Edp0Obg3NRtxKdu6NdgzIUm1Kbq1Hdq1BVp5MQq6ITiyJYh1NSq5HdkuIXm2JVr9AUo9Ibo2JWp8Odn9Lcp5IZkxJYjyOZnyAVo0Afv8OWs2DUn7LWhuIZqzKfv0DVi3LVuzPUq0NSpyLdn5IUrvKVsxOXk8AbruAch1HTh8NRiuEbu2DcqwGZnxLRu5Gep7Eev8Eap0FSmyPVtyLWk4DTp6Hbs1IWh6FZvwPYo2FQo0CTh2Ian3Jek6Jdn8Ifs4IZq8Afv7Lek6GctuPYm5BWmzEdk1DWt4PTqvCSpyBdn1EQozJSv1BTt4JchxEajxLeu9GeuuKQq3EXgxNSt3FSh3LQqxEbpzASu2EYp3KTk7Fdq9PVt9KYvxEdo7PQryOSn3Bbt4KYq8FVmyOds0JZizEbp1PRv3ERp0Jar7Ncp3Mem9OaguKcj8PXt0Dbj1IUsuDWl1Ncp2KduyPWp9KTu3AbsyGXt3Kbv6EXjuHSt4FUnuBVj0CfsuNehxNQruIRl9FdkxJes9Jbq6DTqyLRo6Abj6IZnuAYvvPdoxPYmwDbn5DbkxBTs4BUozOQk3NXn5AWivPSiuIRs6FYmxETiuBUg6DRl6Mal2KWk5Gai1FUo1IWp4Acp8MXqyAcpzFft7MSk5Odo2BXpuAXuxOcr5Oet0Gcq5HVn2Caj7NZj4KUo8EYg9PWluEVi2Pbk5JQt8Ibv9Gcu7LQlvFbtyPcv9KUmxOemxJTv3MYhuFeo5Fbt1BZswAZguIVq3OZt7AQu9Lfp8FfszGRi4HakxLSi1GcguOUo7DdtyBWu0EZvuNXuuCWm1GTjwJcv6HWu4HXswLQs4Ebm2FarwJRmyGXg7FUq1CctvFetyCWiuJVt1KVozJYn7DYvzDbtvBYn4Fek4Efu3JUs1ARsuOZvxHWlzGan4IUk0JcguDVg3Hbi7CRqwATr0CQo8PTm7BSv5EQr7NVo8JTnuLUh0KZn4CSuuBZmvEcl4Ler0BUozNQrvDcg3Adt9NUh0JWouLRuwDcn5JRi0CRp5Mat6GduxAXkwCcv1Gft7MUt0JWo6MUh0KYv7FZguAej5JXtwAXtxIeo1EXv7Ndm1LSm5LTv3BSu4FYj3Kcs5BWrvIZj5LVoxEWp0MQqwFeg1GamzPfnzEXvzNTmwFem3JUl3Gbh0Afq9BWl1DfqyKfo6FZt1Cah4LRq9BRo9Pfs3ARp7Pbl5PXr7GVk1OQq5Cfi0Pci8DVmvLag0JTs2LbnwFRvzHfh0FYq1CTg7LQgwDWh9Abi3GXh3Paj8Ift1ITtvLUg0PerwJWl0KQtyHYu0PYq7Gcl0OYl3JZtwLWrxEcgxOSrzCfkvDRiwKWp3GdgyEdu9IYl8MfqzIfiwGcr3NRk6GXv4LQh3ISo5LVp2GZq5GVhyAfmzAbk5NSm7JUo5DWrvNau0JTq7IboyGXj0EUkzHQruFSlxOfs1BSk9Obj1MTmxMVh1Bfs3GWh2HcjwKdtyJSiwHXk7FYjyPbnxHWozJdj6PauzMbo6HTl4GbtxCShwBbq1Ees6AZk6AWr6FdtzFWg2CVg8MYj5HYg2PYl1LfmvPYl8AYq5Hfi5LZmxPamzPdguBTs2GTjuJWq0Ocs5HTlzGbj8EYm7PQrwFeqvDbt8Lar7HaswBcl2BVq4HbrxNbr5Dav2CVp6PSr5PWt8FTo5BSiuGes7Pcp3Aap2BQmwGXquOesyIeh5GUo2NQn2JegyDZj2Ibu0ESouFSo2KZszORn0MXh4Ceh3LQn0PZo8FVh6JZu3AZswLfr4PQtwKRg4CRkuFcq8JRhvNVrwAbswBXryPcnwBTl7JQqzMbhyHXrwDVluFWr3MVr9DVpwDVgzDbm1GdiwFTvuFVg3OYs0BepvBdi6Dbu6PXvzJXq5OTl2KTp3AYl1GSg0PRuuGXj7Cam3IZhxBckzObo4Nct4EdrwObpuCZo6Idr4LTv2EbouCZv8HVl7EbhwASjwMQvxGUixNeu3KQnvKft8Dcu2PalxDQh0NSmxEWjvLSl9MXg8PVo4Lek3AVi6IVovNbsxKcj6AZg1AUr0OXg9HRg0NUt7EbizPci4GUj9AUo7GcnzNbjwNYk5NSv3Meo8GXruGYm2EZovHfp3KSnzORu9HYnvAWnyKdr8DWi6AYo7AZnyEZizCRoxDVhxAco4Kan1NYo5JVg7LVsvOZpyLQl9PRjvAeg0BRt2FUm4EYpzPXj8PdrzMen1HavwCbnyLZg1PdlxJcu5DVqyJcs9Mbm0Kcv1IQh6FfsyKaqyDYp1LZg7Eaq9Oft0CQozMbt6ERq0KejyMcv2Dfu9LVgvJYmzJVjxFXo9IUj4KVpwBZsvBYnzGRt7MYg2Heq7AXjyEQouDWm0FbvzDRn8JSl1PahwLfl2LUsuHXk9Hcq7Dfr1MSkzGVtwFfguMYnzGRo6EUpuJUkwKco6FXuyLVm5NdgvBXuuEdn7CVnzMSixNSu4GVk5CZt0GVuuIfgvLbszNclzPbs5HYhxPcnxKXv8IWuwKWh0EXuwFdn8FWp1OXr3GYt8OUtvNeiyCUsuCWr9DTt9Ham5KQq5AesuDZg7LQuyKSs5AWg2ERs5ITk1Jdk9Bbv4Jco5Aft4DQsxHYu2LZp4Oek9CTiyAbs0GQn4Gdj5NZq7EflyIas3IRs1ASr5Aej1JeqyIYnyLchyMSm0Pav4IQp9LWn2OSl1OXvvHUj8MQi5BTm2OdruMag1MZhvPagvMVj3JcmxPZv1Dem8MUiwHUrxCTu9Fbq4OUvyIXo2NUruKZg9FZo6CTg4BWu8BQt8EZq8CQg3Oeg4MWs0Lfg0JUr7HZi6IZjwEdg4HYoyHYhvATh2ISq5GaquPVj1EUuzCUm1EWg5Jcj3DSm0JVk5IbvxCZtwJXo0AZj2Feq8DdqxKao7FZmuHUr2JdizOWh3DSt5EXjwBTjuPah6JVm0Dbr6JQl5OQq0GXsvLViwHVi5DRi2HVluKUpvAYvvHYg5Ifh3CVrwEalzGUkyGbs0GRlvHaj9Gds1LRj8Fft6OUg8PWi5Lco4Mav1DegxPfn0LYv2Kbt7HXo5OYo7ASg6HWn1Mfr6CZo1Gel8Jeh4FRp0FZq8MRiyDYo1CXk8KfowLYk7LXo5KXsxPVt4ATq7Ebj4KRt7DVn7Kbp1Pcp2DYqwFej9Ffl6Bfk3Kfj9Fdu0BVg8Feo4MUk8OUg8DXgvMcq4KQtwJciwNUmuBSpvPct8LYguDYvyJSv2DQvuDfhuMdmzKSquKegvLVr3LYi8IakwIejyDdu7DTvyDSj9IWswGehuITswLbu8MVuvJVq9Acu2NZi2KZnuBfr4JZk8Ffv0FUs7KRkvCcsxOTg9Fbt2NTi8PQq9PSv1Ncv7Gbg7BXh1PYv7CYu1FVpwHUmzKdj8JWq6CRl8BQtvNWiuITtvBVt4AWr3Lcr3KUj5AWkzFXjwJanuPXm1GXt1DTk5AbmwASr3CXm3PenuNUu6CVj7KSi4IUp4HYlxGSkzDYjwPfmxHbt0PSu3FagyDYsyHXiwFYgvMXnyMbv8MWh9OdlvBSt9CSnvLWs2IXiwAbhwCXk4Hbv2PfiyIZh9Ofo6CRmyDXmuGci7HWq4EbgzOTj0JTl2FZtwMdl9MZsvBdh0DXt0Ebh2CTr5FUguNbj2AWp1Hfu4Cek0AWv3PXk2AWg9DQmzPTg7HYjxOZj1Fbj9LerxDVhxMQj7GdiwBUl4EUkwLTm2LfrxAdm5CQl0CYlxBbqzLdt3Lfr4EamzKZu1EXryFUi7Aej4Pch4DQq3LUiwLXv1JVv7ESsvMTluMZgvEWpvFfi7KbvvNSjyOcrzLVg9IVv1MRlyOYv0IfrxNZq9JYsvGUi8LdrxKXoyBTsvNcs4BQrwHWs1ATl1MXk1AVq2CVlwMek1BZuyCbk3Och4BYgxAbi3BfsyFci3Adi0MUl0GWs5HUg2KRq1DQhyKbm5Aeh2OcrwKQuxBfm2NRr1OfsyIYruHfl7NZh0CQn7DVvyHTi6KQj3PTq8IfuuPTu3JdlxNTk0Ifq5HWgxHWivJetuJbt2PTrvLas6EamyPbp8OUqvERpwDVizKTp0Dbp2CesuKcr3BXl2Gbu0BZruOfluNRjwEZv6NcuvPch3KZn5LVj6IZtzMQoxERu8NQlxNdv2OVo6Pas2HVm4FTu6GVowIXlyJQj6BRo6LcpyIek0Ofr4IRjxDRnzDet6Mdm7PVs1OZsuDeq4CRj4OatwATn1DdvzLSv6IauwAbp0OQovMfq3Aeo6EamwOUq9LWu4Jcm7LUivEdpyIXu2IUv7Ieo7PYp3Pep5KchzJQr8Fbk5OVl8Jfk8MUq3LYi1DZs6GftvGQrzEUl2BVvwOTh3OYguMXvuCSn2BRi6ISi0BamwPfk7JVp9BSo7PVkuAVn9LWguBcl6HWm4DcnyARo3Jdj2Adk7DbqvGWg3MZgxNZh2Lci9DaozNan1Gcs8OZj9MdqyEev5PdvyOVi8HTu0GZrzJcuxAahuAXmvGZl3PZrzMcr3LVv6BXi0Meg6OSi4Cbj0NbovLSq0BVuvGTv4BQozHXu9PVt1Gbk9AavzHXg8NYs0KWr8Keq5CbtyATr2DTu9Hfq1CejzISozKVgvEZr9KQi0NSj4HZq8EQi2Dbp8HavxKQh6Icu2KdlwLelxDTn7CTk5CZswDUv6OQiyGdm9DahxBVm9Ceg7IUm8BRq6NbqyAft3ERj3NWh8BRhwNbk4OUt6Bft4Ofu6DZk1NVk8JQl3CchwMbn1HarzPYn5HYivASv6KZs4IalvGcv4BVo8DXo0IZnuMYv0MVqxBbq7Dbs5KfrzCah5IdkzKequEal8Ifm0PUu3BalzOTpvFYi2JRtxEbq0NRj9MXtwESt0KSvvCcq7PfgwCSh2HWsxBUq2JXguBVrwBVp6ITsuJfm6DXs0OWt1JWs5CWk4Aes2MbrvCTh1Mdp9JWq9OYp7GTt2PRrxLXh2Nfg7DSg4DarzNcsyBYq6DfkzAXt7Ddi4CRv4Ffk8AarxGSq5Icj4CVm6NZm5OajxOdk3ISo7Ban6Hev5FQiyBZg7Mdh5Deu9Ddg0MYhuCWpyDYh1NRt5KZs6BUvvNRi4HTlxDbl5BSp3JZi0PUgvFcr7MQq8AbjwLeq9NVh0NTl2CZj7ORlvMWtzDVm4Mdi4NZsuMYhyAYlvJSuxPcvwCRi5BUhuLRp2PXv2ISs3JQiuKWruFZuzNblzGfpvKWu0Nbh7NZl5LdlvNXpxLci0DZkuEam9CWizIbg9EVmvOYn6EQn5Hdk8JZs1PdpzFch9PVr8DQi9GSv9JUuzGSpvLbr4BUhxEZjxCcp5JXj4EUt5HVi5EdrxDes5IZqvAfq7NWi9DTv5FRuwLRmvKan8Fas4GXo0HbpuDWs6NXkxGdgzBRu6NThwHZs9ERjwDYi6CWm8Jbk9IUvxKUj5DSnxFZo1Ddn5NTjzJfsvIVh8JRkzMTiyLQpxOQt7KYn1Oes7LYn5NSpwCdv6Nem8Fbh1HWn9PQrxGTgvPQj7JXh2Aan6JVrwCSn5EVk3JQm7PTm3LUhvLbtzERj5KWh4DTn9Cer9NTswGcn7Ift0Ndo9HWmuHesyPcvvHTg7KfhyMXrwOTi0HUvyHUn1FYnvFSo5JckyGZh8JWk8KWv2IRrvFfiwJWtxBShyMfp9Cdi4BSl6NRs0DWowLdj7AWs2OYsxOXo8Hfu9CUn8DTo6BZr3JTq4OQk1OVrzAaq9Iej4CZg4ATq4JXm3PfowIapvKTu8DdqwGYr4GYv9GTo2DekvMet1Bcm2CQp7GXi9Jbh1Jel2PdsvMTk0Pbh4Ech9PXi9HWm2Hfr4JbluNVj7GUl0OWhyEQvwDcj8JVr0JUu5NRiuFTh2Leu6LVqzNVtwKQi1KTr2MSj1NXh0KXh8HXr7BdivGfg4JflxKZk3EXg9MRj5IQozDXp5Obj4Ocm8BXo2ISt5NUq0KbhvBbhvBcuuMZjyIVg5Cdq4Mcu9CSm8JXnvIag6FWp4HdiwJWk8NRh2MZv0OZnwDXk4Fdg0Hft4DVl4BUo1Kfk0IZq0PVr9IVj3HXl6LUhzKah9KSpwNbq3GUtvGSg7Kbo8JSp9NeovETv8OSs8PVt6BVm5AWhzBSsvFetzEXvyMbo0ERm2NZpuNYlwEYmwGbhyEfk2GQtvHTi0CTgxPfv7PXkxKXu5MRtwDQhyARm9CdgzLdu0FRhvHas4NUn5KarwIRn3JYl2EXhyMdt4DUhyCct0GbozDWjuPZsyFZl2LYm6Ebu5JUl8MYsyCXoxNVq5Mcu2JRh8BduwOejwCdr3Pfu8DaoxCev3GVq3NStuDcr2DRr9Paq6Bau1Dcv1IYm0IZgvLSk9MepxAQo7MZryMdi3JRq0Kfm5Lct9LSuyMZl2ITh5Mfn5KQg4Obj8DSh1Afm9MTn3LXk6LYixLZt7NSgxOXr7KTguGQs4Gep0CVp9FbgvGTm4EQr3BckzPQm0Ndm3JQg5JRlzCbj1AakvJdtwNem9LWl7PSo6CdvyJVg9GQs9Kfo5KeuuAYkuMQpzHdq4Gao4LRhyPbpuHcr8Efg7KdtxMUhxDdnxGWl3NUr2KXpxNUjyDRmwCcnvFUv4Nfi0Kbs3LVgyMajuHUo5NWu6Den2OTk7OblvMcuyFdh4Mbj4DYvuNXp6ATg3AZgxGZk5AWu1DUs4Mdt5CYhwIZkyGRk3HSi7DQvyBao2FQt8Jdl0OWh3PRvyDTtvEQuuGRo0Fbn2IakxKYhvDYtzBYtvHZk0CVs4JTizLfvxCWgzPQgvNcr5JcgyBVq1PTj4DegyBZi2GZv1JWp6BVl6FSkuJSlwJRv8NVg9DSuyKVr8MZnuMap7EZruBWmwHWrxCeu8ORs3HftvDdiyKYq2MTuyIau6Ndv9NUv2KbryLem8GRv4LeuvNRrwNbjzIet3LRmzGVg6LQn6AZm7Gao8BXhzGWvyNXsyNQp4JTqvKbu1NUl8IfkyLTn4EYt5Eak2IagzKcn9IXm9HQquHdryKauyMcs4Gfn5AVpxGWp9Hdq1PfovKZoxBToyPUmxObg4NQo1BWm6KQv4PdoyHRuzCYs7Das6BfvxMaj2EYt4BZovLVm5Abj9LWhyJZu7LUuxIcv2KWmzLcq6LZu0NdjvJWm1JQq4KUt1Pfk3CRixAZixNbozPTvvBQlxFck2DStxCYnyGcv3CWpwCWr7PSlxCdu4Afr0IcgvKfh6NThuAfp9OYmyMSk0OSh7Cam0CVh7EXlwPfuyNbiyHSp3Mbn1GZr7BUn1EVg6Kdh4AWpuFYtyOeh4LWi9PZnwIVj2EQo5JepxOWs1Cek6CSn1Cds1Gbi9BUs6FUs8Kcj5NXg0MfjwKTs8JQs6ITq4FYowOeuvHYpzKRs3OdnwOSu3Nei4BblvMcuyLRj2OSn8MVu0JSp4Maq8Ofg4GfhwGSj8BQr5NSv6Oep4HYh5NamwIcg5OWh8Jfm6LZtwLZq7BfgyMZj8Oeq0BavwEdq0FSruPVsuLeo7Ffs5NWl4DeovKdr9KYouASj7Oet2DUluDQt3JXlxAdizHYi0GapwPTl7LYgzOZnzISk9CYj1FYr9ORg3Lcq8Icp2DRsuPZkwOar3LZq1BZq2NZm7HcqxEdnwEcpuGdn4Pdu0KRhyESgwBTs9LTi2PcswNUo6Bfo1Ddm1MTp3OVuxHZk6GXgwKWp0MTr2LVrvPVh0Gfk0GSu7GYvwGTh4Ean9Pek4OftxDWjzASi1OYn9OeuuDboyLRjuPfg7DXgxFVq9CcvyKZs6JSl6Nbj7Fcn6IYr0DUswEUpzHYj5FRp3OUj5JbszKZj5Bag5AWi0OXlxAZuxJZizJfh5KeqzBXl2JTq1KbgzPUl8LXo6Aaj2Hcg0Obv2EVo6NRk3BTj6LXgyFZnyDbr4Eaq0GTrxPdj8GUtuCfhuNfmzIYk6MRquHVpwIVl4FXjvLUvyLcu4Bbs6HYt3Gep1Kbg3Gep3ERg1EYn6NXm6GTp3MUuuBelyLSm6JQgyPXvyIegxFVj7IXv4DXn6Jao5GWq1DSlwORkvPRu4EXkzOQquDXi4Maj6CZt3GVk7HXl5HUv5CVpvNZm6NfixBWt8BSv8Ldh5Lai3NTp4MfmwOVouIfmuPbnxMZsuPZuvHTjxGbj4EXmvBQtwNau7Bdq8HXo7MesvBWn9PRm5DTu3OSg6PWq8BRt3GZn5KeswEfuvMUgvKUh0Ieh6AQq6FWnvIdtvIcrvCQm8HQl0LbozJQpvPTl7Jau1ATj6LSlyHYn9EWn5Fbv1CRl6Pao0IRh6AUu7KXsyARivCXt4AVj9DdmyMcpvJakwAWi0Hen0EUs9ObjyCXlwNTouAbi7MZl2Fbu3DYv4Kcv2MTvzDTszJXiuPdjwAQj7LTmzJSh5Jdt7DYkwJQv0KQo9Geh1JVq6CZl7Jeo2LRi3LTs9NRl7PZt1JTvwLTuwCZu1BRh1BVk2PZi4BapuNXl6ETo8KZu1KXq6Jep0ISr7DZpuLVk9MamyIYn2IThyIXv5DQr6DQr1CQt7OYuuAXuvJRswKSv4Kdp8BZgwDXs6Hdg4MelxLZnwMZj4PbhvFalxMQj2NSh4DXh8Feq0GXuvEYoxFYs3OYo8Cek3PUszHcvwKbtvLZo8CSpzISl0NWj7Ndu2Gft9Gfr0IYj2GSs2MbpuERs2BesyFZmwPYg3Ffh1IRmzFTmwOasuHUh0GVr6DVh9Dak8Kcv8BRvvIcgzJanwKfvuFQg6PUj4PQsyNVsxAUmyOYg8Cbl6FWrxEVvuNbs9Adp0Pcq5FRqvNYjyLdpuPfnwPWgyMVh8Eam6LbsvKQkvIZh6NRm8EVmzCcv3EemvISm3IUhwMQhvPRquBRg3KUj1PQnuMVt9Kdk9AVv3IehwFal8PQpzIYizPalwMRiyPYuzPQi7DatwLWvuIfpvLYk9OcnxIcr4FYqxFYk2Baq7OQt7FYs9DVh7AZv3JVhyIQh3DXm5CWo7PVlzNQovEYh6OZm2Edo9JUl4LSo2BZhvEQi0Oaj8IWsxNTgxFfvxOci7MRg1Jbn4IQn3LXn3Par4ARp9MRt2DXpvOdl7CYvwJaoyOdt1LYs1BXnyOfu0KSmvJeo4AUrvIds2LRr7KTr0NQg8DQizEXq1JTm6CQs2Gas8GZlwBSn4EVk1LXt0Ifp7Jfk3ASu0JVsyAZo3PapzEQj0BZt0PTtwPbn5MXq3Ofl5MUr8Fcm3JRmyPcq6KVk7HYr5HRq3FYl0IYq0EYj0PSr9AYvyPQv5Fbk8DfmyFTnwOVvyFSo5DSi4MXi5FZs4OTiwFUhuHUr2JTj9Ocj7DejuEctxOUv2OXt0KTk4BXqzKeq0BenvHbgvFZn4PWj8KTrwKfuyIdm6PZrvIQlvKSk7LUpxBbuuDav2DVt3Gdr3KWp6LUvyNRqzLRg5JVi4Pcv5NSuzIXqvCSr9Pah2Afo1Pbq4Bcs1EXt8OZs8FcixLRp5ERu0NUovJftyAVhuBZowFdj9Hbg1BSg8BSkuMak5Edk9Ibn8LWszHauyPVj4HQs5KZs0LeozCVswGarzGaoxHbj8DWruMdv4GTluDVuxCdvzEfkxNek9DdkuHVu9JatzMRj1OWi2PcruEcjwPbmzETn8PfpwPfk7IVm0ERn5Afq9HVo2CXp4Ibm3IagxAfu5DSv2IfoyBRn6FQi9Ial4Pbi1LYmvDZl1DWu7MRr2EYp1FbhzAXu4AYvuJauwPchyNfouDdt2BSpuNft3ARlzIai0FYnwCRo9LRi6HRm4OSr3OYv0DRjwBVh0Idq8EWt6CShxBWq6Ket0Gat0KWmyCZu6LQiyMdmuLQm0KdnxJfo2Eeu7Iej5OQk8Oev2ERj2HXs8NQq9NZm2ORmwBWt0PZv5Nah0GckxKSu0EZtyEQkxDQiuEZmuMWr6OXs7FXh5NRm8IZk3Ofu0KQp2HRu4EZv9HejyOVkyKfk9OVj5MXq1EYuyJdl6AYs9DVh4HZmyIamxGTrzHUmyKbi7JWj1LRl8KWlwIYu5HZq9HVnvHapzNZlxHRo8KYq7OSl2Dfr7CQi3HVh0Hap2AUpxEdozKep5IXq6KfoxKQjzDUszJYs7OWl0KWu3KasyPcjwKduvMbuwAVh1FSjyGal5Aau5CXh4JRp1KUluGQv5OWt4NSr4PTk2IQkuDUivPam1FYk4Ldq0CSnvFdhyKUv4PTiuNZtzHQo7MVi1Edu7Dfl4JQp8MZpzNYluJXl4MUgvCToxDYu4MQr9KWryOWp5IZg2EXizASi0CdozIYh5BduvOYj5EbqxNWu4LVr8AWvzPej1PXm3Abm9GQr0CWq6Gfi2Edq3OYu5KYryCflyCZuvHSu1Deo7JVn7JVqwMbr2MSpvOVj3GRj5ETr5JVlwFdi6HTk5NcgyMVk0DfuvHXg8IaowPTi3GUrwHVl5Pfj0CVu3Feh8OZv3AVv2EXm2DVhuLUtuLUl7LZpzHXm1Neu6Lfl8OXgzDdouBUuzLWuuFTnvAZn3PRr7LYi7Nbj5KRt9AdiwNcq1PamvJSt4Abj2BahxLYn8LTmzNbi7GeguEZqyGcjuDfn5DdnxKTq4IWi8ARt8JYt5Cdt3PRi7NSk6DXhvFflzJYguDSv8Baj0BUm2Cap1Cer6Oeg7GYl5Han5Hdg0MWivOWk6McgvAbvyBfl6KWtvJTs8KTnxAck5Baq6JSiwAcmzOXh1CcqyLQt7OWhwPZv2Aaq5AUs5BYm8JWl6GWowBRs6Pei0LXjzESt8Oei0CSi9Ddt6GSs6OWl6JcqvGWm5Geu2KUp7CWp8Gfh8NSv4Icp2DUsxJRt4DZr6IWiuHYtwKVv2ATgvMcv6HQvzNSmvIcquGei9BVnzPZluNcq5ORl0BVo1OZqyBXpzNSlzPZl0EVv9JeguBRhvHcj9KZrvGWt0KWi8EXh2Ifl5CfuwPVq9Mfj1Mcj4Fcq6KUhyFWs7Abv0BfjzAZo9GdkvFZguNVs2BbkzJViwGUmwLQp6CQi1DTu3BQp3AdryJep5CfjyBQszFXrzIZrzBYguNfovDWm7DWu5BbmyBej7AVi2KchzGSg4JZouDYluOUnxFYgxNfu0Dbl8OerwMbp2Jbl1ERozGQn5EZnuCcsvObp3IQj9Oao4Pfv7EWk0JZp2LetyLRl3Hev1EXsxORu3Gdv5ETp7PTmvCavzMTi7PRhyFXo9BYi7NYh8Peq8NQluESo8GTm7PSv0JXk8DSp1FVu1DavuLWt4JQg0OZhwEdjxPfl8Jei7LWq8JTu6MVk0ITg5CSiwKfqwLRn9Her0Adh1ATk0NamzETn0EdkwCTt4Fdq7NZr6AcjuMQm3LWgxMWvwFRj6BctzJSouNem6Let7FaqwHXs9Hfo0OTkzOTi6Gdt2KXnzMQp8BYk5Faq3DfjyOat5DWkvMSu9AdjwMTj3CQizJQs3AelyLRu3BVg9HaFan1Gem2FSn0Han5GXl0DSlzg8020ca2406306bc082ecdbc95e1e35c0520",
    "aliasConfig": {
        "appName": ["", "", ""],
        "totalPageCount": [],
        "largePageWidth": [],
        "largePageHeight": [],
        "normalPath": [],
        "largePath": [],
        "thumbPath": [],
        "ToolBarsSettings": [],
        "TitleBar": [],
        "appLogoIcon": ["appLogoIcon"],
        "appLogoLinkURL": ["appLogoLinkURL"],
        "bookTitle": [],
        "bookDescription": [],
        "ButtonsBar": [],
        "ShareButton": [],
        "ShareButtonVisible": ["socialShareButtonVisible"],
        "ThumbnailsButton": [],
        "ThumbnailsButtonVisible": ["enableThumbnail"],
        "ZoomButton": [],
        "ZoomButtonVisible": ["enableZoomIn"],
        "FlashDisplaySettings": [],
        "MainBgConfig": [],
        "bgBeginColor": ["bgBeginColor"],
        "bgEndColor": ["bgEndColor"],
        "bgMRotation": ["bgMRotation"],
        "backGroundImgURL": ["mainbgImgUrl", "innerMainbgImgUrl"],
        "pageBackgroundColor": ["pageBackgroundColor"],
        "flipshortcutbutton": [],
        "BookMargins": [],
        "topMargin": [],
        "bottomMargin": [],
        "leftMargin": [],
        "rightMargin": [],
        "HTMLControlSettings": [],
        "linkconfig": [],
        "LinkDownColor": ["linkOverColor"],
        "LinkAlpha": ["linkOverColorAlpha"],
        "OpenWindow": ["linkOpenedWindow"],
        "searchColor": [],
        "searchAlpha": [],
        "SearchButtonVisible": ["searchButtonVisible"],
        "productName": [],
        "homePage": [],
        "enableAutoPlay": ["autoPlayAutoStart"],
        "autoPlayDuration": ["autoPlayDuration"],
        "autoPlayLoopCount": ["autoPlayLoopCount"],
        "BookMarkButtonVisible": [],
        "googleAnalyticsID": ["googleAnalyticsID"],
        "OriginPageIndex": [],
        "HardPageEnable": ["isHardCover"],
        "UIBaseURL": [],
        "RightToLeft": ["isRightToLeft"],
        "LeftShadowWidth": ["leftPageShadowWidth"],
        "LeftShadowAlpha": ["pageShadowAlpha"],
        "RightShadowWidth": ["rightPageShadowWidth"],
        "RightShadowAlpha": ["pageShadowAlpha"],
        "ShortcutButtonHeight": [],
        "ShortcutButtonWidth": [],
        "AutoPlayButtonVisible": ["enableAutoPlay"],
        "DownloadButtonVisible": ["enableDownload"],
        "DownloadURL": ["downloadURL"],
        "HomeButtonVisible": ["homeButtonVisible"],
        "HomeURL": ["btnHomeURL"],
        "BackgroundSoundURL": ["bacgroundSoundURL"],
        "PrintButtonVisible": ["enablePrint"],
        "toolbarColor": ["mainColor", "barColor"],
        "loadingBackground": ["mainColor", "barColor"],
        "BackgroundSoundButtonVisible": ["enableFlipSound"],
        "FlipSound": ["enableFlipSound"],
        "MiniStyle": ["userSmallMode"],
        "retainBookCenter": ["moveFlipBookToCenter"],
        "totalPagesCaption": ["totalPageNumberCaptionStr"],
        "pageNumberCaption": ["pageIndexCaptionStrs"]
    },
    "aliasLanguage": {
        "frmPrintbtn": ["frmPrintCaption"],
        "frmPrintall": ["frmPrintPrintAll"],
        "frmPrintcurrent": ["frmPrintPrintCurrentPage"],
        "frmPrintRange": ["frmPrintPrintRange"],
        "frmPrintexample": ["frmPrintExampleCaption"],
        "btnLanguage": ["btnSwicthLanguage"],
        "btnTableOfContent": ["btnBookMark"],
        "btnExitFullscreen": ["btnDisableFullScreen"],
        "btnFullscreen": ["btnFullScreen"],
        "btnHome": ["homebtnHelp"],
        "btnMore": ["btnMoreOptionsLeft"],
        "frmToc": ["btnBookMark"],
        "frmSearch": ["btnSearch"],
        "frmLinkLabel": ["lblLink"]
    },
    "meta": {
        "htmlTemplate": "Popular",
        "theme": "Default",
        "title": "Menu Brothers - Final CMYK",
        "description": "",
        "url": "https:\/\/online.fliphtml5.com\/hbozp\/onfk\/index.html",
        "pageCount": 24,
        "pageWidth": 612,
        "pageHeight": 792,
        "template": "Popular"
    },
    "project-config": [],
    "bmtConfig": {
        "tabs": [],
        "onSideEdge": false,
        "hasTexture": false
    },
    "videoList": [],
    "staticAd": {
        "haveAd": false,
        "bgColor": "#000",
        "bgOpacity": 1,
        "interval": 0,
        "adPosition": 0,
        "data": []
    },
    "language": [{
        "language": "English",
        "btnFirstPage": "First",
        "btnNextPage": "Next Page",
        "btnLastPage": "Last",
        "btnPrePage": "Previous Page",
        "btnDownload": "Download",
        "btnPrint": "Print",
        "btnSearch": "Search",
        "btnClearSearch": "Clear",
        "frmSearchPrompt": "Enter key to search.",
        "btnBookMark": "Table of content",
        "btnHelp": "Help",
        "btnHome": "Home",
        "btnFullscreen": "Fullscreen",
        "btnSoundOn": "Sound On",
        "btnSoundOff": "Sound Off",
        "btnShareEmail": "Email",
        "btnSocialShare": "Social Share",
        "btnZoomIn": "Zoom In",
        "btnZoomOut": "Zoom Out",
        "btnDragToMove": "Move by mouse drag",
        "btnAutoFlip": "Auto Flip",
        "btnStopAutoFlip": "Stop Auto Flip",
        "btnGoToHome": "Return Home",
        "frmHelpCaption": "Help",
        "frmHelpTip1": "Double click to zoom in or out",
        "frmHelpTip2": "Drag the page corner to view",
        "frmPrintCaption": "Print",
        "frmPrintBtnCaption": "Print",
        "frmPrintPreparePage": "Preparing Page:",
        "frmPrintPrintFailed": "Print Failed:",
        "pnlSearchInputInvalid": "The search text is too short.",
        "loginCaption": "Login",
        "loginInvalidPassword": "Not a valid password!",
        "loginPasswordLabel": "Password:",
        "loginBtnLogin": "Login",
        "loginBtnCancel": "Cancel",
        "btnThumb": "Thumbnails",
        "lblPages": "Pages:",
        "lblPagesFound": "Pages:",
        "lblPageIndex": "Page",
        "btnAbout": "About",
        "frnAboutCaption": "About & Contact",
        "btnSinglePage": "Single Page",
        "btnDoublePage": "Double Page",
        "tipChangeLanguage": "Please select a language below...",
        "btnMoreOptionsRight": "More Options",
        "btnFit": "Fit Window",
        "smallModeCaption": "Click to view in fullscreen",
        "btnAddAnnotation": "Add Annotations",
        "btnAnnotation": "Annotations",
        "FlipPageEditor_SaveAndExit": "Save and Exit",
        "FlipPageEditor_Exit": "Exit",
        "DrawToolWindow_Redo": "Redo",
        "DrawToolWindow_Undo": "Undo",
        "DrawToolWindow_Clear": "Clear",
        "DrawToolWindow_Brush": "Brush",
        "DrawToolWindow_Width": "Width",
        "DrawToolWindow_Alpha": "Alpha",
        "DrawToolWindow_Color": "Color",
        "DrawToolWindow_Eraser": "Eraser",
        "DrawToolWindow_Rectangular": "Rectangular",
        "DrawToolWindow_Ellipse": "Ellipse",
        "TStuff_BorderWidth": "Border Width",
        "TStuff_BorderAlph": "Border Alpha",
        "TStuff_BorderColor": "Border Color",
        "DrawToolWindow_TextNote": "Text Note",
        "AnnotMark": "Bookmarks",
        "lastpagebtnHelp": "Last page",
        "firstpagebtnHelp": "First page",
        "aboubtnHelp": "About",
        "screenbtnHelp": "Open this application in full-screen mode",
        "helpbtnHelp": "Show help",
        "searchbtnHelp": "Search from pages",
        "pagesbtnHelp": "Take a look at the thumbnail of this brochure",
        "bookmarkbtnHelp": "Open Bookmarks",
        "AnnotmarkbtnHelp": "Open Table of content",
        "printbtnHelp": "Print the brochure",
        "soundbtnHelp": "Turn on or off the sound",
        "sharebtnHelp": "Send Email to",
        "socialSharebtnHelp": "Social Share",
        "zoominbtnHelp": "Zoom in",
        "downloadbtnHelp": "Downdlaod this brochure",
        "pagemodlebtnHelp": "Switch Single and double page mode",
        "languagebtnHelp": "Switch Lauguage",
        "annotationbtnHelp": "Add Annotation",
        "addbookmarkbtnHelp": "Add Bookmark",
        "removebookmarkbtnHelp": "Remove Bookmark",
        "updatebookmarkbtnHelp": "Update Bookmark",
        "btnShoppingCart": "Shopping Cart",
        "Help_ShoppingCartbtn": "Shopping Cart",
        "Help_btnNextPage": "Next page",
        "Help_btnPrePage": "Previous page",
        "Help_btnAutoFlip": "Auto filp",
        "Help_StopAutoFlip": "Stop atuo filp",
        "btnaddbookmark": "Add",
        "btndeletebookmark": "Delete",
        "btnupdatebookmark": "Update",
        "frmyourbookmarks": "Your bookmarks",
        "frmitems": "items",
        "DownloadFullPublication": "Full Publication",
        "DownloadCurrentPage": "Current Page",
        "DownloadAttachedFiles": "Attached Files",
        "btnCopy": "Copy Button",
        "infCopyToClipboard": "Your browser does not support clipboard.",
        "restorePage": "Would you like to restore your previous session?",
        "tmpl_Backgoundsoundon": "Background Sound On",
        "tmpl_Backgoundsoundoff": "Background Sound Off",
        "tmpl_Flipsoundon": "Flip Sound On",
        "tmpl_Flipsoundoff": "Flip Sound Off",
        "Help_PageIndex": "The current page number",
        "tmpl_PrintPageRanges": "PAGE RANGES",
        "tmpl_PrintPreview": "PREVIEW",
        "btnSelection": "Select Text",
        "loginNameLabel": "Name:",
        "btnGotoPage": "Go",
        "btnSettings": "Setting",
        "soundSettingTitle": "Sound Setting",
        "closeFlipSound": "Page-flipping Sound",
        "closeBackgroundSound": "Background Sound",
        "frmShareCaption": "Share",
        "frmShareLinkLabel": "Link:",
        "frmShareBtnCopy": "Copy",
        "frmShareItemsGroupCaption": "Social Share",
        "frmPanelTitle": "Share it",
        "frmShareQRcode": "QRCode",
        "TAnnoActionPropertyStuff_GotoPage": "Go to page",
        "btnPageBack": "Backward",
        "btnPageForward": "Forward",
        "SelectTextCopy": "Copy Selected Text",
        "selectCopyButton": "Copy",
        "TStuffCart_TypeCart": "Shopping Cart",
        "TStuffCart_DetailedQuantity": "Quantity",
        "TStuffCart_DetailedPrice": "Price",
        "ShappingCart_Close": "Close",
        "ShappingCart_CheckOut": "Checkout",
        "ShappingCart_Item": "Item",
        "ShappingCart_Total": "Total",
        "ShappingCart_AddCart": "Add to cart",
        "ShappingCart_InStock": "In Stock",
        "TStuffCart_DetailedCost": "Shipping cost",
        "TStuffCart_DetailedTime": "Delivery time",
        "TStuffCart_DetailedDay": "day(s)",
        "ShappingCart_NotStock": "Not enough in stock",
        "btnCrop": "Crop",
        "btnDragButton": "Drag",
        "btnFlipBook": "Flip Book",
        "btnSlideMode": "Slide Mode",
        "btnSinglePageMode": "Single Page Mode",
        "btnVertical": "Vertical Mode",
        "btnHotizontal": "Horizontal Mode",
        "btnClose": "Close",
        "btnBookStatus": "Book View",
        "checkBoxInsert": "Insert Current Page",
        "lblLast": "This is the last page.",
        "lblFirst": "This is the first page.",
        "lblFullscreen": "Click to view in fullscreen",
        "lblName": "Name",
        "lblPassword": "Password",
        "lblLogin": "Login",
        "lblCancel": "Cancel",
        "lblNoName": "User name can not be empty.",
        "lblNoPassword": "Password can not be empty.",
        "lblNoCorrectLogin": "Please enter the correct user name and password.",
        "btnVideo": "VideoGallery",
        "btnSlideShow": "SlideShow",
        "btnPositionToMove": "Move by mouse position",
        "lblHelp1": "Drag the page corner to view",
        "lblHelp2": "Double click to zoom in, out",
        "lblCopy": "Copy",
        "lblAddToPage": "add to page",
        "lblPage": "Page",
        "lblDescription": "Title",
        "lblEdit": "Edit",
        "lblDelete": "Delete",
        "lblRemoveAll": "RemoveAll",
        "tltCursor": "cursor",
        "tltAddHighlight": "add highlight",
        "tltAddTexts": "add texts",
        "tltAddShapes": "add shapes",
        "tltAddNotes": "add notes",
        "tltAddImageFile": "add image file",
        "tltAddSignature": "add signature",
        "tltAddLine": "add line",
        "tltAddArrow": "add arrow",
        "tltAddRect": "add rect",
        "tltAddEllipse": "add ellipse",
        "lblDoubleClickToZoomIn": "Double click to zoom in.",
        "frmShareLabel": "Share",
        "frmShareInfo": "You can easily share this publication to social networks.Just cilck the appropriatebutton below.",
        "frminsertLabel": "Insert to Site",
        "frminsertInfo": "Use the code below to embed this publication to your website.",
        "btnQRCode": "Click to scan QR code",
        "btnRotateLeft": "Rotate Left",
        "btnRotateRight": "Rotate Right",
        "lblSelectMode": "Select view mode please.",
        "frmDownloadPreview": "Preview",
        "frmDownload": "Download",
        "frmHowToUse": "How To Use",
        "lblHelpPage1": "Move your finger to flip the book page.",
        "lblHelpPage2": "Zoom in by using gesture or double click on the page.",
        "lblHelpPage3": "Click on the logo to reach the official website of the company.",
        "lblHelpPage4": "Add bookmarks, use search function and auto flip the book.",
        "lblHelpPage5": "Switch horizontal and vertical view on mobile devices.",
        "TTActionQuiz_PlayAgain": "Do you wanna play it again",
        "TTActionQuiz_Ration": "Your ratio is",
        "frmTelephone": "Telephone list",
        "btnDialing": "Dialing",
        "lblSelectMessage": "Please copy the the text content in the text box",
        "btnSelectText": "Select Text",
        "btnNote": "Annotation",
        "btnPhoneNumber": "Telephone",
        "btnWeCharShare": "WeChat Share",
        "btnMagnifierIn": "Magnifying Glass",
        "btnMagnifierOut": "Magnifier Reduction",
        "frmShareSmallProgram": "smallProgram",
        "btnMagnifier": "Magnifier",
        "frmPrintPrintLimitFailed": "Sorry, you can't print the pages.",
        "infNotSupportHtml5": "HTML5 is not supported by your current web browser, please read the book with latestverson web browser. Here we recommend you to read it with Chrome.",
        "btnReport": "Report",
        "btnDoubleSinglePage": "Page switch",
        "btnDownloadPosterPrompt": "Click to download the poster",
        "infLongPressToSavePoster": "Press and hold the mobile terminal to save the poster",
        "infLongPressToIndentify": "Long press to identify QR code",
        "infScanCodeToView": "Scan code to read",
        "frmaboutcaption": "Contact",
        "frmaboutDESCRIPTION": "Description",
        "frmaboutAUTHOR": "Author",
        "frmaboutADDRESS": "Address",
        "frmaboutEMAIL": "Email",
        "frmaboutWEBSITE": "Website",
        "frmaboutMOBILE": "Mobile",
        "infDeleteNote": "Do you want to delete the note?",
        "proFullScreenWarn": "Current browser does not support full-screen,Please use Chrome for best results",
        "btnBack": "Backs",
        "frmVideoListTitle": "Video list",
        "frmVideoTitle": "Video",
        "lblConfirm": "Confirm",
        "frmBookMark": "Book Mark",
        "btnExitFullscreen": "Exit fullscreen",
        "btnMore": "More",
        "frmPrintall": "Print All Pages",
        "frmPrintcurrent": "Print Current Page",
        "frmPrintRange": "Print Range",
        "frmPrintexample": "Example: 2,3,5-10",
        "frmPrintbtn": "Print",
        "frmaboutcontactinformation": "Contact Information",
        "frmSearch": "Search",
        "frmToc": "Table of Contents",
        "btnTableOfContent": "Show Table of Contents",
        "frmLinkLabel": "Link",
        "frmQrcodeCaption": "Scan the bottom two-dimensional code to view with mobile phone.",
        "btnLanguage": "Change Language",
        "msgConfigMissing": "Configuration file is missing, unable to open the book.",
        "lblSave": "Save",
        "accessRestrictedTitle": "Access Restricted",
        "enterYourName": "Enter your name",
        "enterVisitCode": "Please enter your password",
        "enterReadingCode": "enter your reading code",
        "enterTheReason": "Enter your reason for application",
        "enterPhoneNumber": "Enter your email address",
        "enterVerificationCode": "Enter your verification code",
        "getVerificationCode": "Send",
        "sendValidCodeSuccess": "Verification code sent",
        "getVerificationCodePrompt": "Get a verification code sent to your email",
        "enterPasswordPrompt": "Password required to proceed reading",
        "leaveMsgSimilarBooks": "Explore More Books",
        "leaveMsgToAuthor": "Contact Author",
        "leaveMsgName": "Your Name",
        "leaveMsgContact": "Your Contact Information (visible only to the author)",
        "leaveMsgEnter": "Please Enter the Message",
        "leaveMsgCancel": "Cancel",
        "leaveMsgCommitTitle": "Submit",
        "leaveMsgPrompt": "We will forward your message to the book uploader.",
        "leaveMsgErrorPrompt": "Exception occurred. Please try again later",
        "readingCodeErrorPrompt": "Invalid reading code. Please try again",
        "passwordErrorPrompt": "Invalid password. Please try again",
        "invalidPhoneNumber": "Invalid number. Please try again",
        "invalidEmail": "Invalid Email. Please try again",
        "verificationCodeErrorPrompt": "Invalid verification code. Please try again",
        "codeSendingFrequent": "Frequent operation, please try again later",
        "commiteTitle": "Verify",
        "shamStopTitle": "The author's account privileges have resulted in book access suspension.",
        "shamStopSubTitle": "Contact <a target='_blank' href='{%host}\/homepage\/{%uLink}\/' style='text-decoration: underline' >the author<\/a> for further information.",
        "shamStopLeavePrompt": "Please complete the question.",
        "shamStopLeaveMsgSuccessPrompt": "Send successfully",
        "codeSending": "Sending",
        "viewFullScreen": "Fullscreen",
        "cardsSign": "click to view card",
        "frmaboutViews": "Views",
        "btnMessage": "Message",
        "btnInstructions": "instructions",
        "btnArticlePages": "Pages",
        "btnArticleList": "Articles",
        "btnCalendar": "Calendar",
        "btnBook": "Book",
        "btnEnlarge": "Enlarge",
        "btnReduce": "Reduce",
        "btnPrevArticle": "Prev Article",
        "btnNextArticle": "Next Article",
        "copySuccessfully": "Copy Successfully",
        "cardsWechat": "Wechat",
        "cardsTelephone": "phone",
        "close": "close",
        "jumpPageByEnterNumber": "Enter the page number to jump quickly to the specified page",
        "jump": "Jump",
        "relatedContent": "related information",
        "brandTitleUndefined": "No brand name is set yet",
        "more": "More",
        "fold": "Put away",
        "otherWorks": "other works",
        "flipSound": "page turning sound",
        "backgroundSound": "Background music",
        "report": "report",
        "copySuccessTip": "copy successfully",
        "saveSuccessTip": "Saved successfully",
        "scanCodeAddMy": "After saving, WeChat scan the code and add my friend",
        "saveImg": "save Picture",
        "searchTheBook": "Search this book content",
        "historicalRecord": "history record",
        "searchResultCount": "A total of {%count} results",
        "noRelevantResults": "No relevant results",
        "changeTheKeyWords": "Try another keyword ~",
        "leastWordsTip": "Please enter at least 2 words",
        "jumpPageInputTip": "Enter the page number to jump quickly to the specified page",
        "jumpto": "Jump to",
        "foldThumbnailTip": "Click here to put away the thumbnail ~",
        "btnLoadingText": "In loading, it's fine soon",
        "btnTitleText": "Read now",
        "relatedInfoText": "Related Information",
        "brandContactFrTitle": "Contact the author",
        "shareFromPage": "Share starting from page N",
        "TStuffShowInformatin_Width": "Background width",
        "TStuffShowInformatin_Height": "Background height",
        "TPageList_BlankPage": "Blank page",
        "morePanelBookLink": "Link",
        "morePanelPoster": "Poster",
        "morePanelOtherShare": "Other",
        "doublePageTitle": "Enable Landscape Mode to Read in Two-page View",
        "doublePageAndroidTitle": "Enable Landscape Mode to Read in Two-page View?",
        "doublePageDescription": "How to set landscape ?",
        "doublePageGotIt": "Got it",
        "doublePageAndroidSettingStep1": "1.Allow auto-rotation in phone settings",
        "doublePageAndroidSettingStep2": "2.Allow landscape in browser settings",
        "doublePageAndroidSettingStep3": "3.Turn phone sideways to read",
        "doublePageIPhoneSettingStep1": "1.Disable portrait orientation lock",
        "doublePageIPhoneSettingStep2": "2.Rotate phone to read",
        "noFilesAvailablePrompt": "No Files Available!",
        "reportBtn": "Report",
        "reportConfirm": "Submit",
        "reportCancel": "Cancel",
        "reportAlertBoxCloseBtn": "Close",
        "reportTitle": "Please select the reason for reporting",
        "reportSuccessPrompt": "Report successful",
        "reportError": "Report failed",
        "reportNetworkError": "Report failed, request link error",
        "reportDescErrorPrompt": "Detailed description cannot be empty or contain only whitespace characters",
        "reportContactErrorPrompt": "Contact information cannot be empty or contain only whitespace characters",
        "reportTextareaPlaceholder": "Please provide detailed reasons for reporting (required)",
        "reportNumberPlaceholder": "Please provide a valid phone number for better understanding of the situation;otherwise, it will not be processed",
        "reportReasonSource": "Please select the reason for reporting; Piracy Copyright Infringement; Medical HealthPlastic Surgery False Advertising; Cult Violation of National Policies; Pornography GamblingDrugs Pyramid Scheme; Other reasons",
        "businessNone": "None",
        "lblSimulatePageFlip": "Simulate page-flipping on a computer",
        "lblSimulatePageSlide": "Tailor to the sliding habits on a tablet",
        "suspendedForExpiredMembership": "Due to the expiration of the account member service, the access to the book has been suspended by the system",
        "suspendedForMaxReadLimit": "Due to the account reading times being exhausted, the book has been suspended by the system",
        "suspendedForReadLimit": "Due to the limit on the number of readings, the access to the book has been suspended by the system",
        "suspendedForContact": "To resume it, you can contact the author directly.",
        "expiredRedirectButton": "Explore More Books",
        "btnPhoneticReading": "Listen",
        "btnPhoneticTips": "You can listen to and read this book at the same time.",
        "articleSummary": "Article Summary",
        "articleFirst": "This is the first article.",
        "articleLast": "This is the last article.",
        "articleBack": "Back",
        "multimediaSoundOn": "Music on",
        "multimediaSoundOff": "Music off",
        "downloadRestrictionTips": "Download access for this book is restricted by the publisher.",
        "encrpytionSearchTips": "The book has restricted access.<br\/>Please obtain permission before searching.",
        "chatbotBtnTips": "Hi~ Ask me about the book here!",
        "searchMatchType": "Split term search",
        "settingMultimediaSoundTitle": "Music",
        "settingMultimediaSoundPlayTips": "There are pages without music currently. Once music is enabled, it will only play on pages with music.",
        "settingMultimediaSoundPauseTips": "After music is disabled, pages with music will no longer play.",
        "downloadingTips": "Downloading...",
        "downloadSuccessfully": "Download successful!",
        "comment_title": "Reader Message",
        "comment_userNameTip": "Name",
        "comment_numTip": "Contact Number (visible to author only)",
        "comment_leaveMess": "Please enter your message",
        "comment_submitText": "Submit",
        "comment_emptyPrompt": "Be the first to post a message!",
        "comment_closeLeaveMessage1": "Sorry!",
        "comment_closeLeaveMessage2": "The author has disabled the display of messages",
        "comment_closeLeaveMessage3": "You cannot view other readers' messages",
        "comment_successMess": "Message submitted successfully",
        "comment_successShowText": "Your message will be displayed after admin approval",
        "comment_successHideText": "The admin will receive your message",
        "comment_successGotIt": "Got it",
        "comment_loadingText": "Loading, please wait...",
        "comment_noMoreText": "No more messages...",
        "comment_emptyErrorMsg": "Message content cannot be empty",
        "comment_specialErrorMsg": "Message content cannot contain special characters",
        "comment_frequentlyErrorMsg": "Sorry, you're posting too frequently. Please wait a moment before submitting again.",
        "comment_errorMsg": "Sorry, due to system busy, submission failed. Please try again later.",
        "comment_username": "Anonymous",
        "comment_authorName": "Author",
        "comment_replyMsg": "Reply",
        "accessLimitedText": "The book is protected. Please purchase it, or verify password \/ your email to continue reading.",
        "printRestrictionTips": "*Print access for this book is restricted by the publisher.",
        "lblVerifyPwdBtn": "Verify"
    }],
    "ols": [],
    "slideshow": [],
    "pageEditor": [],
    "flipByAudio": null,
    "downloadconfig": {
        "pdf": null,
        "isDownloadProject": false,
        "isDownloadAttach": false,
        "attachments": [],
        "hideDownloadSinglePage": false
    },
    "assistantConfig": null,
    "phoneNumber": [],
    "bookPlugin": null,
    "slider": [],
    "downloadConfig": null,
    "fliphtml5_pages": [{
        "n": ["ec0461212d86c1b552218b7b9b775a55.webp"],
        "t": ".\/files\/thumb\/f49399dd85e534f47b85a8938928aee7.webp"
    }, {
        "n": ["77b0fbb9802cc12f51735d1d30d68041.webp"],
        "t": ".\/files\/thumb\/f967ff760233c73266f76295bd912a8b.webp"
    }, {
        "n": ["9da66b6cd3b8f507cb0377682a1c1906.webp"],
        "t": ".\/files\/thumb\/e5589888e571b09de8a2eb7fa69966a0.webp"
    }, {
        "n": ["fc92df75a78561ae5f1135d478436895.webp"],
        "t": ".\/files\/thumb\/3abb26b406037edb757d3cc9f8124792.webp"
    }, {
        "n": ["89580c03dd7cf31dece69d36b05965b7.webp"],
        "t": ".\/files\/thumb\/5d6772721c6286dd9a31f0c682b17417.webp"
    }, {
        "n": ["d7ac5c2f5abc3ac98d86ec3bd78004ac.webp"],
        "t": ".\/files\/thumb\/43860cd6e0628802a47ed336f785030e.webp"
    }, {
        "n": ["7bcceea60ca0e5baea7f60b55c2c0716.webp"],
        "t": ".\/files\/thumb\/f03d4d52594fa343d231d5dec73d783c.webp"
    }, {
        "n": ["fe8211b66ca8808053dd9af1b9d14dc4.webp"],
        "t": ".\/files\/thumb\/9ea4de65a63124f450e49a576c56811e.webp"
    }, {
        "n": ["76d1d6f41aa2a2a758397f68ac8aab58.webp"],
        "t": ".\/files\/thumb\/f432c9382e576656f5237ddfe6b5842e.webp"
    }, {
        "n": ["8e860cdfa07376e4d2423a71017f708b.webp"],
        "t": ".\/files\/thumb\/e5534b52edb0a02c292e5b6bb79e0b01.webp"
    }, {
        "n": ["a5f43a61c62a57aea7bfb07305244567.webp"],
        "t": ".\/files\/thumb\/2113d0753a8b0f6f51eab28bae81677a.webp"
    }, {
        "n": ["d4e80c575768449498a6c599a9bb0d5d.webp"],
        "t": ".\/files\/thumb\/48bc386e301b138cc970911c99092c1e.webp"
    }, {
        "n": ["bb0ecc7dab5400c3fe5bdb8e25ebf5ef.webp"],
        "t": ".\/files\/thumb\/711548a4909267429f7ef2c00b621323.webp"
    }, {
        "n": ["a7d8b385f8af2a19a3dd6a95cbd287b7.webp"],
        "t": ".\/files\/thumb\/944073daabb176b27350be17813cd3d2.webp"
    }, {
        "n": ["54155ffa2e4461e13bdc6aa7810e6d65.webp"],
        "t": ".\/files\/thumb\/b6c9473fdea226bd6672e89e2eb3b545.webp"
    }, {
        "n": ["f5d0bbece265f17f10363cf163940766.webp"],
        "t": ".\/files\/thumb\/170a2ae398c15aba0dab2587fb659a95.webp"
    }, {
        "n": ["d596251fccb21f4816ed07c2eaf1d7da.webp"],
        "t": ".\/files\/thumb\/df17689568cc9158d8a8335cf729620b.webp"
    }, {
        "n": ["d413d13b4d830f9471748b359ef7d042.webp"],
        "t": ".\/files\/thumb\/9e3fe1539c05ca805b50d9808ebea32f.webp"
    }, {
        "n": ["5e220bbbe62e3835131ab6a67c4210aa.webp"],
        "t": ".\/files\/thumb\/d7bb61e0b87804114b54097cd080b8b9.webp"
    }, {
        "n": ["a59a4e53e004c9a93482b8ae8a8fb7b4.webp"],
        "t": ".\/files\/thumb\/fd6cbff4c33fc50b3f3313af0ba6d7ce.webp"
    }, {
        "n": ["f1d434c5528a5ef2a1be101bf7fe8915.webp"],
        "t": ".\/files\/thumb\/b3a676d8f6a4b3894a1c6c3199c8a3f8.webp"
    }, {
        "n": ["9a318beeaf60b028457d156a4b405b30.webp"],
        "t": ".\/files\/thumb\/19ace186d4fd6b1b80958c3b910a434f.webp"
    }, {
        "n": ["e4cd07033fac06c1209880e1f581d303.webp"],
        "t": ".\/files\/thumb\/5a6bc2eff6a70559df86ffe1a84884b7.webp"
    }, {
        "n": ["5913b710f37f008758e92354fca48b7f.webp"],
        "t": ".\/files\/thumb\/b1351fdf3286542bfdd36cc79ea6ea43.webp"
    }],
    "fileExist": {
        "pageEditor": 0,
        "updateEditorTime": 1752774091,
        "plugin": 0
    },
    "loadingConfig": {
        "loadingBackground": "#323232",
        "loadingCaptionColor": "#DDDDDD",
        "loadingCaption": "",
        "loadingCaptionFontSize": "20",
        "loadingPicture": "",
        "loadingPictureHeight": "150",
        "showLoadingGif": "Yes",
        "loadingVideo": "",
        "loadingDisplayTime": "0",
        "isEncryptionBook": false,
        "isFakeStopBook": 0
    }
};
